from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ActivityCode")


@_attrs_define
class ActivityCode:
    """ActivityCode Entity

    Attributes:
        code_type_object_id (int): The unique ID of the parent activity code type.
        code_value (str): The value of the activity code.
        code_concat_name (str | Unset):
        code_type_name (str | Unset): The name of the parent code type for this code.
        code_type_scope (str | Unset): The scope of the parent activity code type: Global, EPS, or Project. An activity
            code with Global scope can be assigned to any activity. An activity code with EPS scope can be assigned only to
            an activity within a project under that particular EPS. Similarly, an activity code with Project scope can be
            assigned only to an activity within that particular project.
        color (str | Unset): The Hex representation for the color e.g. 0xFFFFFF.
        create_date (datetime.datetime | Unset): The date this activity code was created.
        create_user (str | Unset): The name of the user that created this activity code.
        description (str | Unset): The description of the activity code.
        last_update_date (datetime.datetime | Unset): The date this activity code was last updated.
        last_update_user (str | Unset): The name of the user that last updated this activity code.
        object_id (int | Unset): The unique ID generated by the system.
        parent_object_id (int | Unset): The unique ID of the parent activity code of this activity code in the
            hierarchy.
        project_object_id (int | Unset): The unique project ID of the parent code type for this code if code type scope
            is 'Project' or 'EPS', null for code types with scope 'Global'.
        sequence_number (int | Unset): The sequence number for sorting.
    """

    code_type_object_id: int
    code_value: str
    code_concat_name: str | Unset = UNSET
    code_type_name: str | Unset = UNSET
    code_type_scope: str | Unset = UNSET
    color: str | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    description: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    parent_object_id: int | Unset = UNSET
    project_object_id: int | Unset = UNSET
    sequence_number: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        code_type_object_id = self.code_type_object_id

        code_value = self.code_value

        code_concat_name = self.code_concat_name

        code_type_name = self.code_type_name

        code_type_scope = self.code_type_scope

        color = self.color

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        description = self.description

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        parent_object_id = self.parent_object_id

        project_object_id = self.project_object_id

        sequence_number = self.sequence_number

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "CodeTypeObjectId": code_type_object_id,
                "CodeValue": code_value,
            }
        )
        if code_concat_name is not UNSET:
            field_dict["CodeConcatName"] = code_concat_name
        if code_type_name is not UNSET:
            field_dict["CodeTypeName"] = code_type_name
        if code_type_scope is not UNSET:
            field_dict["CodeTypeScope"] = code_type_scope
        if color is not UNSET:
            field_dict["Color"] = color
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if description is not UNSET:
            field_dict["Description"] = description
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if parent_object_id is not UNSET:
            field_dict["ParentObjectId"] = parent_object_id
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        code_type_object_id = d.pop("CodeTypeObjectId")

        code_value = d.pop("CodeValue")

        code_concat_name = d.pop("CodeConcatName", UNSET)

        code_type_name = d.pop("CodeTypeName", UNSET)

        code_type_scope = d.pop("CodeTypeScope", UNSET)

        color = d.pop("Color", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        description = d.pop("Description", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        parent_object_id = d.pop("ParentObjectId", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        activity_code = cls(
            code_type_object_id=code_type_object_id,
            code_value=code_value,
            code_concat_name=code_concat_name,
            code_type_name=code_type_name,
            code_type_scope=code_type_scope,
            color=color,
            create_date=create_date,
            create_user=create_user,
            description=description,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            parent_object_id=parent_object_id,
            project_object_id=project_object_id,
            sequence_number=sequence_number,
        )

        activity_code.additional_properties = d
        return activity_code

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
