from enum import Enum


class ActivityExpenseFieldItem(str, Enum):
    ACCRUALTYPE = "AccrualType"
    ACTIVITYID = "ActivityId"
    ACTIVITYNAME = "ActivityName"
    ACTIVITYOBJECTID = "ActivityObjectId"
    ACTUALCOST = "ActualCost"
    ACTUALUNITS = "ActualUnits"
    ATCOMPLETIONCOST = "AtCompletionCost"
    ATCOMPLETIONUNITS = "AtCompletionUnits"
    AUTOCOMPUTEACTUALS = "AutoComputeActuals"
    CBSCODE = "CBSCode"
    CBSID = "CBSId"
    COSTACCOUNTID = "CostAccountId"
    COSTACCOUNTNAME = "CostAccountName"
    COSTACCOUNTOBJECTID = "CostAccountObjectId"
    CREATEDATE = "CreateDate"
    CREATEUSER = "CreateUser"
    DOCUMENTNUMBER = "DocumentNumber"
    EXPENSECATEGORYNAME = "ExpenseCategoryName"
    EXPENSECATEGORYOBJECTID = "ExpenseCategoryObjectId"
    EXPENSEDESCRIPTION = "ExpenseDescription"
    EXPENSEITEM = "ExpenseItem"
    EXPENSEPERCENTCOMPLETE = "ExpensePercentComplete"
    ISBASELINE = "IsBaseline"
    ISTEMPLATE = "IsTemplate"
    LASTUPDATEDATE = "LastUpdateDate"
    LASTUPDATEUSER = "LastUpdateUser"
    OBJECTID = "ObjectId"
    OVERBUDGET = "OverBudget"
    PLANNEDCOST = "PlannedCost"
    PLANNEDUNITS = "PlannedUnits"
    PRICEPERUNIT = "PricePerUnit"
    PROJECTID = "ProjectId"
    PROJECTOBJECTID = "ProjectObjectId"
    REMAININGCOST = "RemainingCost"
    REMAININGUNITS = "RemainingUnits"
    UNITOFMEASURE = "UnitOfMeasure"
    VENDOR = "Vendor"
    WBSOBJECTID = "WBSObjectId"

    def __str__(self) -> str:
        return str(self.value)
