from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ActivityComment")


@_attrs_define
class ActivityComment:
    """ActivityComment Entity

    Attributes:
        activity_object_id (int): The unique ID of the activity to which this comment is added.
        comment_text (str): The comment.
        user_object_id (int): The unique ID of the user who added this comment.
        assignment_object_id (int | Unset):
        comment_date (datetime.datetime | Unset): The date on which this comment was added.
        create_date (datetime.datetime | Unset): The date this comment was created.
        create_user (str | Unset): The name of the user that created this comment.
        delete_date (datetime.datetime | Unset):
        delete_user (str | Unset):
        is_rejected (bool | Unset):
        last_update_date (datetime.datetime | Unset): The date this comment was last updated.
        last_update_user (str | Unset): The name of the user that last updated this comment.
        object_id (int | Unset): The unique ID generated by the system.
        personal_name (str | Unset): The commented user's personal or actual name.
        read_flag (bool | Unset): The flag that identifies whether a comment is read by a particular user.
        rejection_comments (str | Unset):
        time_diff (str | Unset): This field gives the time difference between current and createdate.
    """

    activity_object_id: int
    comment_text: str
    user_object_id: int
    assignment_object_id: int | Unset = UNSET
    comment_date: datetime.datetime | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    delete_date: datetime.datetime | Unset = UNSET
    delete_user: str | Unset = UNSET
    is_rejected: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    personal_name: str | Unset = UNSET
    read_flag: bool | Unset = UNSET
    rejection_comments: str | Unset = UNSET
    time_diff: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        activity_object_id = self.activity_object_id

        comment_text = self.comment_text

        user_object_id = self.user_object_id

        assignment_object_id = self.assignment_object_id

        comment_date: str | Unset = UNSET
        if not isinstance(self.comment_date, Unset):
            comment_date = self.comment_date.isoformat()

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        delete_date: str | Unset = UNSET
        if not isinstance(self.delete_date, Unset):
            delete_date = self.delete_date.isoformat()

        delete_user = self.delete_user

        is_rejected = self.is_rejected

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        personal_name = self.personal_name

        read_flag = self.read_flag

        rejection_comments = self.rejection_comments

        time_diff = self.time_diff

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ActivityObjectId": activity_object_id,
                "CommentText": comment_text,
                "UserObjectId": user_object_id,
            }
        )
        if assignment_object_id is not UNSET:
            field_dict["AssignmentObjectId"] = assignment_object_id
        if comment_date is not UNSET:
            field_dict["CommentDate"] = comment_date
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if delete_date is not UNSET:
            field_dict["DeleteDate"] = delete_date
        if delete_user is not UNSET:
            field_dict["DeleteUser"] = delete_user
        if is_rejected is not UNSET:
            field_dict["IsRejected"] = is_rejected
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if personal_name is not UNSET:
            field_dict["PersonalName"] = personal_name
        if read_flag is not UNSET:
            field_dict["ReadFlag"] = read_flag
        if rejection_comments is not UNSET:
            field_dict["RejectionComments"] = rejection_comments
        if time_diff is not UNSET:
            field_dict["TimeDiff"] = time_diff

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        activity_object_id = d.pop("ActivityObjectId")

        comment_text = d.pop("CommentText")

        user_object_id = d.pop("UserObjectId")

        assignment_object_id = d.pop("AssignmentObjectId", UNSET)

        _comment_date = d.pop("CommentDate", UNSET)
        comment_date: datetime.datetime | Unset
        if isinstance(_comment_date, Unset):
            comment_date = UNSET
        else:
            comment_date = isoparse(_comment_date)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        _delete_date = d.pop("DeleteDate", UNSET)
        delete_date: datetime.datetime | Unset
        if isinstance(_delete_date, Unset):
            delete_date = UNSET
        else:
            delete_date = isoparse(_delete_date)

        delete_user = d.pop("DeleteUser", UNSET)

        is_rejected = d.pop("IsRejected", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        personal_name = d.pop("PersonalName", UNSET)

        read_flag = d.pop("ReadFlag", UNSET)

        rejection_comments = d.pop("RejectionComments", UNSET)

        time_diff = d.pop("TimeDiff", UNSET)

        activity_comment = cls(
            activity_object_id=activity_object_id,
            comment_text=comment_text,
            user_object_id=user_object_id,
            assignment_object_id=assignment_object_id,
            comment_date=comment_date,
            create_date=create_date,
            create_user=create_user,
            delete_date=delete_date,
            delete_user=delete_user,
            is_rejected=is_rejected,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            personal_name=personal_name,
            read_flag=read_flag,
            rejection_comments=rejection_comments,
            time_diff=time_diff,
        )

        activity_comment.additional_properties = d
        return activity_comment

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
