from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="ActivityFilter")


@_attrs_define
class ActivityFilter:
    """ActivityFilter Entity

    Attributes:
        activity_filter_id (int): The unique ID generated by the system.
        activity_filter_name (str): The name of the Activity Filter.
        filter_criteria (str | Unset): Filter criteria for Activity Filter.
        filter_criteria_config (str | Unset):
        filter_type (str | Unset):
        user_id (int | Unset):
    """

    activity_filter_id: int
    activity_filter_name: str
    filter_criteria: str | Unset = UNSET
    filter_criteria_config: str | Unset = UNSET
    filter_type: str | Unset = UNSET
    user_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        activity_filter_id = self.activity_filter_id

        activity_filter_name = self.activity_filter_name

        filter_criteria = self.filter_criteria

        filter_criteria_config = self.filter_criteria_config

        filter_type = self.filter_type

        user_id = self.user_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ActivityFilterId": activity_filter_id,
                "ActivityFilterName": activity_filter_name,
            }
        )
        if filter_criteria is not UNSET:
            field_dict["FilterCriteria"] = filter_criteria
        if filter_criteria_config is not UNSET:
            field_dict["FilterCriteriaConfig"] = filter_criteria_config
        if filter_type is not UNSET:
            field_dict["FilterType"] = filter_type
        if user_id is not UNSET:
            field_dict["UserId"] = user_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        activity_filter_id = d.pop("ActivityFilterId")

        activity_filter_name = d.pop("ActivityFilterName")

        filter_criteria = d.pop("FilterCriteria", UNSET)

        filter_criteria_config = d.pop("FilterCriteriaConfig", UNSET)

        filter_type = d.pop("FilterType", UNSET)

        user_id = d.pop("UserId", UNSET)

        activity_filter = cls(
            activity_filter_id=activity_filter_id,
            activity_filter_name=activity_filter_name,
            filter_criteria=filter_criteria,
            filter_criteria_config=filter_criteria_config,
            filter_type=filter_type,
            user_id=user_id,
        )

        activity_filter.additional_properties = d
        return activity_filter

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
