from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ActivityCodeType")


@_attrs_define
class ActivityCodeType:
    """ActivityCodeType Entity

    Attributes:
        name (str): The name of the activity code type.
        create_date (datetime.datetime | Unset): The date this Activity Code Type was created.
        create_user (str | Unset): The name of the user that created this ActivityCodeType.
        eps_code_type_hierarchy (str | Unset): The field that maintains the EPS Activity Code Type Hierarchy.
        eps_object_id (int | Unset): The unique ID of the associated EPS.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_secure_code (bool | Unset): The flag indicating whether this is a secure Activity Code Type.
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this Activity Code Type was last updated.
        last_update_user (str | Unset): The name of the user that last updated this ActivityCodeType.
        length (int | Unset): The maximum number of characters allowed for values of this activity code.
        object_id (int | Unset): The unique ID generated by the system.
        project_object_id (int | Unset): The unique ID of the associated project.
        ref_project_object_ids (str | Unset): The unique ID associated with a project whose activities have this code
            assigned. This data is only exported if more than one project is included in the export and if more than one
            project contains activities to which the EPS scoped activity code is assigned.
        scope (str | Unset): The scope of the code type: Global, EPS, or Project. An activity code with Global scope can
            be assigned to any activity. An activity code with EPS scope can be assigned only to an activity within a
            project under that particular EPS. Similarly, an activity code with Project scope can be assigned only to an
            activity within that particular project.
        sequence_number (int | Unset): The sequence number for sorting.
    """

    name: str
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    eps_code_type_hierarchy: str | Unset = UNSET
    eps_object_id: int | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_secure_code: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    length: int | Unset = UNSET
    object_id: int | Unset = UNSET
    project_object_id: int | Unset = UNSET
    ref_project_object_ids: str | Unset = UNSET
    scope: str | Unset = UNSET
    sequence_number: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        eps_code_type_hierarchy = self.eps_code_type_hierarchy

        eps_object_id = self.eps_object_id

        is_baseline = self.is_baseline

        is_secure_code = self.is_secure_code

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        length = self.length

        object_id = self.object_id

        project_object_id = self.project_object_id

        ref_project_object_ids = self.ref_project_object_ids

        scope = self.scope

        sequence_number = self.sequence_number

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Name": name,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if eps_code_type_hierarchy is not UNSET:
            field_dict["EPSCodeTypeHierarchy"] = eps_code_type_hierarchy
        if eps_object_id is not UNSET:
            field_dict["EPSObjectId"] = eps_object_id
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_secure_code is not UNSET:
            field_dict["IsSecureCode"] = is_secure_code
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if length is not UNSET:
            field_dict["Length"] = length
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if ref_project_object_ids is not UNSET:
            field_dict["RefProjectObjectIds"] = ref_project_object_ids
        if scope is not UNSET:
            field_dict["Scope"] = scope
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("Name")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        eps_code_type_hierarchy = d.pop("EPSCodeTypeHierarchy", UNSET)

        eps_object_id = d.pop("EPSObjectId", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_secure_code = d.pop("IsSecureCode", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        length = d.pop("Length", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        ref_project_object_ids = d.pop("RefProjectObjectIds", UNSET)

        scope = d.pop("Scope", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        activity_code_type = cls(
            name=name,
            create_date=create_date,
            create_user=create_user,
            eps_code_type_hierarchy=eps_code_type_hierarchy,
            eps_object_id=eps_object_id,
            is_baseline=is_baseline,
            is_secure_code=is_secure_code,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            length=length,
            object_id=object_id,
            project_object_id=project_object_id,
            ref_project_object_ids=ref_project_object_ids,
            scope=scope,
            sequence_number=sequence_number,
        )

        activity_code_type.additional_properties = d
        return activity_code_type

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
