from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ActivityStepTemplateItem")


@_attrs_define
class ActivityStepTemplateItem:
    """ActivityStepTemplateItem Entity

    Attributes:
        activity_step_template_object_id (int | Unset): The unique ID of the activity step template to which this item
            belongs.
        create_date (datetime.datetime | Unset): The date this activity step template item was created.
        create_user (str | Unset): The name of the user that created this activity step template item.
        description (str | Unset): The description of the activity step.
        last_update_date (datetime.datetime | Unset): The date this activity step template item was last updated.
        last_update_user (str | Unset): The name of the user that last updated this activity step template item.
        name (str | Unset): The name of the activity step template item.
        object_id (int | Unset): The unique ID generated by the system.
        sequence_number (int | Unset): The sequence number for sorting.
        weight (float | Unset): The weight that is assigned to the step. This is a user defined field that is used to
            calculate the physical percent complete when the project option is set.
    """

    activity_step_template_object_id: int | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    description: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    name: str | Unset = UNSET
    object_id: int | Unset = UNSET
    sequence_number: int | Unset = UNSET
    weight: float | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        activity_step_template_object_id = self.activity_step_template_object_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        description = self.description

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        name = self.name

        object_id = self.object_id

        sequence_number = self.sequence_number

        weight = self.weight

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if activity_step_template_object_id is not UNSET:
            field_dict["ActivityStepTemplateObjectId"] = activity_step_template_object_id
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if description is not UNSET:
            field_dict["Description"] = description
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if name is not UNSET:
            field_dict["Name"] = name
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number
        if weight is not UNSET:
            field_dict["Weight"] = weight

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        activity_step_template_object_id = d.pop("ActivityStepTemplateObjectId", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        description = d.pop("Description", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        name = d.pop("Name", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        weight = d.pop("Weight", UNSET)

        activity_step_template_item = cls(
            activity_step_template_object_id=activity_step_template_object_id,
            create_date=create_date,
            create_user=create_user,
            description=description,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            name=name,
            object_id=object_id,
            sequence_number=sequence_number,
            weight=weight,
        )

        activity_step_template_item.additional_properties = d
        return activity_step_template_item

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
