from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ActivityStep")


@_attrs_define
class ActivityStep:
    """ActivityStep Entity

    Attributes:
        activity_name (str): The name of the activity. The activity name does not have to be unique.
        activity_object_id (int): The unique ID of the activity to which the steps are assigned.
        activity_id (str | Unset): The short ID that uniquely identifies the activity within the project.
        create_date (datetime.datetime | Unset): The date this activity step was created.
        create_user (str | Unset): The name of the user that created this activity step.
        description (str | Unset): The description of the activity step.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_completed (bool | Unset): The flag that indicates whether the step has been completed.
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this activity step was last updated.
        last_update_user (str | Unset): The name of the user that last updated this activity step.
        name (str | Unset): The name of the activity step.
        object_id (int | Unset): The unique ID generated by the system.
        percent_complete (float | Unset): The percent complete for the step.
        project_id (str | Unset): The short code that uniquely identifies the project.
        project_object_id (int | Unset): The unique ID of the associated project.
        sequence_number (int | Unset): The sequence number for sorting.
        wbs_object_id (int | Unset): The unique ID of the WBS for the activity.
        weight (float | Unset): The weight that is assigned to the step. This is a user defined field that is used to
            calculate the physical percent complete when the project option is set.
        weight_percent (float | Unset): The non-editable field that displays the percentage amount that corresponds to
            the step. It is calculated by taking the weight of the step and dividing it by the total of all weights for the
            activity.
    """

    activity_name: str
    activity_object_id: int
    activity_id: str | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    description: str | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_completed: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    name: str | Unset = UNSET
    object_id: int | Unset = UNSET
    percent_complete: float | Unset = UNSET
    project_id: str | Unset = UNSET
    project_object_id: int | Unset = UNSET
    sequence_number: int | Unset = UNSET
    wbs_object_id: int | Unset = UNSET
    weight: float | Unset = UNSET
    weight_percent: float | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        activity_name = self.activity_name

        activity_object_id = self.activity_object_id

        activity_id = self.activity_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        description = self.description

        is_baseline = self.is_baseline

        is_completed = self.is_completed

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        name = self.name

        object_id = self.object_id

        percent_complete = self.percent_complete

        project_id = self.project_id

        project_object_id = self.project_object_id

        sequence_number = self.sequence_number

        wbs_object_id = self.wbs_object_id

        weight = self.weight

        weight_percent = self.weight_percent

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ActivityName": activity_name,
                "ActivityObjectId": activity_object_id,
            }
        )
        if activity_id is not UNSET:
            field_dict["ActivityId"] = activity_id
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if description is not UNSET:
            field_dict["Description"] = description
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_completed is not UNSET:
            field_dict["IsCompleted"] = is_completed
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if name is not UNSET:
            field_dict["Name"] = name
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if percent_complete is not UNSET:
            field_dict["PercentComplete"] = percent_complete
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number
        if wbs_object_id is not UNSET:
            field_dict["WBSObjectId"] = wbs_object_id
        if weight is not UNSET:
            field_dict["Weight"] = weight
        if weight_percent is not UNSET:
            field_dict["WeightPercent"] = weight_percent

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        activity_name = d.pop("ActivityName")

        activity_object_id = d.pop("ActivityObjectId")

        activity_id = d.pop("ActivityId", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        description = d.pop("Description", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_completed = d.pop("IsCompleted", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        name = d.pop("Name", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        percent_complete = d.pop("PercentComplete", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        wbs_object_id = d.pop("WBSObjectId", UNSET)

        weight = d.pop("Weight", UNSET)

        weight_percent = d.pop("WeightPercent", UNSET)

        activity_step = cls(
            activity_name=activity_name,
            activity_object_id=activity_object_id,
            activity_id=activity_id,
            create_date=create_date,
            create_user=create_user,
            description=description,
            is_baseline=is_baseline,
            is_completed=is_completed,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            name=name,
            object_id=object_id,
            percent_complete=percent_complete,
            project_id=project_id,
            project_object_id=project_object_id,
            sequence_number=sequence_number,
            wbs_object_id=wbs_object_id,
            weight=weight,
            weight_percent=weight_percent,
        )

        activity_step.additional_properties = d
        return activity_step

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
