from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.holiday_or_exceptions import HolidayOrExceptions
    from ..models.standard_work_week import StandardWorkWeek


T = TypeVar("T", bound="Calendar")


@_attrs_define
class Calendar:
    """Calendar Entity

    Attributes:
        name (str): The name of the calendar.
        type_ (str): The calendar type - either 'Global', 'Resource', or 'Project'. 'Global' calendars can be assigned
            to projects and resources. 'Resource' calendars can be assigned only to resources. 'Project' calendars are
            specific to projects.
        base_calendar_object_id (int | Unset): The unique ID of the global calendar to which this calendar is linked.
            Any changes to the global calendar are automatically propagated to this calendar.
        create_date (datetime.datetime | Unset): The date this calendar was created.
        create_user (str | Unset): The name of the user that created this calendar.
        hours_per_day (float | Unset): The number of work hours per day. This conversion factor is used for displaying
            time units and durations in the user's selected display formats.
        hours_per_month (float | Unset): The number of work hours per month. This conversion factor is used for
            displaying time units and durations in the user's selected display formats.
        hours_per_week (float | Unset): The number of work hours per week. This conversion factor is used for displaying
            time units and durations in the user's selected display formats.
        hours_per_year (float | Unset): The number of work hours per year. This conversion factor is used for displaying
            time units and durations in the user's selected display formats.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_default (bool | Unset): The flag that identifies the default global calendar (applies to global calendars
            only).
        is_personal (bool | Unset): The flag indicating if this calendar is a personal calendar (applies to resource
            calendars only).
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this calendar was last updated.
        last_update_user (str | Unset): The name of the user that last updated this calendar.
        object_id (int | Unset): The unique ID generated by the system.
        project_id (str | Unset): The ID for the project for which this change request is associated.
        project_object_id (int | Unset): The unique ID of the associated project.
        standard_work_week (StandardWorkWeek | Unset):
        holiday_or_exceptions (HolidayOrExceptions | Unset): HolidayOrExceptions
    """

    name: str
    type_: str
    base_calendar_object_id: int | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    hours_per_day: float | Unset = UNSET
    hours_per_month: float | Unset = UNSET
    hours_per_week: float | Unset = UNSET
    hours_per_year: float | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_default: bool | Unset = UNSET
    is_personal: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    project_id: str | Unset = UNSET
    project_object_id: int | Unset = UNSET
    standard_work_week: StandardWorkWeek | Unset = UNSET
    holiday_or_exceptions: HolidayOrExceptions | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        type_ = self.type_

        base_calendar_object_id = self.base_calendar_object_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        hours_per_day = self.hours_per_day

        hours_per_month = self.hours_per_month

        hours_per_week = self.hours_per_week

        hours_per_year = self.hours_per_year

        is_baseline = self.is_baseline

        is_default = self.is_default

        is_personal = self.is_personal

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        project_id = self.project_id

        project_object_id = self.project_object_id

        standard_work_week: dict[str, Any] | Unset = UNSET
        if not isinstance(self.standard_work_week, Unset):
            standard_work_week = self.standard_work_week.to_dict()

        holiday_or_exceptions: dict[str, Any] | Unset = UNSET
        if not isinstance(self.holiday_or_exceptions, Unset):
            holiday_or_exceptions = self.holiday_or_exceptions.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Name": name,
                "Type": type_,
            }
        )
        if base_calendar_object_id is not UNSET:
            field_dict["BaseCalendarObjectId"] = base_calendar_object_id
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if hours_per_day is not UNSET:
            field_dict["HoursPerDay"] = hours_per_day
        if hours_per_month is not UNSET:
            field_dict["HoursPerMonth"] = hours_per_month
        if hours_per_week is not UNSET:
            field_dict["HoursPerWeek"] = hours_per_week
        if hours_per_year is not UNSET:
            field_dict["HoursPerYear"] = hours_per_year
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_default is not UNSET:
            field_dict["IsDefault"] = is_default
        if is_personal is not UNSET:
            field_dict["IsPersonal"] = is_personal
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if standard_work_week is not UNSET:
            field_dict["StandardWorkWeek"] = standard_work_week
        if holiday_or_exceptions is not UNSET:
            field_dict["HolidayOrExceptions"] = holiday_or_exceptions

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.holiday_or_exceptions import HolidayOrExceptions
        from ..models.standard_work_week import StandardWorkWeek

        d = dict(src_dict)
        name = d.pop("Name")

        type_ = d.pop("Type")

        base_calendar_object_id = d.pop("BaseCalendarObjectId", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        hours_per_day = d.pop("HoursPerDay", UNSET)

        hours_per_month = d.pop("HoursPerMonth", UNSET)

        hours_per_week = d.pop("HoursPerWeek", UNSET)

        hours_per_year = d.pop("HoursPerYear", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_default = d.pop("IsDefault", UNSET)

        is_personal = d.pop("IsPersonal", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        _standard_work_week = d.pop("StandardWorkWeek", UNSET)
        standard_work_week: StandardWorkWeek | Unset
        if isinstance(_standard_work_week, Unset):
            standard_work_week = UNSET
        else:
            standard_work_week = StandardWorkWeek.from_dict(_standard_work_week)

        _holiday_or_exceptions = d.pop("HolidayOrExceptions", UNSET)
        holiday_or_exceptions: HolidayOrExceptions | Unset
        if isinstance(_holiday_or_exceptions, Unset):
            holiday_or_exceptions = UNSET
        else:
            holiday_or_exceptions = HolidayOrExceptions.from_dict(_holiday_or_exceptions)

        calendar = cls(
            name=name,
            type_=type_,
            base_calendar_object_id=base_calendar_object_id,
            create_date=create_date,
            create_user=create_user,
            hours_per_day=hours_per_day,
            hours_per_month=hours_per_month,
            hours_per_week=hours_per_week,
            hours_per_year=hours_per_year,
            is_baseline=is_baseline,
            is_default=is_default,
            is_personal=is_personal,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            project_id=project_id,
            project_object_id=project_object_id,
            standard_work_week=standard_work_week,
            holiday_or_exceptions=holiday_or_exceptions,
        )

        calendar.additional_properties = d
        return calendar

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
