from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="CBS")


@_attrs_define
class CBS:
    """CBS Entity

    Attributes:
        cbs_code (str): The unique name of the Unifier CBS Code. Assign CBS codes to activities so that you can filter
            which activities you will send to Unifier.
        project_object_id (int): The unique ID of the associated project.
        cbs_description (str | Unset): The description of the associated CBS.
        cbs_status (str | Unset): Specifies the status of the CBS.
        create_date (datetime.datetime | Unset): The date this activity was created.
        create_user (str | Unset): The name of the user that created this activity.
        last_update_date (datetime.datetime | Unset): The date this activity was last updated.
        last_update_user (str | Unset): The name of the user that last updated this activity.
        object_id (int | Unset): The unique ID generated by the system.
        parent_object_id (int | Unset): The unique ID of the parent CBS for this CBS in the hierarchy.
    """

    cbs_code: str
    project_object_id: int
    cbs_description: str | Unset = UNSET
    cbs_status: str | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    parent_object_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        cbs_code = self.cbs_code

        project_object_id = self.project_object_id

        cbs_description = self.cbs_description

        cbs_status = self.cbs_status

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        parent_object_id = self.parent_object_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "CBSCode": cbs_code,
                "ProjectObjectId": project_object_id,
            }
        )
        if cbs_description is not UNSET:
            field_dict["CBSDescription"] = cbs_description
        if cbs_status is not UNSET:
            field_dict["CBSStatus"] = cbs_status
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if parent_object_id is not UNSET:
            field_dict["ParentObjectId"] = parent_object_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        cbs_code = d.pop("CBSCode")

        project_object_id = d.pop("ProjectObjectId")

        cbs_description = d.pop("CBSDescription", UNSET)

        cbs_status = d.pop("CBSStatus", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        parent_object_id = d.pop("ParentObjectId", UNSET)

        cbs = cls(
            cbs_code=cbs_code,
            project_object_id=project_object_id,
            cbs_description=cbs_description,
            cbs_status=cbs_status,
            create_date=create_date,
            create_user=create_user,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            parent_object_id=parent_object_id,
        )

        cbs.additional_properties = d
        return cbs

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
