from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="CostAccount")


@_attrs_define
class CostAccount:
    """CostAccount Entity

    Attributes:
        id (str): The short ID assigned to each cost account for identification. Each cost account is uniquely
            identified by concatenating its own ID together with its parents' IDs.
        name (str): The name of the cost account.
        create_date (datetime.datetime | Unset): The date this account was created.
        create_user (str | Unset): The name of the user that created this account.
        description (str | Unset): The description of the cost account.
        last_update_date (datetime.datetime | Unset): The date this account was last updated.
        last_update_user (str | Unset): The name of the user that last updated this account.
        object_id (int | Unset): The unique ID generated by the system.
        parent_object_id (int | Unset): The unique ID of the parent cost account of this cost account in the hierarchy.
        sequence_number (int | Unset): The sequence number for sorting.
    """

    id: str
    name: str
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    description: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    parent_object_id: int | Unset = UNSET
    sequence_number: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        name = self.name

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        description = self.description

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        parent_object_id = self.parent_object_id

        sequence_number = self.sequence_number

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Id": id,
                "Name": name,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if description is not UNSET:
            field_dict["Description"] = description
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if parent_object_id is not UNSET:
            field_dict["ParentObjectId"] = parent_object_id
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("Id")

        name = d.pop("Name")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        description = d.pop("Description", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        parent_object_id = d.pop("ParentObjectId", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        cost_account = cls(
            id=id,
            name=name,
            create_date=create_date,
            create_user=create_user,
            description=description,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            parent_object_id=parent_object_id,
            sequence_number=sequence_number,
        )

        cost_account.additional_properties = d
        return cost_account

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
