from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="Currency")


@_attrs_define
class Currency:
    """Currency Entity

    Attributes:
        id (str): The unique currency abbreviation for each currency.
        name (str): The name of the currency.
        symbol (str): The currency symbol displayed.
        create_date (datetime.datetime | Unset): The date this currency was created.
        create_user (str | Unset): The name of the user that created this currency.
        decimal_places (int | Unset): The number of decimal places displayed.
        decimal_symbol (str | Unset): The decimal symbol displayed.
        digit_grouping_symbol (str | Unset): The symbol used to group the numbers.
        exchange_rate (float | Unset): The exchange rate against the base currency.
        is_base_currency (bool | Unset): The currency used to store cost in the Project Management database. The
            exchange rate for the base currency is always 1.0. The base currency ID, name, and symbol default to U.S.
            dollars and can be edited but never deleted.
        last_update_date (datetime.datetime | Unset): The date this currency was last updated.
        last_update_user (str | Unset): The name of the user that last updated this currency.
        negative_symbol (str | Unset): The symbol used to display a negative currency.
        object_id (int | Unset): The unique ID generated by the system.
        positive_symbol (str | Unset): The symbol used to display a positive currency.
    """

    id: str
    name: str
    symbol: str
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    decimal_places: int | Unset = UNSET
    decimal_symbol: str | Unset = UNSET
    digit_grouping_symbol: str | Unset = UNSET
    exchange_rate: float | Unset = UNSET
    is_base_currency: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    negative_symbol: str | Unset = UNSET
    object_id: int | Unset = UNSET
    positive_symbol: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        name = self.name

        symbol = self.symbol

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        decimal_places = self.decimal_places

        decimal_symbol = self.decimal_symbol

        digit_grouping_symbol = self.digit_grouping_symbol

        exchange_rate = self.exchange_rate

        is_base_currency = self.is_base_currency

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        negative_symbol = self.negative_symbol

        object_id = self.object_id

        positive_symbol = self.positive_symbol

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Id": id,
                "Name": name,
                "Symbol": symbol,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if decimal_places is not UNSET:
            field_dict["DecimalPlaces"] = decimal_places
        if decimal_symbol is not UNSET:
            field_dict["DecimalSymbol"] = decimal_symbol
        if digit_grouping_symbol is not UNSET:
            field_dict["DigitGroupingSymbol"] = digit_grouping_symbol
        if exchange_rate is not UNSET:
            field_dict["ExchangeRate"] = exchange_rate
        if is_base_currency is not UNSET:
            field_dict["IsBaseCurrency"] = is_base_currency
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if negative_symbol is not UNSET:
            field_dict["NegativeSymbol"] = negative_symbol
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if positive_symbol is not UNSET:
            field_dict["PositiveSymbol"] = positive_symbol

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("Id")

        name = d.pop("Name")

        symbol = d.pop("Symbol")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        decimal_places = d.pop("DecimalPlaces", UNSET)

        decimal_symbol = d.pop("DecimalSymbol", UNSET)

        digit_grouping_symbol = d.pop("DigitGroupingSymbol", UNSET)

        exchange_rate = d.pop("ExchangeRate", UNSET)

        is_base_currency = d.pop("IsBaseCurrency", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        negative_symbol = d.pop("NegativeSymbol", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        positive_symbol = d.pop("PositiveSymbol", UNSET)

        currency = cls(
            id=id,
            name=name,
            symbol=symbol,
            create_date=create_date,
            create_user=create_user,
            decimal_places=decimal_places,
            decimal_symbol=decimal_symbol,
            digit_grouping_symbol=digit_grouping_symbol,
            exchange_rate=exchange_rate,
            is_base_currency=is_base_currency,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            negative_symbol=negative_symbol,
            object_id=object_id,
            positive_symbol=positive_symbol,
        )

        currency.additional_properties = d
        return currency

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
