from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="Document")


@_attrs_define
class Document:
    """Document Entity

    Attributes:
        project_object_id (int): The unique ID of the associated project.
        title (str): The title or name of a project work product or document.
        activity_object_id (int | Unset):
        author (str | Unset): The person who created the work product or document.
        content_repository_document_internal_id (str | Unset): The internal ID of the content repository document.
        create_date (datetime.datetime | Unset): The date this document was created.
        create_user (str | Unset): The name of the user that created this document.
        deliverable (bool | Unset): The flag that indicates that the work product or document is a project deliverable.
        description (str | Unset): The narrative description of the work product or document.
        document_category_name (str | Unset): The name of the associated document category.
        document_category_object_id (int | Unset): The unique ID of the associated document category.
        document_status_code_name (str | Unset): The name of the associated document status code.
        document_status_code_object_id (int | Unset): The unique ID of the associated document status code.
        document_type (str | Unset): The type of document: 'Non-Collaboration' or 'Collaboration'.
        guid (str | Unset): The globally unique ID generated by the system.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this document was last updated.
        last_update_user (str | Unset): The name of the user that last updated this document.
        object_id (int | Unset): The unique ID generated by the system.
        parent_object_id (int | Unset): The unique ID of the parent document of this document in the hierarchy.
        private_location (str | Unset): The work product or document's private file location.
        project_id (str | Unset): The short code that uniquely identifies the project.
        public_location (str | Unset): The work product or document's publicly-accessible file location.
        reference_number (str | Unset): The work product or document's reference or catalog number.
        resource_id (str | Unset): The short code that uniquely identifies the associated resource.
        resource_name (str | Unset): The name of the associated resource.
        resource_object_id (int | Unset): The unique ID of the associated resource.
        revision_date (datetime.datetime | Unset): The date of the work product or document's last update.
        sequence_number (int | Unset): The sequence number for sorting.
        version (str | Unset): The work product or document's version number.
    """

    project_object_id: int
    title: str
    activity_object_id: int | Unset = UNSET
    author: str | Unset = UNSET
    content_repository_document_internal_id: str | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    deliverable: bool | Unset = UNSET
    description: str | Unset = UNSET
    document_category_name: str | Unset = UNSET
    document_category_object_id: int | Unset = UNSET
    document_status_code_name: str | Unset = UNSET
    document_status_code_object_id: int | Unset = UNSET
    document_type: str | Unset = UNSET
    guid: str | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    parent_object_id: int | Unset = UNSET
    private_location: str | Unset = UNSET
    project_id: str | Unset = UNSET
    public_location: str | Unset = UNSET
    reference_number: str | Unset = UNSET
    resource_id: str | Unset = UNSET
    resource_name: str | Unset = UNSET
    resource_object_id: int | Unset = UNSET
    revision_date: datetime.datetime | Unset = UNSET
    sequence_number: int | Unset = UNSET
    version: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        project_object_id = self.project_object_id

        title = self.title

        activity_object_id = self.activity_object_id

        author = self.author

        content_repository_document_internal_id = self.content_repository_document_internal_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        deliverable = self.deliverable

        description = self.description

        document_category_name = self.document_category_name

        document_category_object_id = self.document_category_object_id

        document_status_code_name = self.document_status_code_name

        document_status_code_object_id = self.document_status_code_object_id

        document_type = self.document_type

        guid = self.guid

        is_baseline = self.is_baseline

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        parent_object_id = self.parent_object_id

        private_location = self.private_location

        project_id = self.project_id

        public_location = self.public_location

        reference_number = self.reference_number

        resource_id = self.resource_id

        resource_name = self.resource_name

        resource_object_id = self.resource_object_id

        revision_date: str | Unset = UNSET
        if not isinstance(self.revision_date, Unset):
            revision_date = self.revision_date.isoformat()

        sequence_number = self.sequence_number

        version = self.version

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ProjectObjectId": project_object_id,
                "Title": title,
            }
        )
        if activity_object_id is not UNSET:
            field_dict["ActivityObjectId"] = activity_object_id
        if author is not UNSET:
            field_dict["Author"] = author
        if content_repository_document_internal_id is not UNSET:
            field_dict["ContentRepositoryDocumentInternalId"] = content_repository_document_internal_id
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if deliverable is not UNSET:
            field_dict["Deliverable"] = deliverable
        if description is not UNSET:
            field_dict["Description"] = description
        if document_category_name is not UNSET:
            field_dict["DocumentCategoryName"] = document_category_name
        if document_category_object_id is not UNSET:
            field_dict["DocumentCategoryObjectId"] = document_category_object_id
        if document_status_code_name is not UNSET:
            field_dict["DocumentStatusCodeName"] = document_status_code_name
        if document_status_code_object_id is not UNSET:
            field_dict["DocumentStatusCodeObjectId"] = document_status_code_object_id
        if document_type is not UNSET:
            field_dict["DocumentType"] = document_type
        if guid is not UNSET:
            field_dict["GUID"] = guid
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if parent_object_id is not UNSET:
            field_dict["ParentObjectId"] = parent_object_id
        if private_location is not UNSET:
            field_dict["PrivateLocation"] = private_location
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if public_location is not UNSET:
            field_dict["PublicLocation"] = public_location
        if reference_number is not UNSET:
            field_dict["ReferenceNumber"] = reference_number
        if resource_id is not UNSET:
            field_dict["ResourceId"] = resource_id
        if resource_name is not UNSET:
            field_dict["ResourceName"] = resource_name
        if resource_object_id is not UNSET:
            field_dict["ResourceObjectId"] = resource_object_id
        if revision_date is not UNSET:
            field_dict["RevisionDate"] = revision_date
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number
        if version is not UNSET:
            field_dict["Version"] = version

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        project_object_id = d.pop("ProjectObjectId")

        title = d.pop("Title")

        activity_object_id = d.pop("ActivityObjectId", UNSET)

        author = d.pop("Author", UNSET)

        content_repository_document_internal_id = d.pop("ContentRepositoryDocumentInternalId", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        deliverable = d.pop("Deliverable", UNSET)

        description = d.pop("Description", UNSET)

        document_category_name = d.pop("DocumentCategoryName", UNSET)

        document_category_object_id = d.pop("DocumentCategoryObjectId", UNSET)

        document_status_code_name = d.pop("DocumentStatusCodeName", UNSET)

        document_status_code_object_id = d.pop("DocumentStatusCodeObjectId", UNSET)

        document_type = d.pop("DocumentType", UNSET)

        guid = d.pop("GUID", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        parent_object_id = d.pop("ParentObjectId", UNSET)

        private_location = d.pop("PrivateLocation", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        public_location = d.pop("PublicLocation", UNSET)

        reference_number = d.pop("ReferenceNumber", UNSET)

        resource_id = d.pop("ResourceId", UNSET)

        resource_name = d.pop("ResourceName", UNSET)

        resource_object_id = d.pop("ResourceObjectId", UNSET)

        _revision_date = d.pop("RevisionDate", UNSET)
        revision_date: datetime.datetime | Unset
        if isinstance(_revision_date, Unset):
            revision_date = UNSET
        else:
            revision_date = isoparse(_revision_date)

        sequence_number = d.pop("SequenceNumber", UNSET)

        version = d.pop("Version", UNSET)

        document = cls(
            project_object_id=project_object_id,
            title=title,
            activity_object_id=activity_object_id,
            author=author,
            content_repository_document_internal_id=content_repository_document_internal_id,
            create_date=create_date,
            create_user=create_user,
            deliverable=deliverable,
            description=description,
            document_category_name=document_category_name,
            document_category_object_id=document_category_object_id,
            document_status_code_name=document_status_code_name,
            document_status_code_object_id=document_status_code_object_id,
            document_type=document_type,
            guid=guid,
            is_baseline=is_baseline,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            parent_object_id=parent_object_id,
            private_location=private_location,
            project_id=project_id,
            public_location=public_location,
            reference_number=reference_number,
            resource_id=resource_id,
            resource_name=resource_name,
            resource_object_id=resource_object_id,
            revision_date=revision_date,
            sequence_number=sequence_number,
            version=version,
        )

        document.additional_properties = d
        return document

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
