from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="EPSBudgetChangeLog")


@_attrs_define
class EPSBudgetChangeLog:
    """EPSBudgetChangeLog Entity

    Attributes:
        change_number (str): The change number that is automatically incremented according to when changes are added.
            This can be changed to any number.
        eps_object_id (int): The unique ID of the EPS element to which the budget change log applies.
        amount (float | Unset): The amount of budget change.
        create_date (datetime.datetime | Unset): The date this epsbudgetchangelog was created.
        create_user (str | Unset): The name of the user that created this epsbudgetchangelog.
        date (datetime.datetime | Unset): The date of this budget change entry.
        eps_id (str | Unset): The short code assigned to the associated EPS.
        eps_name (str | Unset): The name of the EPS element associated with this budget change log.
        last_update_date (datetime.datetime | Unset): The date this epsbudgetchangelog was last updated.
        last_update_user (str | Unset): The name of the user that last updated this epsbudgetchangelog.
        object_id (int | Unset): The unique ID generated by the system.
        reason (str | Unset): The description of the reason for the budget change request.
        responsible (str | Unset): The person responsible for the change.
        status (str | Unset): The status of this budget change request.
    """

    change_number: str
    eps_object_id: int
    amount: float | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    date: datetime.datetime | Unset = UNSET
    eps_id: str | Unset = UNSET
    eps_name: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    reason: str | Unset = UNSET
    responsible: str | Unset = UNSET
    status: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        change_number = self.change_number

        eps_object_id = self.eps_object_id

        amount = self.amount

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        date: str | Unset = UNSET
        if not isinstance(self.date, Unset):
            date = self.date.isoformat()

        eps_id = self.eps_id

        eps_name = self.eps_name

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        reason = self.reason

        responsible = self.responsible

        status = self.status

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ChangeNumber": change_number,
                "EPSObjectId": eps_object_id,
            }
        )
        if amount is not UNSET:
            field_dict["Amount"] = amount
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if date is not UNSET:
            field_dict["Date"] = date
        if eps_id is not UNSET:
            field_dict["EPSId"] = eps_id
        if eps_name is not UNSET:
            field_dict["EPSName"] = eps_name
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if reason is not UNSET:
            field_dict["Reason"] = reason
        if responsible is not UNSET:
            field_dict["Responsible"] = responsible
        if status is not UNSET:
            field_dict["Status"] = status

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        change_number = d.pop("ChangeNumber")

        eps_object_id = d.pop("EPSObjectId")

        amount = d.pop("Amount", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        _date = d.pop("Date", UNSET)
        date: datetime.datetime | Unset
        if isinstance(_date, Unset):
            date = UNSET
        else:
            date = isoparse(_date)

        eps_id = d.pop("EPSId", UNSET)

        eps_name = d.pop("EPSName", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        reason = d.pop("Reason", UNSET)

        responsible = d.pop("Responsible", UNSET)

        status = d.pop("Status", UNSET)

        eps_budget_change_log = cls(
            change_number=change_number,
            eps_object_id=eps_object_id,
            amount=amount,
            create_date=create_date,
            create_user=create_user,
            date=date,
            eps_id=eps_id,
            eps_name=eps_name,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            reason=reason,
            responsible=responsible,
            status=status,
        )

        eps_budget_change_log.additional_properties = d
        return eps_budget_change_log

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
