from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="EPSFunding")


@_attrs_define
class EPSFunding:
    """EPSFunding Entity

    Attributes:
        eps_object_id (int): The unique ID of the associated EPS for this EPS funding.
        funding_source_object_id (int): The unique ID of the associated funding source for this EPS funding.
        amount (float | Unset): The amount of a funding source that is allocated to the EPS.
        create_date (datetime.datetime | Unset): The date this epsfunding was created.
        create_user (str | Unset): The name of the user that created this epsfunding.
        eps_id (str | Unset): The short code assigned to the associated EPS.
        eps_name (str | Unset): The name of the EPS element associated with this funding.
        fund_share (float | Unset): The percentage of the total fund that is allocated to the EPS.
        last_update_date (datetime.datetime | Unset): The date this epsfunding was last updated.
        last_update_user (str | Unset): The name of the user that last updated this epsfunding.
        object_id (int | Unset): The unique ID generated by the system.
    """

    eps_object_id: int
    funding_source_object_id: int
    amount: float | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    eps_id: str | Unset = UNSET
    eps_name: str | Unset = UNSET
    fund_share: float | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        eps_object_id = self.eps_object_id

        funding_source_object_id = self.funding_source_object_id

        amount = self.amount

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        eps_id = self.eps_id

        eps_name = self.eps_name

        fund_share = self.fund_share

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "EPSObjectId": eps_object_id,
                "FundingSourceObjectId": funding_source_object_id,
            }
        )
        if amount is not UNSET:
            field_dict["Amount"] = amount
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if eps_id is not UNSET:
            field_dict["EPSId"] = eps_id
        if eps_name is not UNSET:
            field_dict["EPSName"] = eps_name
        if fund_share is not UNSET:
            field_dict["FundShare"] = fund_share
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        eps_object_id = d.pop("EPSObjectId")

        funding_source_object_id = d.pop("FundingSourceObjectId")

        amount = d.pop("Amount", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        eps_id = d.pop("EPSId", UNSET)

        eps_name = d.pop("EPSName", UNSET)

        fund_share = d.pop("FundShare", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        eps_funding = cls(
            eps_object_id=eps_object_id,
            funding_source_object_id=funding_source_object_id,
            amount=amount,
            create_date=create_date,
            create_user=create_user,
            eps_id=eps_id,
            eps_name=eps_name,
            fund_share=fund_share,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
        )

        eps_funding.additional_properties = d
        return eps_funding

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
