from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="EPSNote")


@_attrs_define
class EPSNote:
    """EPSNote Entity

    Attributes:
        eps_object_id (int): The unique ID of the associated EPS.
        notebook_topic_object_id (int): The unique ID of the associated notebook topic.
        create_date (datetime.datetime | Unset): The date this EPS Note was created.
        create_user (str | Unset): The name of the user that created this EPS Note.
        eps_id (str | Unset): The short code assigned to the associated EPS.
        eps_name (str | Unset): The name of the EPS element associated with this note.
        note (str | Unset): The information that is associated with the notebook topic.
        last_update_date (datetime.datetime | Unset): The date this EPS Note was last updated.
        last_update_user (str | Unset): The name of the user that last updated this EPS Note.
        notebook_topic_name (str | Unset): The name of the associated notebook topic.
        object_id (int | Unset): The unique ID generated by the system.
        raw_text_note (str | Unset): The information that is associated with the notebook topic, without any HTML.
    """

    eps_object_id: int
    notebook_topic_object_id: int
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    eps_id: str | Unset = UNSET
    eps_name: str | Unset = UNSET
    note: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    notebook_topic_name: str | Unset = UNSET
    object_id: int | Unset = UNSET
    raw_text_note: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        eps_object_id = self.eps_object_id

        notebook_topic_object_id = self.notebook_topic_object_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        eps_id = self.eps_id

        eps_name = self.eps_name

        note = self.note

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        notebook_topic_name = self.notebook_topic_name

        object_id = self.object_id

        raw_text_note = self.raw_text_note

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "EPSObjectId": eps_object_id,
                "NotebookTopicObjectId": notebook_topic_object_id,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if eps_id is not UNSET:
            field_dict["EPSId"] = eps_id
        if eps_name is not UNSET:
            field_dict["EPSName"] = eps_name
        if note is not UNSET:
            field_dict["Note"] = note
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if notebook_topic_name is not UNSET:
            field_dict["NotebookTopicName"] = notebook_topic_name
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if raw_text_note is not UNSET:
            field_dict["RawTextNote"] = raw_text_note

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        eps_object_id = d.pop("EPSObjectId")

        notebook_topic_object_id = d.pop("NotebookTopicObjectId")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        eps_id = d.pop("EPSId", UNSET)

        eps_name = d.pop("EPSName", UNSET)

        note = d.pop("Note", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        notebook_topic_name = d.pop("NotebookTopicName", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        raw_text_note = d.pop("RawTextNote", UNSET)

        eps_note = cls(
            eps_object_id=eps_object_id,
            notebook_topic_object_id=notebook_topic_object_id,
            create_date=create_date,
            create_user=create_user,
            eps_id=eps_id,
            eps_name=eps_name,
            note=note,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            notebook_topic_name=notebook_topic_name,
            object_id=object_id,
            raw_text_note=raw_text_note,
        )

        eps_note.additional_properties = d
        return eps_note

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
