from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="FinancialPeriod")


@_attrs_define
class FinancialPeriod:
    """FinancialPeriod Entity

    Attributes:
        end_date (datetime.datetime): The end date of the period.
        name (str): The name of the financial period.
        start_date (datetime.datetime): The start date of the period.
        create_date (datetime.datetime | Unset): The date this financial period was created.
        create_user (str | Unset): The name of the user that created this financial period.
        financial_period_template_id (int | Unset):
        last_update_date (datetime.datetime | Unset): The date this financial period was last updated.
        last_update_user (str | Unset): The name of the user that last updated this financial period.
        object_id (int | Unset): The unique ID generated by the system.
    """

    end_date: datetime.datetime
    name: str
    start_date: datetime.datetime
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    financial_period_template_id: int | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        end_date = self.end_date.isoformat()

        name = self.name

        start_date = self.start_date.isoformat()

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        financial_period_template_id = self.financial_period_template_id

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "EndDate": end_date,
                "Name": name,
                "StartDate": start_date,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if financial_period_template_id is not UNSET:
            field_dict["FinancialPeriodTemplateId"] = financial_period_template_id
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        end_date = isoparse(d.pop("EndDate"))

        name = d.pop("Name")

        start_date = isoparse(d.pop("StartDate"))

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        financial_period_template_id = d.pop("FinancialPeriodTemplateId", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        financial_period = cls(
            end_date=end_date,
            name=name,
            start_date=start_date,
            create_date=create_date,
            create_user=create_user,
            financial_period_template_id=financial_period_template_id,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
        )

        financial_period.additional_properties = d
        return financial_period

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
