from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="JobService")


@_attrs_define
class JobService:
    """JobService Entity

    Attributes:
        add_project_info (str | Unset):
        copy_options (str | Unset):
        export_file_path (str | Unset): Exported file path.
        export_plf_file_names (str | Unset): File names of exported PLF files.
        export_xml_byte (str | Unset): Export byte array.
        file_name (str | Unset): Exported File Name.
        import_xml_byte (str | Unset): Import byte array.
        job_data (str | Unset): The job data for the job service.
        job_data_x (str | Unset): The job data X for the job service.
        job_recurring_type (str | Unset): JobRecurringType for job service
        job_status (str | Unset): The status of the job.
        job_type (str | Unset): The type of the job service.
        job_type_key (str | Unset): Project ObjectId to be used by job.
        last_run_date (datetime.datetime | Unset): LastRunDate for job service.
        name (str | Unset): The name of the job service.
        object_id (int | Unset): The unique ID generated by the system.
        plf_dir_name (str | Unset): PlfDirName
        project_info (str | Unset):
        target_wbs_id (int | Unset):
        user_id (int | Unset): The ID of the user that ran a job service.
    """

    add_project_info: str | Unset = UNSET
    copy_options: str | Unset = UNSET
    export_file_path: str | Unset = UNSET
    export_plf_file_names: str | Unset = UNSET
    export_xml_byte: str | Unset = UNSET
    file_name: str | Unset = UNSET
    import_xml_byte: str | Unset = UNSET
    job_data: str | Unset = UNSET
    job_data_x: str | Unset = UNSET
    job_recurring_type: str | Unset = UNSET
    job_status: str | Unset = UNSET
    job_type: str | Unset = UNSET
    job_type_key: str | Unset = UNSET
    last_run_date: datetime.datetime | Unset = UNSET
    name: str | Unset = UNSET
    object_id: int | Unset = UNSET
    plf_dir_name: str | Unset = UNSET
    project_info: str | Unset = UNSET
    target_wbs_id: int | Unset = UNSET
    user_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        add_project_info = self.add_project_info

        copy_options = self.copy_options

        export_file_path = self.export_file_path

        export_plf_file_names = self.export_plf_file_names

        export_xml_byte = self.export_xml_byte

        file_name = self.file_name

        import_xml_byte = self.import_xml_byte

        job_data = self.job_data

        job_data_x = self.job_data_x

        job_recurring_type = self.job_recurring_type

        job_status = self.job_status

        job_type = self.job_type

        job_type_key = self.job_type_key

        last_run_date: str | Unset = UNSET
        if not isinstance(self.last_run_date, Unset):
            last_run_date = self.last_run_date.isoformat()

        name = self.name

        object_id = self.object_id

        plf_dir_name = self.plf_dir_name

        project_info = self.project_info

        target_wbs_id = self.target_wbs_id

        user_id = self.user_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if add_project_info is not UNSET:
            field_dict["AddProjectInfo"] = add_project_info
        if copy_options is not UNSET:
            field_dict["CopyOptions"] = copy_options
        if export_file_path is not UNSET:
            field_dict["ExportFilePath"] = export_file_path
        if export_plf_file_names is not UNSET:
            field_dict["ExportPlfFileNames"] = export_plf_file_names
        if export_xml_byte is not UNSET:
            field_dict["ExportXMLByte"] = export_xml_byte
        if file_name is not UNSET:
            field_dict["FileName"] = file_name
        if import_xml_byte is not UNSET:
            field_dict["ImportXMLByte"] = import_xml_byte
        if job_data is not UNSET:
            field_dict["JobData"] = job_data
        if job_data_x is not UNSET:
            field_dict["JobDataX"] = job_data_x
        if job_recurring_type is not UNSET:
            field_dict["JobRecurringType"] = job_recurring_type
        if job_status is not UNSET:
            field_dict["JobStatus"] = job_status
        if job_type is not UNSET:
            field_dict["JobType"] = job_type
        if job_type_key is not UNSET:
            field_dict["JobTypeKey"] = job_type_key
        if last_run_date is not UNSET:
            field_dict["LastRunDate"] = last_run_date
        if name is not UNSET:
            field_dict["Name"] = name
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if plf_dir_name is not UNSET:
            field_dict["PlfDirName"] = plf_dir_name
        if project_info is not UNSET:
            field_dict["ProjectInfo"] = project_info
        if target_wbs_id is not UNSET:
            field_dict["TargetWbsId"] = target_wbs_id
        if user_id is not UNSET:
            field_dict["UserId"] = user_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        add_project_info = d.pop("AddProjectInfo", UNSET)

        copy_options = d.pop("CopyOptions", UNSET)

        export_file_path = d.pop("ExportFilePath", UNSET)

        export_plf_file_names = d.pop("ExportPlfFileNames", UNSET)

        export_xml_byte = d.pop("ExportXMLByte", UNSET)

        file_name = d.pop("FileName", UNSET)

        import_xml_byte = d.pop("ImportXMLByte", UNSET)

        job_data = d.pop("JobData", UNSET)

        job_data_x = d.pop("JobDataX", UNSET)

        job_recurring_type = d.pop("JobRecurringType", UNSET)

        job_status = d.pop("JobStatus", UNSET)

        job_type = d.pop("JobType", UNSET)

        job_type_key = d.pop("JobTypeKey", UNSET)

        _last_run_date = d.pop("LastRunDate", UNSET)
        last_run_date: datetime.datetime | Unset
        if isinstance(_last_run_date, Unset):
            last_run_date = UNSET
        else:
            last_run_date = isoparse(_last_run_date)

        name = d.pop("Name", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        plf_dir_name = d.pop("PlfDirName", UNSET)

        project_info = d.pop("ProjectInfo", UNSET)

        target_wbs_id = d.pop("TargetWbsId", UNSET)

        user_id = d.pop("UserId", UNSET)

        job_service = cls(
            add_project_info=add_project_info,
            copy_options=copy_options,
            export_file_path=export_file_path,
            export_plf_file_names=export_plf_file_names,
            export_xml_byte=export_xml_byte,
            file_name=file_name,
            import_xml_byte=import_xml_byte,
            job_data=job_data,
            job_data_x=job_data_x,
            job_recurring_type=job_recurring_type,
            job_status=job_status,
            job_type=job_type,
            job_type_key=job_type_key,
            last_run_date=last_run_date,
            name=name,
            object_id=object_id,
            plf_dir_name=plf_dir_name,
            project_info=project_info,
            target_wbs_id=target_wbs_id,
            user_id=user_id,
        )

        job_service.additional_properties = d
        return job_service

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
