from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="MSPTemplate")


@_attrs_define
class MSPTemplate:
    """MSPTemplate Entity

    Attributes:
        msp_template_type (str | Unset): The content of the template.
        name (str | Unset): The name of the template.
        object_id (int | Unset): The unique ID generated by the system.
        view_data (str | Unset): The content of the template.
    """

    msp_template_type: str | Unset = UNSET
    name: str | Unset = UNSET
    object_id: int | Unset = UNSET
    view_data: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        msp_template_type = self.msp_template_type

        name = self.name

        object_id = self.object_id

        view_data = self.view_data

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if msp_template_type is not UNSET:
            field_dict["MSPTemplateType"] = msp_template_type
        if name is not UNSET:
            field_dict["Name"] = name
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if view_data is not UNSET:
            field_dict["ViewData"] = view_data

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        msp_template_type = d.pop("MSPTemplateType", UNSET)

        name = d.pop("Name", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        view_data = d.pop("ViewData", UNSET)

        msp_template = cls(
            msp_template_type=msp_template_type,
            name=name,
            object_id=object_id,
            view_data=view_data,
        )

        msp_template.additional_properties = d
        return msp_template

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
