from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="NotebookTopic")


@_attrs_define
class NotebookTopic:
    """NotebookTopic Entity

    Attributes:
        create_date (datetime.datetime | Unset): The date this notebook topic was created.
        create_user (str | Unset): The name of the user that created this notebook topic.
        name (str | Unset): The name of the notebook topic.
        available_for_activity (bool | Unset): The flag indicating that the topic will be available to assign to
            activities.
        last_update_date (datetime.datetime | Unset): The date this notebook topic was last updated.
        last_update_user (str | Unset): The name of the user that last updated this notebook topic.
        object_id (int | Unset): The unique ID generated by the system.
        sequence_number (int | Unset): The sequence number for sorting.
        available_for_eps (bool | Unset): The flag indicating that the topic will be available to assign to EPS.
        available_for_project (bool | Unset): The flag indicating that the topic will be available to assign to
            projects.
        available_for_wbs (bool | Unset): The flag indicating that the topic will be available to assign to WBS.
    """

    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    name: str | Unset = UNSET
    available_for_activity: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    sequence_number: int | Unset = UNSET
    available_for_eps: bool | Unset = UNSET
    available_for_project: bool | Unset = UNSET
    available_for_wbs: bool | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        name = self.name

        available_for_activity = self.available_for_activity

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        sequence_number = self.sequence_number

        available_for_eps = self.available_for_eps

        available_for_project = self.available_for_project

        available_for_wbs = self.available_for_wbs

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if name is not UNSET:
            field_dict["Name"] = name
        if available_for_activity is not UNSET:
            field_dict["AvailableForActivity"] = available_for_activity
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number
        if available_for_eps is not UNSET:
            field_dict["AvailableForEPS"] = available_for_eps
        if available_for_project is not UNSET:
            field_dict["AvailableForProject"] = available_for_project
        if available_for_wbs is not UNSET:
            field_dict["AvailableForWBS"] = available_for_wbs

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        name = d.pop("Name", UNSET)

        available_for_activity = d.pop("AvailableForActivity", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        available_for_eps = d.pop("AvailableForEPS", UNSET)

        available_for_project = d.pop("AvailableForProject", UNSET)

        available_for_wbs = d.pop("AvailableForWBS", UNSET)

        notebook_topic = cls(
            create_date=create_date,
            create_user=create_user,
            name=name,
            available_for_activity=available_for_activity,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            sequence_number=sequence_number,
            available_for_eps=available_for_eps,
            available_for_project=available_for_project,
            available_for_wbs=available_for_wbs,
        )

        notebook_topic.additional_properties = d
        return notebook_topic

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
