from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.privilege import Privilege


T = TypeVar("T", bound="ProjectProfile")


@_attrs_define
class ProjectProfile:
    """ProjectProfile Entity

    Attributes:
        name (str): The unique name of this project profile
        create_date (datetime.datetime | Unset): The date this project profile was created.
        create_user (str | Unset): The name of the user that created this project profile.
        is_default (bool | Unset): The flag that indicates this security profile is the default profile assigned to
            UserOBS objects. When a ProjectProfile object is deleted from the database, all UserOBS objects assigned to that
            profile are reassigned to the default profile. You cannot not delete the default profile.
        is_super_user (bool | Unset): The flag that indicates this is the project superuser profile, which gives a user
            read/write privileges for all project and OBS specific information and features
        last_update_date (datetime.datetime | Unset): The date this project profile was last updated.
        last_update_user (str | Unset): The name of the user that last updated this project profile.
        object_id (int | Unset): The unique ID generated by the system.
        privilege (list[Privilege] | Unset): Privilege
    """

    name: str
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    is_default: bool | Unset = UNSET
    is_super_user: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    privilege: list[Privilege] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        is_default = self.is_default

        is_super_user = self.is_super_user

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        privilege: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.privilege, Unset):
            privilege = []
            for privilege_item_data in self.privilege:
                privilege_item = privilege_item_data.to_dict()
                privilege.append(privilege_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Name": name,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if is_default is not UNSET:
            field_dict["IsDefault"] = is_default
        if is_super_user is not UNSET:
            field_dict["IsSuperUser"] = is_super_user
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if privilege is not UNSET:
            field_dict["Privilege"] = privilege

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.privilege import Privilege

        d = dict(src_dict)
        name = d.pop("Name")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        is_default = d.pop("IsDefault", UNSET)

        is_super_user = d.pop("IsSuperUser", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        _privilege = d.pop("Privilege", UNSET)
        privilege: list[Privilege] | Unset = UNSET
        if _privilege is not UNSET:
            privilege = []
            for privilege_item_data in _privilege:
                privilege_item = Privilege.from_dict(privilege_item_data)

                privilege.append(privilege_item)

        project_profile = cls(
            name=name,
            create_date=create_date,
            create_user=create_user,
            is_default=is_default,
            is_super_user=is_super_user,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            privilege=privilege,
        )

        project_profile.additional_properties = d
        return project_profile

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
