from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.member_project import MemberProject


T = TypeVar("T", bound="ProjectPortfolio")


@_attrs_define
class ProjectPortfolio:
    """ProjectPortfolio Entity

    Attributes:
        name (str): The name of the project portfolio.
        create_date (datetime.datetime | Unset): The date this project portfolio was created.
        create_user (str | Unset): The name of the user that created this project portfolio.
        description (str | Unset): The description of the project portfolio.
        include_closed_projects (bool | Unset): The flag that indicates whether closed projects are included in the
            portfolio.
        include_what_if_projects (bool | Unset): The flag that indicates whether what-if projects are included in the
            portfolio.
        last_update_date (datetime.datetime | Unset): The date this project portfolio was last updated.
        last_update_user (str | Unset): The name of the user that last updated this project portfolio.
        object_id (int | Unset): The unique ID generated by the system.
        portfolio_user_id_array (str | Unset):
        portfolio_user_name_array (str | Unset):
        type_ (str | Unset): The type of the project portfolio: "Manual", "Auto-Maintained", or "Filtered".
        user_name (str | Unset): The user's login name.
        user_object_id (int | Unset): The unique ID of a specific user who has access to the selected project portfolio.
        member_project (list[MemberProject] | Unset): MemberProject
    """

    name: str
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    description: str | Unset = UNSET
    include_closed_projects: bool | Unset = UNSET
    include_what_if_projects: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    portfolio_user_id_array: str | Unset = UNSET
    portfolio_user_name_array: str | Unset = UNSET
    type_: str | Unset = UNSET
    user_name: str | Unset = UNSET
    user_object_id: int | Unset = UNSET
    member_project: list[MemberProject] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        description = self.description

        include_closed_projects = self.include_closed_projects

        include_what_if_projects = self.include_what_if_projects

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        portfolio_user_id_array = self.portfolio_user_id_array

        portfolio_user_name_array = self.portfolio_user_name_array

        type_ = self.type_

        user_name = self.user_name

        user_object_id = self.user_object_id

        member_project: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.member_project, Unset):
            member_project = []
            for member_project_item_data in self.member_project:
                member_project_item = member_project_item_data.to_dict()
                member_project.append(member_project_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Name": name,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if description is not UNSET:
            field_dict["Description"] = description
        if include_closed_projects is not UNSET:
            field_dict["IncludeClosedProjects"] = include_closed_projects
        if include_what_if_projects is not UNSET:
            field_dict["IncludeWhatIfProjects"] = include_what_if_projects
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if portfolio_user_id_array is not UNSET:
            field_dict["PortfolioUserIdArray"] = portfolio_user_id_array
        if portfolio_user_name_array is not UNSET:
            field_dict["PortfolioUserNameArray"] = portfolio_user_name_array
        if type_ is not UNSET:
            field_dict["Type"] = type_
        if user_name is not UNSET:
            field_dict["UserName"] = user_name
        if user_object_id is not UNSET:
            field_dict["UserObjectId"] = user_object_id
        if member_project is not UNSET:
            field_dict["MemberProject"] = member_project

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.member_project import MemberProject

        d = dict(src_dict)
        name = d.pop("Name")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        description = d.pop("Description", UNSET)

        include_closed_projects = d.pop("IncludeClosedProjects", UNSET)

        include_what_if_projects = d.pop("IncludeWhatIfProjects", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        portfolio_user_id_array = d.pop("PortfolioUserIdArray", UNSET)

        portfolio_user_name_array = d.pop("PortfolioUserNameArray", UNSET)

        type_ = d.pop("Type", UNSET)

        user_name = d.pop("UserName", UNSET)

        user_object_id = d.pop("UserObjectId", UNSET)

        _member_project = d.pop("MemberProject", UNSET)
        member_project: list[MemberProject] | Unset = UNSET
        if _member_project is not UNSET:
            member_project = []
            for member_project_item_data in _member_project:
                member_project_item = MemberProject.from_dict(member_project_item_data)

                member_project.append(member_project_item)

        project_portfolio = cls(
            name=name,
            create_date=create_date,
            create_user=create_user,
            description=description,
            include_closed_projects=include_closed_projects,
            include_what_if_projects=include_what_if_projects,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            portfolio_user_id_array=portfolio_user_id_array,
            portfolio_user_name_array=portfolio_user_name_array,
            type_=type_,
            user_name=user_name,
            user_object_id=user_object_id,
            member_project=member_project,
        )

        project_portfolio.additional_properties = d
        return project_portfolio

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
