from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ProjectSpendingPlan")


@_attrs_define
class ProjectSpendingPlan:
    """ProjectSpendingPlan Entity

    Attributes:
        date (datetime.datetime): The start of a spending/benefit plan time period for the project.
        project_object_id (int): The unique ID of the associated project for this project spending plan.
        wbs_object_id (int): The unique ID of the associated WBS for this project spending plan.
        benefit_plan (float | Unset): The editable monthly profit portion for each month for the project.
        create_date (datetime.datetime | Unset): The date this spending plan was created.
        create_user (str | Unset): The name of the user that created this spending plan.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this spending plan was last updated.
        last_update_user (str | Unset): The name of the user that last updated this spending plan.
        object_id (int | Unset): The unique ID generated by the system.
        project_id (str | Unset): The Project short code that uniquely identifies the project.
        spending_plan (float | Unset): The editable total monthly expenditure for the project.
        wbs_code (str | Unset): The short code assigned to each WBS element for identification. Each WBS element is
            uniquely identified by concatenating its own code together with its parents' codes.
        wbs_name (str | Unset): The name of the WBS element.
    """

    date: datetime.datetime
    project_object_id: int
    wbs_object_id: int
    benefit_plan: float | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    project_id: str | Unset = UNSET
    spending_plan: float | Unset = UNSET
    wbs_code: str | Unset = UNSET
    wbs_name: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        date = self.date.isoformat()

        project_object_id = self.project_object_id

        wbs_object_id = self.wbs_object_id

        benefit_plan = self.benefit_plan

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        is_baseline = self.is_baseline

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        project_id = self.project_id

        spending_plan = self.spending_plan

        wbs_code = self.wbs_code

        wbs_name = self.wbs_name

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Date": date,
                "ProjectObjectId": project_object_id,
                "WBSObjectId": wbs_object_id,
            }
        )
        if benefit_plan is not UNSET:
            field_dict["BenefitPlan"] = benefit_plan
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if spending_plan is not UNSET:
            field_dict["SpendingPlan"] = spending_plan
        if wbs_code is not UNSET:
            field_dict["WBSCode"] = wbs_code
        if wbs_name is not UNSET:
            field_dict["WBSName"] = wbs_name

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        date = isoparse(d.pop("Date"))

        project_object_id = d.pop("ProjectObjectId")

        wbs_object_id = d.pop("WBSObjectId")

        benefit_plan = d.pop("BenefitPlan", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        spending_plan = d.pop("SpendingPlan", UNSET)

        wbs_code = d.pop("WBSCode", UNSET)

        wbs_name = d.pop("WBSName", UNSET)

        project_spending_plan = cls(
            date=date,
            project_object_id=project_object_id,
            wbs_object_id=wbs_object_id,
            benefit_plan=benefit_plan,
            create_date=create_date,
            create_user=create_user,
            is_baseline=is_baseline,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            project_id=project_id,
            spending_plan=spending_plan,
            wbs_code=wbs_code,
            wbs_name=wbs_name,
        )

        project_spending_plan.additional_properties = d
        return project_spending_plan

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
