from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ProjectThreshold")


@_attrs_define
class ProjectThreshold:
    """ProjectThreshold Entity

    Attributes:
        obs_object_id (int): The unique ID of the associated OBS for this project threshold.
        project_object_id (int): The unique ID of the associated project for this project threshold.
        threshold_parameter_object_id (int): The unique ID of the associated threshold parameter for this project
            threshold.
        wbs_object_id (int): The unique ID of the associated WBS for this project threshold.
        create_date (datetime.datetime | Unset): The date this project threshold was created.
        create_user (str | Unset): The name of the user that created this project threshold.
        detail_to_monitor (str | Unset): The level of detail to monitor, either Activity or WBS. The project threshold
            is calculated at the activity level or at the WBS level, whichever is selected.
        from_date (datetime.datetime | Unset): The starting custom date of the time window that is monitored against a
            project threshold. Any activities or WBS elements with start/finish dates which intersect this time window are
            monitored.
        from_date_expression (str | Unset): The expression for the starting date of the time window that is monitored
            against a project threshold. Valid values are PS (the project StartDate), PF (the project FinishDate), DD (the
            project Data Date), CD (Current Date), CW (Current Week), or CM (Current Month). All values can be combined with
            arithmetic operators + or - and a numerical calendar value. For example, PS+5D, DD-1M. The calendar abbreviation
            specified in the expression (H, D, W, M, Y) must match the value of the corresponding GlobalPreferences field:
            HourChar, DayChar, WeekChar, MonthChar, or YearChar. You could specify a custom date by setting a date value for
            the FromDate field. If you set values for both the FromDate and FromDateExpression fields, the
            FromDateExpression will be ignored.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        issue_priority (str | Unset): The priority of any issues generated from the project threshold.
        last_update_date (datetime.datetime | Unset): The date this project threshold was last updated.
        last_update_user (str | Unset): The name of the user that last updated this project threshold.
        lower_threshold (float | Unset): The lower value of a project threshold that will trigger an issue. An issue is
            identified by the project threshold monitor when the actual/observed value of the project threshold parameter is
            found to be less than or equal to the lower project threshold value. If the lower project threshold value is
            null, it is ignored. Example: The Total Float lower project threshold is set to one day. Whenever the observed
            total float is less than or equal to one day, a project issue is raised
        object_id (int | Unset): The unique ID generated by the system.
        project_id (str | Unset): The Project short code that uniquely identifies the project.
        status (str | Unset): The current status of the project threshold.
        to_date (datetime.datetime | Unset): The ending custom date of the time window that is monitored against a
            project threshold. Any activities or WBS elements with start/finish dates which intersect this time window are
            monitored.
        to_date_expression (str | Unset): The expression for the ending date of the time window that is monitored
            against a project threshold. Valid values are PS (the project StartDate), PF (the project FinishDate), DD (the
            project Data Date), CD (Current Date), CW (Current Week), or CM (Current Month). All values can be combined with
            arithmetic operators + or - and a numerical calendar value. For example, PS+5d, DD-1M. The calendar abbreviation
            specified in the expression (H, D, W, M, Y) must match the value of the corresponding GlobalPreferences field:
            HourChar, DayChar, WeekChar, MonthChar, or YearChar. You could specify a custom date by setting a date value for
            the FromDate field. If you set values for both the ToDate and ToDateExpression fields, the ToDateExpression will
            be ignored.
        upper_threshold (float | Unset): The upper value of a project threshold parameter which will trigger an issue.
            An issue is identified by the project threshold monitor when the actual/observed value of the project threshold
            parameter is found to be greater than or equal to the upper project threshold value. If the upper project
            threshold value is null, it is ignored. Example: The Cost % of Planned upper project threshold is set to 120%.
            Whenever the actual cost is greater than or equal to 120% of planned, an issue is raised.
        wbs_code (str | Unset): The short code assigned to each WBS element for identification. Each WBS element is
            uniquely identified by concatenating its own code together with its parents' codes.
        wbs_name (str | Unset): The name of the WBS element.
    """

    obs_object_id: int
    project_object_id: int
    threshold_parameter_object_id: int
    wbs_object_id: int
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    detail_to_monitor: str | Unset = UNSET
    from_date: datetime.datetime | Unset = UNSET
    from_date_expression: str | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    issue_priority: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    lower_threshold: float | Unset = UNSET
    object_id: int | Unset = UNSET
    project_id: str | Unset = UNSET
    status: str | Unset = UNSET
    to_date: datetime.datetime | Unset = UNSET
    to_date_expression: str | Unset = UNSET
    upper_threshold: float | Unset = UNSET
    wbs_code: str | Unset = UNSET
    wbs_name: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        obs_object_id = self.obs_object_id

        project_object_id = self.project_object_id

        threshold_parameter_object_id = self.threshold_parameter_object_id

        wbs_object_id = self.wbs_object_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        detail_to_monitor = self.detail_to_monitor

        from_date: str | Unset = UNSET
        if not isinstance(self.from_date, Unset):
            from_date = self.from_date.isoformat()

        from_date_expression = self.from_date_expression

        is_baseline = self.is_baseline

        is_template = self.is_template

        issue_priority = self.issue_priority

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        lower_threshold = self.lower_threshold

        object_id = self.object_id

        project_id = self.project_id

        status = self.status

        to_date: str | Unset = UNSET
        if not isinstance(self.to_date, Unset):
            to_date = self.to_date.isoformat()

        to_date_expression = self.to_date_expression

        upper_threshold = self.upper_threshold

        wbs_code = self.wbs_code

        wbs_name = self.wbs_name

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "OBSObjectId": obs_object_id,
                "ProjectObjectId": project_object_id,
                "ThresholdParameterObjectId": threshold_parameter_object_id,
                "WBSObjectId": wbs_object_id,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if detail_to_monitor is not UNSET:
            field_dict["DetailToMonitor"] = detail_to_monitor
        if from_date is not UNSET:
            field_dict["FromDate"] = from_date
        if from_date_expression is not UNSET:
            field_dict["FromDateExpression"] = from_date_expression
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if issue_priority is not UNSET:
            field_dict["IssuePriority"] = issue_priority
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if lower_threshold is not UNSET:
            field_dict["LowerThreshold"] = lower_threshold
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if status is not UNSET:
            field_dict["Status"] = status
        if to_date is not UNSET:
            field_dict["ToDate"] = to_date
        if to_date_expression is not UNSET:
            field_dict["ToDateExpression"] = to_date_expression
        if upper_threshold is not UNSET:
            field_dict["UpperThreshold"] = upper_threshold
        if wbs_code is not UNSET:
            field_dict["WBSCode"] = wbs_code
        if wbs_name is not UNSET:
            field_dict["WBSName"] = wbs_name

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        obs_object_id = d.pop("OBSObjectId")

        project_object_id = d.pop("ProjectObjectId")

        threshold_parameter_object_id = d.pop("ThresholdParameterObjectId")

        wbs_object_id = d.pop("WBSObjectId")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        detail_to_monitor = d.pop("DetailToMonitor", UNSET)

        _from_date = d.pop("FromDate", UNSET)
        from_date: datetime.datetime | Unset
        if isinstance(_from_date, Unset):
            from_date = UNSET
        else:
            from_date = isoparse(_from_date)

        from_date_expression = d.pop("FromDateExpression", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        issue_priority = d.pop("IssuePriority", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        lower_threshold = d.pop("LowerThreshold", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        status = d.pop("Status", UNSET)

        _to_date = d.pop("ToDate", UNSET)
        to_date: datetime.datetime | Unset
        if isinstance(_to_date, Unset):
            to_date = UNSET
        else:
            to_date = isoparse(_to_date)

        to_date_expression = d.pop("ToDateExpression", UNSET)

        upper_threshold = d.pop("UpperThreshold", UNSET)

        wbs_code = d.pop("WBSCode", UNSET)

        wbs_name = d.pop("WBSName", UNSET)

        project_threshold = cls(
            obs_object_id=obs_object_id,
            project_object_id=project_object_id,
            threshold_parameter_object_id=threshold_parameter_object_id,
            wbs_object_id=wbs_object_id,
            create_date=create_date,
            create_user=create_user,
            detail_to_monitor=detail_to_monitor,
            from_date=from_date,
            from_date_expression=from_date_expression,
            is_baseline=is_baseline,
            is_template=is_template,
            issue_priority=issue_priority,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            lower_threshold=lower_threshold,
            object_id=object_id,
            project_id=project_id,
            status=status,
            to_date=to_date,
            to_date_expression=to_date_expression,
            upper_threshold=upper_threshold,
            wbs_code=wbs_code,
            wbs_name=wbs_name,
        )

        project_threshold.additional_properties = d
        return project_threshold

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
