from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ProjectBudgetChangeLog")


@_attrs_define
class ProjectBudgetChangeLog:
    """ProjectBudgetChangeLog Entity

    Attributes:
        change_number (str): The change number that is automatically incremented according to when changes are added.
            This can be changed to any number.
        project_object_id (int): The unique ID of the associated project.
        wbs_object_id (int): The unique ID of the WBS element to which the budget change log applies.
        amount (float | Unset): The amount of budget change.
        create_user (str | Unset): The name of the user that created this log of budget changes.
        date (datetime.datetime | Unset): The date of this budget change entry.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this log of budget changes was last updated.
        last_update_user (str | Unset): The name of the user that last updated this log of budget changes.
        object_id (int | Unset): The unique ID generated by the system.
        project_id (str | Unset): The short code that uniquely identifies the project.
        reason (str | Unset): The description of the reason for the budget change request.
        responsible (str | Unset): The person responsible for the change.
        status (str | Unset): The status of this budget change request. Possible values are 'Pending', 'Approved', and
            'Not Approved'.
        wbs_code (str | Unset): The short code assigned to each WBS element for identification. Each WBS element is
            uniquely identified by concatenating its own code together with its parents' codes.
        wbs_name (str | Unset): The name of the WBS element.
    """

    change_number: str
    project_object_id: int
    wbs_object_id: int
    amount: float | Unset = UNSET
    create_user: str | Unset = UNSET
    date: datetime.datetime | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    project_id: str | Unset = UNSET
    reason: str | Unset = UNSET
    responsible: str | Unset = UNSET
    status: str | Unset = UNSET
    wbs_code: str | Unset = UNSET
    wbs_name: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        change_number = self.change_number

        project_object_id = self.project_object_id

        wbs_object_id = self.wbs_object_id

        amount = self.amount

        create_user = self.create_user

        date: str | Unset = UNSET
        if not isinstance(self.date, Unset):
            date = self.date.isoformat()

        is_baseline = self.is_baseline

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        project_id = self.project_id

        reason = self.reason

        responsible = self.responsible

        status = self.status

        wbs_code = self.wbs_code

        wbs_name = self.wbs_name

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ChangeNumber": change_number,
                "ProjectObjectId": project_object_id,
                "WBSObjectId": wbs_object_id,
            }
        )
        if amount is not UNSET:
            field_dict["Amount"] = amount
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if date is not UNSET:
            field_dict["Date"] = date
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if reason is not UNSET:
            field_dict["Reason"] = reason
        if responsible is not UNSET:
            field_dict["Responsible"] = responsible
        if status is not UNSET:
            field_dict["Status"] = status
        if wbs_code is not UNSET:
            field_dict["WBSCode"] = wbs_code
        if wbs_name is not UNSET:
            field_dict["WBSName"] = wbs_name

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        change_number = d.pop("ChangeNumber")

        project_object_id = d.pop("ProjectObjectId")

        wbs_object_id = d.pop("WBSObjectId")

        amount = d.pop("Amount", UNSET)

        create_user = d.pop("CreateUser", UNSET)

        _date = d.pop("Date", UNSET)
        date: datetime.datetime | Unset
        if isinstance(_date, Unset):
            date = UNSET
        else:
            date = isoparse(_date)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        reason = d.pop("Reason", UNSET)

        responsible = d.pop("Responsible", UNSET)

        status = d.pop("Status", UNSET)

        wbs_code = d.pop("WBSCode", UNSET)

        wbs_name = d.pop("WBSName", UNSET)

        project_budget_change_log = cls(
            change_number=change_number,
            project_object_id=project_object_id,
            wbs_object_id=wbs_object_id,
            amount=amount,
            create_user=create_user,
            date=date,
            is_baseline=is_baseline,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            project_id=project_id,
            reason=reason,
            responsible=responsible,
            status=status,
            wbs_code=wbs_code,
            wbs_name=wbs_name,
        )

        project_budget_change_log.additional_properties = d
        return project_budget_change_log

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
