from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.resource_request import ResourceRequest


T = TypeVar("T", bound="ProjectResource")


@_attrs_define
class ProjectResource:
    """ProjectResource Entity

    Attributes:
        project_object_id (int): The unique ID of the associated project.
        resource_object_id (int): The unique ID of the associated resource.
        role_object_id (int): The unique ID of the associated role.
        wbs_object_id (int): The unique ID of the associated WBS.
        committed_flag (bool | Unset): The Boolean value that determines whether a resource is committed, and so, the
            resource assignment is stable and unlikely to change. When calculating availability, Primavera considers only
            assignments that are marked as committed.
        create_date (datetime.datetime | Unset): The date this project resource was created.
        create_user (str | Unset): The name of the user that created this project resource.
        finish_date (datetime.datetime | Unset): The finish date of the assignment. By default, it is set to the Planned
            Start date of the project + 1 day, finishing at 5:00pm. For example, if the planned start date is January 1,
            8:00am, the finish date is set to January 2, 5:00pm. If LifeOfProjectFlag is set to true during creation, this
            date is set to the Project Scheduled Finish date. If associated ProjectResourceQuantities exist, this field is
            set to the end of the week of the latest ProjectResourceQuantity.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this project resource was last updated.
        last_update_user (str | Unset): The name of the user that last updated this project resource.
        life_of_project_flag (bool | Unset): The Boolean value that determines whether a resource that is assigned to a
            project at Project or WBS level, has that assignment for the duration of the project.
        object_id (int | Unset): The unique ID generated by the system.
        project_id (str | Unset): The short code that uniquely identifies the associated project.
        project_resource_category_name (str | Unset): The name of the associated project resource category.
        project_resource_category_object_id (int | Unset): The unique ID of the associated project resource category.
        resource_name (str | Unset): The name of the associated resource.
        role_name (str | Unset): The name of the associated role.
        start_date (datetime.datetime | Unset): The start date of the assignment. By default, it is set to the Planned
            Start date of the project. If LifeOfProjectFlag is set to true, this date is set to the Project Planned Start
            date. If associated ProjectResourceQuantities exist, this field is set to the beginning of the week of the
            earliest ProjectResourceQuantity.
        status (str | Unset): The project or WBS status: 'Planned', 'Active', 'Inactive', 'What-If', or 'Requested'.
        wbs_code (str | Unset): The short code assigned to the associated WBS element for identification.
        resource_request (ResourceRequest | Unset):
    """

    project_object_id: int
    resource_object_id: int
    role_object_id: int
    wbs_object_id: int
    committed_flag: bool | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    finish_date: datetime.datetime | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    life_of_project_flag: bool | Unset = UNSET
    object_id: int | Unset = UNSET
    project_id: str | Unset = UNSET
    project_resource_category_name: str | Unset = UNSET
    project_resource_category_object_id: int | Unset = UNSET
    resource_name: str | Unset = UNSET
    role_name: str | Unset = UNSET
    start_date: datetime.datetime | Unset = UNSET
    status: str | Unset = UNSET
    wbs_code: str | Unset = UNSET
    resource_request: ResourceRequest | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        project_object_id = self.project_object_id

        resource_object_id = self.resource_object_id

        role_object_id = self.role_object_id

        wbs_object_id = self.wbs_object_id

        committed_flag = self.committed_flag

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        finish_date: str | Unset = UNSET
        if not isinstance(self.finish_date, Unset):
            finish_date = self.finish_date.isoformat()

        is_baseline = self.is_baseline

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        life_of_project_flag = self.life_of_project_flag

        object_id = self.object_id

        project_id = self.project_id

        project_resource_category_name = self.project_resource_category_name

        project_resource_category_object_id = self.project_resource_category_object_id

        resource_name = self.resource_name

        role_name = self.role_name

        start_date: str | Unset = UNSET
        if not isinstance(self.start_date, Unset):
            start_date = self.start_date.isoformat()

        status = self.status

        wbs_code = self.wbs_code

        resource_request: dict[str, Any] | Unset = UNSET
        if not isinstance(self.resource_request, Unset):
            resource_request = self.resource_request.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ProjectObjectId": project_object_id,
                "ResourceObjectId": resource_object_id,
                "RoleObjectId": role_object_id,
                "WBSObjectId": wbs_object_id,
            }
        )
        if committed_flag is not UNSET:
            field_dict["CommittedFlag"] = committed_flag
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if finish_date is not UNSET:
            field_dict["FinishDate"] = finish_date
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if life_of_project_flag is not UNSET:
            field_dict["LifeOfProjectFlag"] = life_of_project_flag
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if project_resource_category_name is not UNSET:
            field_dict["ProjectResourceCategoryName"] = project_resource_category_name
        if project_resource_category_object_id is not UNSET:
            field_dict["ProjectResourceCategoryObjectId"] = project_resource_category_object_id
        if resource_name is not UNSET:
            field_dict["ResourceName"] = resource_name
        if role_name is not UNSET:
            field_dict["RoleName"] = role_name
        if start_date is not UNSET:
            field_dict["StartDate"] = start_date
        if status is not UNSET:
            field_dict["Status"] = status
        if wbs_code is not UNSET:
            field_dict["WBSCode"] = wbs_code
        if resource_request is not UNSET:
            field_dict["ResourceRequest"] = resource_request

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.resource_request import ResourceRequest

        d = dict(src_dict)
        project_object_id = d.pop("ProjectObjectId")

        resource_object_id = d.pop("ResourceObjectId")

        role_object_id = d.pop("RoleObjectId")

        wbs_object_id = d.pop("WBSObjectId")

        committed_flag = d.pop("CommittedFlag", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        _finish_date = d.pop("FinishDate", UNSET)
        finish_date: datetime.datetime | Unset
        if isinstance(_finish_date, Unset):
            finish_date = UNSET
        else:
            finish_date = isoparse(_finish_date)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        life_of_project_flag = d.pop("LifeOfProjectFlag", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        project_resource_category_name = d.pop("ProjectResourceCategoryName", UNSET)

        project_resource_category_object_id = d.pop("ProjectResourceCategoryObjectId", UNSET)

        resource_name = d.pop("ResourceName", UNSET)

        role_name = d.pop("RoleName", UNSET)

        _start_date = d.pop("StartDate", UNSET)
        start_date: datetime.datetime | Unset
        if isinstance(_start_date, Unset):
            start_date = UNSET
        else:
            start_date = isoparse(_start_date)

        status = d.pop("Status", UNSET)

        wbs_code = d.pop("WBSCode", UNSET)

        _resource_request = d.pop("ResourceRequest", UNSET)
        resource_request: ResourceRequest | Unset
        if isinstance(_resource_request, Unset):
            resource_request = UNSET
        else:
            resource_request = ResourceRequest.from_dict(_resource_request)

        project_resource = cls(
            project_object_id=project_object_id,
            resource_object_id=resource_object_id,
            role_object_id=role_object_id,
            wbs_object_id=wbs_object_id,
            committed_flag=committed_flag,
            create_date=create_date,
            create_user=create_user,
            finish_date=finish_date,
            is_baseline=is_baseline,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            life_of_project_flag=life_of_project_flag,
            object_id=object_id,
            project_id=project_id,
            project_resource_category_name=project_resource_category_name,
            project_resource_category_object_id=project_resource_category_object_id,
            resource_name=resource_name,
            role_name=role_name,
            start_date=start_date,
            status=status,
            wbs_code=wbs_code,
            resource_request=resource_request,
        )

        project_resource.additional_properties = d
        return project_resource

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
