from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="Relationship")


@_attrs_define
class Relationship:
    """Relationship Entity

    Attributes:
        predecessor_activity_object_id (int): The unique ID of the predecessor activity.
        successor_activity_object_id (int): The unique ID of the successor activity.
        aref (datetime.datetime | Unset): The Adjusted Relationship Early Finish where one of the activities of the
            relationship is in a project which is not present in this database.
        arls (datetime.datetime | Unset): The Adjusted Relationship Late Start where one of the activities of the
            relationship is in a project which is not present in this database.
        comments (str | Unset):
        create_date (datetime.datetime | Unset): The date this dependency was created.
        create_user (str | Unset): The name of the user that created this dependency.
        driving (bool | Unset):
        is_predecessor_baseline (bool | Unset): The YesNo value indicating if the predecessor activity is related to a
            Project or Baseline
        is_predecessor_template (bool | Unset): The boolean value indicating if this business object is related to a
            template Project.
        is_successor_baseline (bool | Unset): The YesNo value indicating if the successor activity is related to a
            Project or Baseline
        is_successor_template (bool | Unset): The boolean value indicating if this business object is related to a
            template Project.
        lag (float | Unset): The time lag of the relationship. This is the time lag between the predecessor activity's
            start or finish date and the successor activity's start or finish date, depending on the relationship type. The
            time lag is based on the successor activity's calendar. This value is specified by the project manager and is
            used by the project scheduler when scheduling activities.
        last_update_date (datetime.datetime | Unset): The date this dependency was last updated.
        last_update_user (str | Unset): The name of the user that last updated this dependency.
        object_id (int | Unset): The unique ID generated by the system.
        predecessor_activity_id (str | Unset): The activity ID of the predecessor activity.
        predecessor_activity_name (str | Unset): The name of the predecessor activity.
        predecessor_activity_type (str | Unset): The type of the predecessor activity, either 'Task Dependent',
            'Resource Dependent', 'Level of Effort', or 'Milestone'.
        predecessor_finish_date (datetime.datetime | Unset): The finish date of the predecessor activity.
        predecessor_project_id (str | Unset): The project ID of the project that owns the predecessor activity.
        predecessor_project_object_id (int | Unset): The unique ID of the project that owns the predecessor activity.
        predecessor_start_date (datetime.datetime | Unset): The start date of the predecessor activity.
        predecessor_wbs_name (str | Unset): The name of each WBS element in the predecessor activity.
        successor_activity_id (str | Unset): The activity ID of the successor activity.
        successor_activity_name (str | Unset): The name of the successor activity.
        successor_activity_type (str | Unset): The type of the successor activity, either 'Task Dependent', 'Resource
            Dependent', 'Level of Effort', or 'Milestone'.
        successor_finish_date (datetime.datetime | Unset): The finish date of the successor activity.
        successor_project_id (str | Unset): The project ID of the project that owns the successor activity.
        successor_project_object_id (int | Unset): The unique ID of the project that owns the successor activity.
        successor_start_date (datetime.datetime | Unset): The start date of the successor activity.
        successor_wbs_name (str | Unset): The name of each WBS element in the successor activity.
        type_ (str | Unset): The type of relationship: 'Finish to Start', 'Finish to Finish', 'Start to Start', or
            'Start to Finish'.
    """

    predecessor_activity_object_id: int
    successor_activity_object_id: int
    aref: datetime.datetime | Unset = UNSET
    arls: datetime.datetime | Unset = UNSET
    comments: str | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    driving: bool | Unset = UNSET
    is_predecessor_baseline: bool | Unset = UNSET
    is_predecessor_template: bool | Unset = UNSET
    is_successor_baseline: bool | Unset = UNSET
    is_successor_template: bool | Unset = UNSET
    lag: float | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    predecessor_activity_id: str | Unset = UNSET
    predecessor_activity_name: str | Unset = UNSET
    predecessor_activity_type: str | Unset = UNSET
    predecessor_finish_date: datetime.datetime | Unset = UNSET
    predecessor_project_id: str | Unset = UNSET
    predecessor_project_object_id: int | Unset = UNSET
    predecessor_start_date: datetime.datetime | Unset = UNSET
    predecessor_wbs_name: str | Unset = UNSET
    successor_activity_id: str | Unset = UNSET
    successor_activity_name: str | Unset = UNSET
    successor_activity_type: str | Unset = UNSET
    successor_finish_date: datetime.datetime | Unset = UNSET
    successor_project_id: str | Unset = UNSET
    successor_project_object_id: int | Unset = UNSET
    successor_start_date: datetime.datetime | Unset = UNSET
    successor_wbs_name: str | Unset = UNSET
    type_: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        predecessor_activity_object_id = self.predecessor_activity_object_id

        successor_activity_object_id = self.successor_activity_object_id

        aref: str | Unset = UNSET
        if not isinstance(self.aref, Unset):
            aref = self.aref.isoformat()

        arls: str | Unset = UNSET
        if not isinstance(self.arls, Unset):
            arls = self.arls.isoformat()

        comments = self.comments

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        driving = self.driving

        is_predecessor_baseline = self.is_predecessor_baseline

        is_predecessor_template = self.is_predecessor_template

        is_successor_baseline = self.is_successor_baseline

        is_successor_template = self.is_successor_template

        lag = self.lag

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        predecessor_activity_id = self.predecessor_activity_id

        predecessor_activity_name = self.predecessor_activity_name

        predecessor_activity_type = self.predecessor_activity_type

        predecessor_finish_date: str | Unset = UNSET
        if not isinstance(self.predecessor_finish_date, Unset):
            predecessor_finish_date = self.predecessor_finish_date.isoformat()

        predecessor_project_id = self.predecessor_project_id

        predecessor_project_object_id = self.predecessor_project_object_id

        predecessor_start_date: str | Unset = UNSET
        if not isinstance(self.predecessor_start_date, Unset):
            predecessor_start_date = self.predecessor_start_date.isoformat()

        predecessor_wbs_name = self.predecessor_wbs_name

        successor_activity_id = self.successor_activity_id

        successor_activity_name = self.successor_activity_name

        successor_activity_type = self.successor_activity_type

        successor_finish_date: str | Unset = UNSET
        if not isinstance(self.successor_finish_date, Unset):
            successor_finish_date = self.successor_finish_date.isoformat()

        successor_project_id = self.successor_project_id

        successor_project_object_id = self.successor_project_object_id

        successor_start_date: str | Unset = UNSET
        if not isinstance(self.successor_start_date, Unset):
            successor_start_date = self.successor_start_date.isoformat()

        successor_wbs_name = self.successor_wbs_name

        type_ = self.type_

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "PredecessorActivityObjectId": predecessor_activity_object_id,
                "SuccessorActivityObjectId": successor_activity_object_id,
            }
        )
        if aref is not UNSET:
            field_dict["Aref"] = aref
        if arls is not UNSET:
            field_dict["Arls"] = arls
        if comments is not UNSET:
            field_dict["Comments"] = comments
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if driving is not UNSET:
            field_dict["Driving"] = driving
        if is_predecessor_baseline is not UNSET:
            field_dict["IsPredecessorBaseline"] = is_predecessor_baseline
        if is_predecessor_template is not UNSET:
            field_dict["IsPredecessorTemplate"] = is_predecessor_template
        if is_successor_baseline is not UNSET:
            field_dict["IsSuccessorBaseline"] = is_successor_baseline
        if is_successor_template is not UNSET:
            field_dict["IsSuccessorTemplate"] = is_successor_template
        if lag is not UNSET:
            field_dict["Lag"] = lag
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if predecessor_activity_id is not UNSET:
            field_dict["PredecessorActivityId"] = predecessor_activity_id
        if predecessor_activity_name is not UNSET:
            field_dict["PredecessorActivityName"] = predecessor_activity_name
        if predecessor_activity_type is not UNSET:
            field_dict["PredecessorActivityType"] = predecessor_activity_type
        if predecessor_finish_date is not UNSET:
            field_dict["PredecessorFinishDate"] = predecessor_finish_date
        if predecessor_project_id is not UNSET:
            field_dict["PredecessorProjectId"] = predecessor_project_id
        if predecessor_project_object_id is not UNSET:
            field_dict["PredecessorProjectObjectId"] = predecessor_project_object_id
        if predecessor_start_date is not UNSET:
            field_dict["PredecessorStartDate"] = predecessor_start_date
        if predecessor_wbs_name is not UNSET:
            field_dict["PredecessorWbsName"] = predecessor_wbs_name
        if successor_activity_id is not UNSET:
            field_dict["SuccessorActivityId"] = successor_activity_id
        if successor_activity_name is not UNSET:
            field_dict["SuccessorActivityName"] = successor_activity_name
        if successor_activity_type is not UNSET:
            field_dict["SuccessorActivityType"] = successor_activity_type
        if successor_finish_date is not UNSET:
            field_dict["SuccessorFinishDate"] = successor_finish_date
        if successor_project_id is not UNSET:
            field_dict["SuccessorProjectId"] = successor_project_id
        if successor_project_object_id is not UNSET:
            field_dict["SuccessorProjectObjectId"] = successor_project_object_id
        if successor_start_date is not UNSET:
            field_dict["SuccessorStartDate"] = successor_start_date
        if successor_wbs_name is not UNSET:
            field_dict["SuccessorWbsName"] = successor_wbs_name
        if type_ is not UNSET:
            field_dict["Type"] = type_

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        predecessor_activity_object_id = d.pop("PredecessorActivityObjectId")

        successor_activity_object_id = d.pop("SuccessorActivityObjectId")

        _aref = d.pop("Aref", UNSET)
        aref: datetime.datetime | Unset
        if isinstance(_aref, Unset):
            aref = UNSET
        else:
            aref = isoparse(_aref)

        _arls = d.pop("Arls", UNSET)
        arls: datetime.datetime | Unset
        if isinstance(_arls, Unset):
            arls = UNSET
        else:
            arls = isoparse(_arls)

        comments = d.pop("Comments", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        driving = d.pop("Driving", UNSET)

        is_predecessor_baseline = d.pop("IsPredecessorBaseline", UNSET)

        is_predecessor_template = d.pop("IsPredecessorTemplate", UNSET)

        is_successor_baseline = d.pop("IsSuccessorBaseline", UNSET)

        is_successor_template = d.pop("IsSuccessorTemplate", UNSET)

        lag = d.pop("Lag", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        predecessor_activity_id = d.pop("PredecessorActivityId", UNSET)

        predecessor_activity_name = d.pop("PredecessorActivityName", UNSET)

        predecessor_activity_type = d.pop("PredecessorActivityType", UNSET)

        _predecessor_finish_date = d.pop("PredecessorFinishDate", UNSET)
        predecessor_finish_date: datetime.datetime | Unset
        if isinstance(_predecessor_finish_date, Unset):
            predecessor_finish_date = UNSET
        else:
            predecessor_finish_date = isoparse(_predecessor_finish_date)

        predecessor_project_id = d.pop("PredecessorProjectId", UNSET)

        predecessor_project_object_id = d.pop("PredecessorProjectObjectId", UNSET)

        _predecessor_start_date = d.pop("PredecessorStartDate", UNSET)
        predecessor_start_date: datetime.datetime | Unset
        if isinstance(_predecessor_start_date, Unset):
            predecessor_start_date = UNSET
        else:
            predecessor_start_date = isoparse(_predecessor_start_date)

        predecessor_wbs_name = d.pop("PredecessorWbsName", UNSET)

        successor_activity_id = d.pop("SuccessorActivityId", UNSET)

        successor_activity_name = d.pop("SuccessorActivityName", UNSET)

        successor_activity_type = d.pop("SuccessorActivityType", UNSET)

        _successor_finish_date = d.pop("SuccessorFinishDate", UNSET)
        successor_finish_date: datetime.datetime | Unset
        if isinstance(_successor_finish_date, Unset):
            successor_finish_date = UNSET
        else:
            successor_finish_date = isoparse(_successor_finish_date)

        successor_project_id = d.pop("SuccessorProjectId", UNSET)

        successor_project_object_id = d.pop("SuccessorProjectObjectId", UNSET)

        _successor_start_date = d.pop("SuccessorStartDate", UNSET)
        successor_start_date: datetime.datetime | Unset
        if isinstance(_successor_start_date, Unset):
            successor_start_date = UNSET
        else:
            successor_start_date = isoparse(_successor_start_date)

        successor_wbs_name = d.pop("SuccessorWbsName", UNSET)

        type_ = d.pop("Type", UNSET)

        relationship = cls(
            predecessor_activity_object_id=predecessor_activity_object_id,
            successor_activity_object_id=successor_activity_object_id,
            aref=aref,
            arls=arls,
            comments=comments,
            create_date=create_date,
            create_user=create_user,
            driving=driving,
            is_predecessor_baseline=is_predecessor_baseline,
            is_predecessor_template=is_predecessor_template,
            is_successor_baseline=is_successor_baseline,
            is_successor_template=is_successor_template,
            lag=lag,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            predecessor_activity_id=predecessor_activity_id,
            predecessor_activity_name=predecessor_activity_name,
            predecessor_activity_type=predecessor_activity_type,
            predecessor_finish_date=predecessor_finish_date,
            predecessor_project_id=predecessor_project_id,
            predecessor_project_object_id=predecessor_project_object_id,
            predecessor_start_date=predecessor_start_date,
            predecessor_wbs_name=predecessor_wbs_name,
            successor_activity_id=successor_activity_id,
            successor_activity_name=successor_activity_name,
            successor_activity_type=successor_activity_type,
            successor_finish_date=successor_finish_date,
            successor_project_id=successor_project_id,
            successor_project_object_id=successor_project_object_id,
            successor_start_date=successor_start_date,
            successor_wbs_name=successor_wbs_name,
            type_=type_,
        )

        relationship.additional_properties = d
        return relationship

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
