from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ResourceCodeType")


@_attrs_define
class ResourceCodeType:
    """ResourceCodeType Entity

    Attributes:
        create_date (datetime.datetime | Unset): The date this resource code type was created.
        create_user (str | Unset): The name of the user that created this resource code type.
        is_secure_code (bool | Unset): The flag indicating whether this is a secure Resource Code Type.
        length (int | Unset): The maximum number of characters allowed for values of this resource code.
        last_update_date (datetime.datetime | Unset): The date this resource code type was last updated.
        last_update_user (str | Unset): The name of the user that last updated this resource code type.
        object_id (int | Unset): The unique ID generated by the system.
        name (str | Unset): The name of the resource code type.
        sequence_number (int | Unset): The sequence number for sorting.
    """

    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    is_secure_code: bool | Unset = UNSET
    length: int | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    name: str | Unset = UNSET
    sequence_number: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        is_secure_code = self.is_secure_code

        length = self.length

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        name = self.name

        sequence_number = self.sequence_number

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if is_secure_code is not UNSET:
            field_dict["IsSecureCode"] = is_secure_code
        if length is not UNSET:
            field_dict["Length"] = length
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if name is not UNSET:
            field_dict["Name"] = name
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        is_secure_code = d.pop("IsSecureCode", UNSET)

        length = d.pop("Length", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        name = d.pop("Name", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        resource_code_type = cls(
            create_date=create_date,
            create_user=create_user,
            is_secure_code=is_secure_code,
            length=length,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            name=name,
            sequence_number=sequence_number,
        )

        resource_code_type.additional_properties = d
        return resource_code_type

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
