from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ResourceAssignmentUpdate")


@_attrs_define
class ResourceAssignmentUpdate:
    """ResourceAssignmentUpdate Entity

    Attributes:
        change_set_object_id (int): The unique ID generated by the system for the change set object.
        resource_assignment_object_id (int): The unique identifier for the ResourceAssignment. You can specify one or
            more ResourceAssignmentObjectID.
        activity_object_id (int | Unset): The name of the Contract Management Group.
        all_data (str | Unset): The unique ID of the activity to which the activity code is assigned.
        approval_date (datetime.datetime | Unset): The date that the activity was approved.
        approval_user_name (str | Unset): The username of the approved user.
        approval_user_object_id (int | Unset): The unique ID generated by the system for the approved user.
        calendar_id (int | Unset):
        create_user (str | Unset):
        date (datetime.datetime | Unset): The date of the resource assignment update.
        held_date (datetime.datetime | Unset): The date of the held resource assignment.
        override_actual_finish_date (datetime.datetime | Unset): The actual finish date for an override activity.
        override_actual_start_date (datetime.datetime | Unset): The actual start date for an override activity.
        override_actual_units (float | Unset): The number of units for an override activity.
        override_remaining_duration (float | Unset): The remaining duration for an override activity.
        override_remaining_finish_date (datetime.datetime | Unset): The date that the override activity finishes.
        override_remaining_units (float | Unset): The overridden new remaining units of work to be performed by this
            resource on this activity.
        pending_actual_finish_date (datetime.datetime | Unset): The date on which the pending activity actually finishes
            if approval is required.
        pending_actual_start_date (datetime.datetime | Unset): The date on which the pending activity actually starts if
            approval is required.
        pending_actual_units (float | Unset): The actual number of units associated with the the pending activity if
            approval is required.
        pending_remaining_duration (float | Unset): The remaining duration that is required to finish a pending activity
            if approval is required.
        pending_remaining_finish_date (datetime.datetime | Unset): The remaining finish date of a pending activity if
            approval is required.
        pending_remaining_units (float | Unset): The remaining number of units associated with a pending activity if
            approval is required.
        project_object_id (int | Unset): The unique ID of the associated project.
        rejected_by (str | Unset):
        rejected_date (datetime.datetime | Unset):
        request_user_object_id (int | Unset): The unique ID of the user modifying the task, assignment, or step.
        resubmitted_by (str | Unset):
        resubmitted_date (datetime.datetime | Unset):
        status (str | Unset): The status of this budget change request. Possible values are 'Pending', 'Held', and
            'Approved'.
    """

    change_set_object_id: int
    resource_assignment_object_id: int
    activity_object_id: int | Unset = UNSET
    all_data: str | Unset = UNSET
    approval_date: datetime.datetime | Unset = UNSET
    approval_user_name: str | Unset = UNSET
    approval_user_object_id: int | Unset = UNSET
    calendar_id: int | Unset = UNSET
    create_user: str | Unset = UNSET
    date: datetime.datetime | Unset = UNSET
    held_date: datetime.datetime | Unset = UNSET
    override_actual_finish_date: datetime.datetime | Unset = UNSET
    override_actual_start_date: datetime.datetime | Unset = UNSET
    override_actual_units: float | Unset = UNSET
    override_remaining_duration: float | Unset = UNSET
    override_remaining_finish_date: datetime.datetime | Unset = UNSET
    override_remaining_units: float | Unset = UNSET
    pending_actual_finish_date: datetime.datetime | Unset = UNSET
    pending_actual_start_date: datetime.datetime | Unset = UNSET
    pending_actual_units: float | Unset = UNSET
    pending_remaining_duration: float | Unset = UNSET
    pending_remaining_finish_date: datetime.datetime | Unset = UNSET
    pending_remaining_units: float | Unset = UNSET
    project_object_id: int | Unset = UNSET
    rejected_by: str | Unset = UNSET
    rejected_date: datetime.datetime | Unset = UNSET
    request_user_object_id: int | Unset = UNSET
    resubmitted_by: str | Unset = UNSET
    resubmitted_date: datetime.datetime | Unset = UNSET
    status: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        change_set_object_id = self.change_set_object_id

        resource_assignment_object_id = self.resource_assignment_object_id

        activity_object_id = self.activity_object_id

        all_data = self.all_data

        approval_date: str | Unset = UNSET
        if not isinstance(self.approval_date, Unset):
            approval_date = self.approval_date.isoformat()

        approval_user_name = self.approval_user_name

        approval_user_object_id = self.approval_user_object_id

        calendar_id = self.calendar_id

        create_user = self.create_user

        date: str | Unset = UNSET
        if not isinstance(self.date, Unset):
            date = self.date.isoformat()

        held_date: str | Unset = UNSET
        if not isinstance(self.held_date, Unset):
            held_date = self.held_date.isoformat()

        override_actual_finish_date: str | Unset = UNSET
        if not isinstance(self.override_actual_finish_date, Unset):
            override_actual_finish_date = self.override_actual_finish_date.isoformat()

        override_actual_start_date: str | Unset = UNSET
        if not isinstance(self.override_actual_start_date, Unset):
            override_actual_start_date = self.override_actual_start_date.isoformat()

        override_actual_units = self.override_actual_units

        override_remaining_duration = self.override_remaining_duration

        override_remaining_finish_date: str | Unset = UNSET
        if not isinstance(self.override_remaining_finish_date, Unset):
            override_remaining_finish_date = self.override_remaining_finish_date.isoformat()

        override_remaining_units = self.override_remaining_units

        pending_actual_finish_date: str | Unset = UNSET
        if not isinstance(self.pending_actual_finish_date, Unset):
            pending_actual_finish_date = self.pending_actual_finish_date.isoformat()

        pending_actual_start_date: str | Unset = UNSET
        if not isinstance(self.pending_actual_start_date, Unset):
            pending_actual_start_date = self.pending_actual_start_date.isoformat()

        pending_actual_units = self.pending_actual_units

        pending_remaining_duration = self.pending_remaining_duration

        pending_remaining_finish_date: str | Unset = UNSET
        if not isinstance(self.pending_remaining_finish_date, Unset):
            pending_remaining_finish_date = self.pending_remaining_finish_date.isoformat()

        pending_remaining_units = self.pending_remaining_units

        project_object_id = self.project_object_id

        rejected_by = self.rejected_by

        rejected_date: str | Unset = UNSET
        if not isinstance(self.rejected_date, Unset):
            rejected_date = self.rejected_date.isoformat()

        request_user_object_id = self.request_user_object_id

        resubmitted_by = self.resubmitted_by

        resubmitted_date: str | Unset = UNSET
        if not isinstance(self.resubmitted_date, Unset):
            resubmitted_date = self.resubmitted_date.isoformat()

        status = self.status

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "ChangeSetObjectId": change_set_object_id,
                "ResourceAssignmentObjectId": resource_assignment_object_id,
            }
        )
        if activity_object_id is not UNSET:
            field_dict["ActivityObjectId"] = activity_object_id
        if all_data is not UNSET:
            field_dict["AllData"] = all_data
        if approval_date is not UNSET:
            field_dict["ApprovalDate"] = approval_date
        if approval_user_name is not UNSET:
            field_dict["ApprovalUserName"] = approval_user_name
        if approval_user_object_id is not UNSET:
            field_dict["ApprovalUserObjectId"] = approval_user_object_id
        if calendar_id is not UNSET:
            field_dict["CalendarId"] = calendar_id
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if date is not UNSET:
            field_dict["Date"] = date
        if held_date is not UNSET:
            field_dict["HeldDate"] = held_date
        if override_actual_finish_date is not UNSET:
            field_dict["OverrideActualFinishDate"] = override_actual_finish_date
        if override_actual_start_date is not UNSET:
            field_dict["OverrideActualStartDate"] = override_actual_start_date
        if override_actual_units is not UNSET:
            field_dict["OverrideActualUnits"] = override_actual_units
        if override_remaining_duration is not UNSET:
            field_dict["OverrideRemainingDuration"] = override_remaining_duration
        if override_remaining_finish_date is not UNSET:
            field_dict["OverrideRemainingFinishDate"] = override_remaining_finish_date
        if override_remaining_units is not UNSET:
            field_dict["OverrideRemainingUnits"] = override_remaining_units
        if pending_actual_finish_date is not UNSET:
            field_dict["PendingActualFinishDate"] = pending_actual_finish_date
        if pending_actual_start_date is not UNSET:
            field_dict["PendingActualStartDate"] = pending_actual_start_date
        if pending_actual_units is not UNSET:
            field_dict["PendingActualUnits"] = pending_actual_units
        if pending_remaining_duration is not UNSET:
            field_dict["PendingRemainingDuration"] = pending_remaining_duration
        if pending_remaining_finish_date is not UNSET:
            field_dict["PendingRemainingFinishDate"] = pending_remaining_finish_date
        if pending_remaining_units is not UNSET:
            field_dict["PendingRemainingUnits"] = pending_remaining_units
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if rejected_by is not UNSET:
            field_dict["RejectedBy"] = rejected_by
        if rejected_date is not UNSET:
            field_dict["RejectedDate"] = rejected_date
        if request_user_object_id is not UNSET:
            field_dict["RequestUserObjectId"] = request_user_object_id
        if resubmitted_by is not UNSET:
            field_dict["ResubmittedBy"] = resubmitted_by
        if resubmitted_date is not UNSET:
            field_dict["ResubmittedDate"] = resubmitted_date
        if status is not UNSET:
            field_dict["Status"] = status

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        change_set_object_id = d.pop("ChangeSetObjectId")

        resource_assignment_object_id = d.pop("ResourceAssignmentObjectId")

        activity_object_id = d.pop("ActivityObjectId", UNSET)

        all_data = d.pop("AllData", UNSET)

        _approval_date = d.pop("ApprovalDate", UNSET)
        approval_date: datetime.datetime | Unset
        if isinstance(_approval_date, Unset):
            approval_date = UNSET
        else:
            approval_date = isoparse(_approval_date)

        approval_user_name = d.pop("ApprovalUserName", UNSET)

        approval_user_object_id = d.pop("ApprovalUserObjectId", UNSET)

        calendar_id = d.pop("CalendarId", UNSET)

        create_user = d.pop("CreateUser", UNSET)

        _date = d.pop("Date", UNSET)
        date: datetime.datetime | Unset
        if isinstance(_date, Unset):
            date = UNSET
        else:
            date = isoparse(_date)

        _held_date = d.pop("HeldDate", UNSET)
        held_date: datetime.datetime | Unset
        if isinstance(_held_date, Unset):
            held_date = UNSET
        else:
            held_date = isoparse(_held_date)

        _override_actual_finish_date = d.pop("OverrideActualFinishDate", UNSET)
        override_actual_finish_date: datetime.datetime | Unset
        if isinstance(_override_actual_finish_date, Unset):
            override_actual_finish_date = UNSET
        else:
            override_actual_finish_date = isoparse(_override_actual_finish_date)

        _override_actual_start_date = d.pop("OverrideActualStartDate", UNSET)
        override_actual_start_date: datetime.datetime | Unset
        if isinstance(_override_actual_start_date, Unset):
            override_actual_start_date = UNSET
        else:
            override_actual_start_date = isoparse(_override_actual_start_date)

        override_actual_units = d.pop("OverrideActualUnits", UNSET)

        override_remaining_duration = d.pop("OverrideRemainingDuration", UNSET)

        _override_remaining_finish_date = d.pop("OverrideRemainingFinishDate", UNSET)
        override_remaining_finish_date: datetime.datetime | Unset
        if isinstance(_override_remaining_finish_date, Unset):
            override_remaining_finish_date = UNSET
        else:
            override_remaining_finish_date = isoparse(_override_remaining_finish_date)

        override_remaining_units = d.pop("OverrideRemainingUnits", UNSET)

        _pending_actual_finish_date = d.pop("PendingActualFinishDate", UNSET)
        pending_actual_finish_date: datetime.datetime | Unset
        if isinstance(_pending_actual_finish_date, Unset):
            pending_actual_finish_date = UNSET
        else:
            pending_actual_finish_date = isoparse(_pending_actual_finish_date)

        _pending_actual_start_date = d.pop("PendingActualStartDate", UNSET)
        pending_actual_start_date: datetime.datetime | Unset
        if isinstance(_pending_actual_start_date, Unset):
            pending_actual_start_date = UNSET
        else:
            pending_actual_start_date = isoparse(_pending_actual_start_date)

        pending_actual_units = d.pop("PendingActualUnits", UNSET)

        pending_remaining_duration = d.pop("PendingRemainingDuration", UNSET)

        _pending_remaining_finish_date = d.pop("PendingRemainingFinishDate", UNSET)
        pending_remaining_finish_date: datetime.datetime | Unset
        if isinstance(_pending_remaining_finish_date, Unset):
            pending_remaining_finish_date = UNSET
        else:
            pending_remaining_finish_date = isoparse(_pending_remaining_finish_date)

        pending_remaining_units = d.pop("PendingRemainingUnits", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        rejected_by = d.pop("RejectedBy", UNSET)

        _rejected_date = d.pop("RejectedDate", UNSET)
        rejected_date: datetime.datetime | Unset
        if isinstance(_rejected_date, Unset):
            rejected_date = UNSET
        else:
            rejected_date = isoparse(_rejected_date)

        request_user_object_id = d.pop("RequestUserObjectId", UNSET)

        resubmitted_by = d.pop("ResubmittedBy", UNSET)

        _resubmitted_date = d.pop("ResubmittedDate", UNSET)
        resubmitted_date: datetime.datetime | Unset
        if isinstance(_resubmitted_date, Unset):
            resubmitted_date = UNSET
        else:
            resubmitted_date = isoparse(_resubmitted_date)

        status = d.pop("Status", UNSET)

        resource_assignment_update = cls(
            change_set_object_id=change_set_object_id,
            resource_assignment_object_id=resource_assignment_object_id,
            activity_object_id=activity_object_id,
            all_data=all_data,
            approval_date=approval_date,
            approval_user_name=approval_user_name,
            approval_user_object_id=approval_user_object_id,
            calendar_id=calendar_id,
            create_user=create_user,
            date=date,
            held_date=held_date,
            override_actual_finish_date=override_actual_finish_date,
            override_actual_start_date=override_actual_start_date,
            override_actual_units=override_actual_units,
            override_remaining_duration=override_remaining_duration,
            override_remaining_finish_date=override_remaining_finish_date,
            override_remaining_units=override_remaining_units,
            pending_actual_finish_date=pending_actual_finish_date,
            pending_actual_start_date=pending_actual_start_date,
            pending_actual_units=pending_actual_units,
            pending_remaining_duration=pending_remaining_duration,
            pending_remaining_finish_date=pending_remaining_finish_date,
            pending_remaining_units=pending_remaining_units,
            project_object_id=project_object_id,
            rejected_by=rejected_by,
            rejected_date=rejected_date,
            request_user_object_id=request_user_object_id,
            resubmitted_by=resubmitted_by,
            resubmitted_date=resubmitted_date,
            status=status,
        )

        resource_assignment_update.additional_properties = d
        return resource_assignment_update

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
