from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.member_resource import MemberResource


T = TypeVar("T", bound="ResourceTeam")


@_attrs_define
class ResourceTeam:
    """ResourceTeam Entity

    Attributes:
        create_date (datetime.datetime | Unset): The date this resource team was created.
        create_user (str | Unset): The name of the user that created this resource team.
        description (str | Unset): The description of the resource team.
        last_update_date (datetime.datetime | Unset): The date this resource team was last updated.
        last_update_user (str | Unset): The name of the user that last updated this resource team.
        name (str | Unset): The name of the resource team.
        object_id (int | Unset): The unique ID generated by the system.
        user_name (str | Unset): The user's login name.
        user_object_id (int | Unset): The unique ID of the associated user.
        member_resource (list[MemberResource] | Unset):
    """

    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    description: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    name: str | Unset = UNSET
    object_id: int | Unset = UNSET
    user_name: str | Unset = UNSET
    user_object_id: int | Unset = UNSET
    member_resource: list[MemberResource] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        description = self.description

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        name = self.name

        object_id = self.object_id

        user_name = self.user_name

        user_object_id = self.user_object_id

        member_resource: list[dict[str, Any]] | Unset = UNSET
        if not isinstance(self.member_resource, Unset):
            member_resource = []
            for member_resource_item_data in self.member_resource:
                member_resource_item = member_resource_item_data.to_dict()
                member_resource.append(member_resource_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if description is not UNSET:
            field_dict["Description"] = description
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if name is not UNSET:
            field_dict["Name"] = name
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if user_name is not UNSET:
            field_dict["UserName"] = user_name
        if user_object_id is not UNSET:
            field_dict["UserObjectId"] = user_object_id
        if member_resource is not UNSET:
            field_dict["MemberResource"] = member_resource

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.member_resource import MemberResource

        d = dict(src_dict)
        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        description = d.pop("Description", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        name = d.pop("Name", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        user_name = d.pop("UserName", UNSET)

        user_object_id = d.pop("UserObjectId", UNSET)

        _member_resource = d.pop("MemberResource", UNSET)
        member_resource: list[MemberResource] | Unset = UNSET
        if _member_resource is not UNSET:
            member_resource = []
            for member_resource_item_data in _member_resource:
                member_resource_item = MemberResource.from_dict(member_resource_item_data)

                member_resource.append(member_resource_item)

        resource_team = cls(
            create_date=create_date,
            create_user=create_user,
            description=description,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            name=name,
            object_id=object_id,
            user_name=user_name,
            user_object_id=user_object_id,
            member_resource=member_resource,
        )

        resource_team.additional_properties = d
        return resource_team

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
