from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="ResourceHour")


@_attrs_define
class ResourceHour:
    """ResourceHour Entity

    Attributes:
        overhead_code_object_id (int): The unique ID of the overhead code, if the hours are for an overhead activity.
        resource_assignment_object_id (int): The unique ID of the associated resource assignment.
        resource_object_id (int): The unique ID of the associated resource.
        timesheet_period_object_id (int): The unique ID of the associated timesheet.
        activity_object_id (int | Unset): The unique ID of the activity to which the resource is assigned.
        activity_timesheet_link_flag (bool | Unset): The value which indicates if the record is a real timesheet entry
            (false) or simply a placeholder for a timesheet entry (true).
        approved_hours (float | Unset): The number of hours, approved.
        approved_overtime_hours (float | Unset): The number of overtime hours, approved.
        create_date (datetime.datetime | Unset): The date this data was created.
        create_user (str | Unset): The name of the user that created this data.
        date (datetime.datetime | Unset): The date to which the hours apply.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this data was last updated.
        last_update_user (str | Unset): The name of the user that last updated this data.
        object_id (int | Unset): The unique ID generated by the system.
        overhead_code_name (str | Unset): The name of the overhead code.
        project_id (str | Unset): The short code that uniquely identifies the project.
        project_name (str | Unset): The name of the associated project.
        project_object_id (int | Unset): The unique ID of the associated project.
        resource_id (str | Unset): The short code that uniquely identifies the resource.
        resource_integrated_type (str | Unset): The flag indicating whether the resource is integrated with an
            Enterprise Resource Planning (ERP) system. 'Fusion' indicates the resource is integrated with Oracle Fusion.
            'ERP' indicates the resource is integrated with another ERP system. 'Gateway' indicates the resource is
            integrated with Oracle Primavera Gateway.
        resource_name (str | Unset): The name of the resource.
        status (str | Unset): The approval level, when timesheets require approval: 'Submitted', 'Approved', 'Resource
            Manager Approved', 'Project Manager Approved', 'Active', or 'Rejected'.
        timesheet_status_date (datetime.datetime | Unset): The status date of the associated timesheet.
        unapproved_hours (float | Unset): The actual non-overtime units submitted by the resource on the activity. These
            units remain submitted until the timesheet is approved.
        unapproved_overtime_hours (float | Unset): The actual overtime units submitted by the resource on the acitivity.
            These units remain submitted until the timesheet is approved.
        wbs_object_id (int | Unset): The unique ID of the WBS for the activity.
    """

    overhead_code_object_id: int
    resource_assignment_object_id: int
    resource_object_id: int
    timesheet_period_object_id: int
    activity_object_id: int | Unset = UNSET
    activity_timesheet_link_flag: bool | Unset = UNSET
    approved_hours: float | Unset = UNSET
    approved_overtime_hours: float | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    date: datetime.datetime | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    overhead_code_name: str | Unset = UNSET
    project_id: str | Unset = UNSET
    project_name: str | Unset = UNSET
    project_object_id: int | Unset = UNSET
    resource_id: str | Unset = UNSET
    resource_integrated_type: str | Unset = UNSET
    resource_name: str | Unset = UNSET
    status: str | Unset = UNSET
    timesheet_status_date: datetime.datetime | Unset = UNSET
    unapproved_hours: float | Unset = UNSET
    unapproved_overtime_hours: float | Unset = UNSET
    wbs_object_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        overhead_code_object_id = self.overhead_code_object_id

        resource_assignment_object_id = self.resource_assignment_object_id

        resource_object_id = self.resource_object_id

        timesheet_period_object_id = self.timesheet_period_object_id

        activity_object_id = self.activity_object_id

        activity_timesheet_link_flag = self.activity_timesheet_link_flag

        approved_hours = self.approved_hours

        approved_overtime_hours = self.approved_overtime_hours

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        date: str | Unset = UNSET
        if not isinstance(self.date, Unset):
            date = self.date.isoformat()

        is_baseline = self.is_baseline

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        overhead_code_name = self.overhead_code_name

        project_id = self.project_id

        project_name = self.project_name

        project_object_id = self.project_object_id

        resource_id = self.resource_id

        resource_integrated_type = self.resource_integrated_type

        resource_name = self.resource_name

        status = self.status

        timesheet_status_date: str | Unset = UNSET
        if not isinstance(self.timesheet_status_date, Unset):
            timesheet_status_date = self.timesheet_status_date.isoformat()

        unapproved_hours = self.unapproved_hours

        unapproved_overtime_hours = self.unapproved_overtime_hours

        wbs_object_id = self.wbs_object_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "OverheadCodeObjectId": overhead_code_object_id,
                "ResourceAssignmentObjectId": resource_assignment_object_id,
                "ResourceObjectId": resource_object_id,
                "TimesheetPeriodObjectId": timesheet_period_object_id,
            }
        )
        if activity_object_id is not UNSET:
            field_dict["ActivityObjectId"] = activity_object_id
        if activity_timesheet_link_flag is not UNSET:
            field_dict["ActivityTimesheetLinkFlag"] = activity_timesheet_link_flag
        if approved_hours is not UNSET:
            field_dict["ApprovedHours"] = approved_hours
        if approved_overtime_hours is not UNSET:
            field_dict["ApprovedOvertimeHours"] = approved_overtime_hours
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if date is not UNSET:
            field_dict["Date"] = date
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if overhead_code_name is not UNSET:
            field_dict["OverheadCodeName"] = overhead_code_name
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if project_name is not UNSET:
            field_dict["ProjectName"] = project_name
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if resource_id is not UNSET:
            field_dict["ResourceId"] = resource_id
        if resource_integrated_type is not UNSET:
            field_dict["ResourceIntegratedType"] = resource_integrated_type
        if resource_name is not UNSET:
            field_dict["ResourceName"] = resource_name
        if status is not UNSET:
            field_dict["Status"] = status
        if timesheet_status_date is not UNSET:
            field_dict["TimesheetStatusDate"] = timesheet_status_date
        if unapproved_hours is not UNSET:
            field_dict["UnapprovedHours"] = unapproved_hours
        if unapproved_overtime_hours is not UNSET:
            field_dict["UnapprovedOvertimeHours"] = unapproved_overtime_hours
        if wbs_object_id is not UNSET:
            field_dict["WBSObjectId"] = wbs_object_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        overhead_code_object_id = d.pop("OverheadCodeObjectId")

        resource_assignment_object_id = d.pop("ResourceAssignmentObjectId")

        resource_object_id = d.pop("ResourceObjectId")

        timesheet_period_object_id = d.pop("TimesheetPeriodObjectId")

        activity_object_id = d.pop("ActivityObjectId", UNSET)

        activity_timesheet_link_flag = d.pop("ActivityTimesheetLinkFlag", UNSET)

        approved_hours = d.pop("ApprovedHours", UNSET)

        approved_overtime_hours = d.pop("ApprovedOvertimeHours", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        _date = d.pop("Date", UNSET)
        date: datetime.datetime | Unset
        if isinstance(_date, Unset):
            date = UNSET
        else:
            date = isoparse(_date)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        overhead_code_name = d.pop("OverheadCodeName", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        project_name = d.pop("ProjectName", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        resource_id = d.pop("ResourceId", UNSET)

        resource_integrated_type = d.pop("ResourceIntegratedType", UNSET)

        resource_name = d.pop("ResourceName", UNSET)

        status = d.pop("Status", UNSET)

        _timesheet_status_date = d.pop("TimesheetStatusDate", UNSET)
        timesheet_status_date: datetime.datetime | Unset
        if isinstance(_timesheet_status_date, Unset):
            timesheet_status_date = UNSET
        else:
            timesheet_status_date = isoparse(_timesheet_status_date)

        unapproved_hours = d.pop("UnapprovedHours", UNSET)

        unapproved_overtime_hours = d.pop("UnapprovedOvertimeHours", UNSET)

        wbs_object_id = d.pop("WBSObjectId", UNSET)

        resource_hour = cls(
            overhead_code_object_id=overhead_code_object_id,
            resource_assignment_object_id=resource_assignment_object_id,
            resource_object_id=resource_object_id,
            timesheet_period_object_id=timesheet_period_object_id,
            activity_object_id=activity_object_id,
            activity_timesheet_link_flag=activity_timesheet_link_flag,
            approved_hours=approved_hours,
            approved_overtime_hours=approved_overtime_hours,
            create_date=create_date,
            create_user=create_user,
            date=date,
            is_baseline=is_baseline,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            overhead_code_name=overhead_code_name,
            project_id=project_id,
            project_name=project_name,
            project_object_id=project_object_id,
            resource_id=resource_id,
            resource_integrated_type=resource_integrated_type,
            resource_name=resource_name,
            status=status,
            timesheet_status_date=timesheet_status_date,
            unapproved_hours=unapproved_hours,
            unapproved_overtime_hours=unapproved_overtime_hours,
            wbs_object_id=wbs_object_id,
        )

        resource_hour.additional_properties = d
        return resource_hour

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
