from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="RiskThreshold")


@_attrs_define
class RiskThreshold:
    """RiskThreshold Entity

    Attributes:
        name (str): The name of the risk score type.
        create_date (datetime.datetime | Unset): The date this risk score type was created.
        create_user (str | Unset): The name of the user that created the risk score type.
        last_update_date (datetime.datetime | Unset): The date this risk score type was last updated.
        last_update_user (str | Unset): The name of the user that last updated the risk score type.
        level (int | Unset): The number of Risk Threshold Levels. There are between two and nine.
        object_id (int | Unset): The unique ID generated by the system.
        threshold_type (str | Unset): The type of Risk Threshold. Valid types are 'Probability', 'Tolerance',
            'Schedule', 'Cost', 'Relative Schedule', 'Relative Cost' and 'User Defined'
    """

    name: str
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    level: int | Unset = UNSET
    object_id: int | Unset = UNSET
    threshold_type: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        level = self.level

        object_id = self.object_id

        threshold_type = self.threshold_type

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Name": name,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if level is not UNSET:
            field_dict["Level"] = level
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if threshold_type is not UNSET:
            field_dict["ThresholdType"] = threshold_type

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("Name")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        level = d.pop("Level", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        threshold_type = d.pop("ThresholdType", UNSET)

        risk_threshold = cls(
            name=name,
            create_date=create_date,
            create_user=create_user,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            level=level,
            object_id=object_id,
            threshold_type=threshold_type,
        )

        risk_threshold.additional_properties = d
        return risk_threshold

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
