from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="RiskResponseActionImpact")


@_attrs_define
class RiskResponseActionImpact:
    """RiskResponseActionImpact Entity

    Attributes:
        risk_response_action_object_id (int): The unique ID of the RiskResponseAction.
        risk_threshold_level_object_id (int): The unique ID of the associated Risk Threshold Level.
        create_date (datetime.datetime | Unset): The date this risk response action was created.
        create_user (str | Unset): The name of the user that created the risk response action.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this risk response action was last updated.
        last_update_user (str | Unset): The name of the user that last updated the risk response action.
        project_id (str | Unset): The short name of the associated project.
        project_name (str | Unset): The name of the associated project.
        project_object_id (int | Unset): The unique ID of the associated project.
        risk_id (str | Unset): The unique identifier of the risk or risks assigned to this activity.
        risk_object_id (int | Unset): The unique ID generated by the system.
        risk_response_action_id (str | Unset): The ID of the RiskResponseAction.
        risk_response_action_name (str | Unset): The name of the RiskResponseAction.
        risk_threshold_level_code (str | Unset): The 10 character short name for the threshold level. Must be unique.
        risk_threshold_level_name (str | Unset): The 40 character name for the threshold level. Does not need to be
            unique.
        risk_threshold_name (str | Unset): The name of the associated risk score type.
        risk_threshold_object_id (int | Unset): The unique ID of the associated Risk Threshold.
    """

    risk_response_action_object_id: int
    risk_threshold_level_object_id: int
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    project_id: str | Unset = UNSET
    project_name: str | Unset = UNSET
    project_object_id: int | Unset = UNSET
    risk_id: str | Unset = UNSET
    risk_object_id: int | Unset = UNSET
    risk_response_action_id: str | Unset = UNSET
    risk_response_action_name: str | Unset = UNSET
    risk_threshold_level_code: str | Unset = UNSET
    risk_threshold_level_name: str | Unset = UNSET
    risk_threshold_name: str | Unset = UNSET
    risk_threshold_object_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        risk_response_action_object_id = self.risk_response_action_object_id

        risk_threshold_level_object_id = self.risk_threshold_level_object_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        is_baseline = self.is_baseline

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        project_id = self.project_id

        project_name = self.project_name

        project_object_id = self.project_object_id

        risk_id = self.risk_id

        risk_object_id = self.risk_object_id

        risk_response_action_id = self.risk_response_action_id

        risk_response_action_name = self.risk_response_action_name

        risk_threshold_level_code = self.risk_threshold_level_code

        risk_threshold_level_name = self.risk_threshold_level_name

        risk_threshold_name = self.risk_threshold_name

        risk_threshold_object_id = self.risk_threshold_object_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "RiskResponseActionObjectId": risk_response_action_object_id,
                "RiskThresholdLevelObjectId": risk_threshold_level_object_id,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if project_name is not UNSET:
            field_dict["ProjectName"] = project_name
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if risk_id is not UNSET:
            field_dict["RiskId"] = risk_id
        if risk_object_id is not UNSET:
            field_dict["RiskObjectId"] = risk_object_id
        if risk_response_action_id is not UNSET:
            field_dict["RiskResponseActionId"] = risk_response_action_id
        if risk_response_action_name is not UNSET:
            field_dict["RiskResponseActionName"] = risk_response_action_name
        if risk_threshold_level_code is not UNSET:
            field_dict["RiskThresholdLevelCode"] = risk_threshold_level_code
        if risk_threshold_level_name is not UNSET:
            field_dict["RiskThresholdLevelName"] = risk_threshold_level_name
        if risk_threshold_name is not UNSET:
            field_dict["RiskThresholdName"] = risk_threshold_name
        if risk_threshold_object_id is not UNSET:
            field_dict["RiskThresholdObjectId"] = risk_threshold_object_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        risk_response_action_object_id = d.pop("RiskResponseActionObjectId")

        risk_threshold_level_object_id = d.pop("RiskThresholdLevelObjectId")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        project_name = d.pop("ProjectName", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        risk_id = d.pop("RiskId", UNSET)

        risk_object_id = d.pop("RiskObjectId", UNSET)

        risk_response_action_id = d.pop("RiskResponseActionId", UNSET)

        risk_response_action_name = d.pop("RiskResponseActionName", UNSET)

        risk_threshold_level_code = d.pop("RiskThresholdLevelCode", UNSET)

        risk_threshold_level_name = d.pop("RiskThresholdLevelName", UNSET)

        risk_threshold_name = d.pop("RiskThresholdName", UNSET)

        risk_threshold_object_id = d.pop("RiskThresholdObjectId", UNSET)

        risk_response_action_impact = cls(
            risk_response_action_object_id=risk_response_action_object_id,
            risk_threshold_level_object_id=risk_threshold_level_object_id,
            create_date=create_date,
            create_user=create_user,
            is_baseline=is_baseline,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            project_id=project_id,
            project_name=project_name,
            project_object_id=project_object_id,
            risk_id=risk_id,
            risk_object_id=risk_object_id,
            risk_response_action_id=risk_response_action_id,
            risk_response_action_name=risk_response_action_name,
            risk_threshold_level_code=risk_threshold_level_code,
            risk_threshold_level_name=risk_threshold_level_name,
            risk_threshold_name=risk_threshold_name,
            risk_threshold_object_id=risk_threshold_object_id,
        )

        risk_response_action_impact.additional_properties = d
        return risk_response_action_impact

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
