from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="RiskResponsePlan")


@_attrs_define
class RiskResponsePlan:
    """RiskResponsePlan Entity

    Attributes:
        id (str): The ID of the risk response plan. This must be unique within the assigned risk.
        risk_object_id (int): The unique ID of the associated risk.
        actual_cost (float | Unset): The actual cost.
        create_date (datetime.datetime | Unset): The date this risk response plan was created.
        create_user (str | Unset): The name of the user that created the risk response plan.
        finish_date (datetime.datetime | Unset): The finish date of the risk response action. If an activity is
            assigned, the risk response action uses the activity finish date.
        is_active (bool | Unset): The indication of whether the response plan is currently active for the associated
            risk. Only one response plan can be active at a given time for a risk.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline.
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this risk response plan was last updated.
        last_update_user (str | Unset): The name of the user that last updated the risk response plan.
        name (str | Unset): The name of the risk response plan.
        object_id (int | Unset): The unique ID generated by the system.
        planned_cost (float | Unset): The planned cost.
        planned_finish_date (datetime.datetime | Unset): The planned finish date.
        planned_start_date (datetime.datetime | Unset): The planned start date.
        project_id (str | Unset): The short name of the associated project.
        project_name (str | Unset): The name of the associated project.
        project_object_id (int | Unset): The unique ID of the associated project.
        remaining_cost (float | Unset): The remaining cost associated with the risk response action.
        response_type (str | Unset): The risk response plan type. If the risk is a threat, the valid types are 'Avoid',
            'Transfer', 'Reduce', and 'Accept'. If the risk is a opportunity, the valid types are 'Exploit', 'Facilitate',
            'Enhance', and 'Reject'.
        risk_id (str | Unset): The ID of the risk.
        risk_name (str | Unset): The name of the risk.
        score (int | Unset): The risk score from the numeric PID after all response actions of the response plan have
            been completed. The post response plan score is set from the response action with the latest finish date and the
            lowest score when more than one response action has the same date.
        score_color (str | Unset): The color of the tolerance threshold for the score value.
        score_text (str | Unset): The risk score from the alphanumeric PID after all response actions of the response
            plan have been completed. The post response plan score is set from the response action with the latest finish
            date and the lowest score when more than one response action has the same date.
        start_date (datetime.datetime | Unset): The start date of the risk response action. If an activity is assigned,
            the risk response action uses the activity start date.
    """

    id: str
    risk_object_id: int
    actual_cost: float | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    finish_date: datetime.datetime | Unset = UNSET
    is_active: bool | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    name: str | Unset = UNSET
    object_id: int | Unset = UNSET
    planned_cost: float | Unset = UNSET
    planned_finish_date: datetime.datetime | Unset = UNSET
    planned_start_date: datetime.datetime | Unset = UNSET
    project_id: str | Unset = UNSET
    project_name: str | Unset = UNSET
    project_object_id: int | Unset = UNSET
    remaining_cost: float | Unset = UNSET
    response_type: str | Unset = UNSET
    risk_id: str | Unset = UNSET
    risk_name: str | Unset = UNSET
    score: int | Unset = UNSET
    score_color: str | Unset = UNSET
    score_text: str | Unset = UNSET
    start_date: datetime.datetime | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        risk_object_id = self.risk_object_id

        actual_cost = self.actual_cost

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        finish_date: str | Unset = UNSET
        if not isinstance(self.finish_date, Unset):
            finish_date = self.finish_date.isoformat()

        is_active = self.is_active

        is_baseline = self.is_baseline

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        name = self.name

        object_id = self.object_id

        planned_cost = self.planned_cost

        planned_finish_date: str | Unset = UNSET
        if not isinstance(self.planned_finish_date, Unset):
            planned_finish_date = self.planned_finish_date.isoformat()

        planned_start_date: str | Unset = UNSET
        if not isinstance(self.planned_start_date, Unset):
            planned_start_date = self.planned_start_date.isoformat()

        project_id = self.project_id

        project_name = self.project_name

        project_object_id = self.project_object_id

        remaining_cost = self.remaining_cost

        response_type = self.response_type

        risk_id = self.risk_id

        risk_name = self.risk_name

        score = self.score

        score_color = self.score_color

        score_text = self.score_text

        start_date: str | Unset = UNSET
        if not isinstance(self.start_date, Unset):
            start_date = self.start_date.isoformat()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Id": id,
                "RiskObjectId": risk_object_id,
            }
        )
        if actual_cost is not UNSET:
            field_dict["ActualCost"] = actual_cost
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if finish_date is not UNSET:
            field_dict["FinishDate"] = finish_date
        if is_active is not UNSET:
            field_dict["IsActive"] = is_active
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if name is not UNSET:
            field_dict["Name"] = name
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if planned_cost is not UNSET:
            field_dict["PlannedCost"] = planned_cost
        if planned_finish_date is not UNSET:
            field_dict["PlannedFinishDate"] = planned_finish_date
        if planned_start_date is not UNSET:
            field_dict["PlannedStartDate"] = planned_start_date
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if project_name is not UNSET:
            field_dict["ProjectName"] = project_name
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if remaining_cost is not UNSET:
            field_dict["RemainingCost"] = remaining_cost
        if response_type is not UNSET:
            field_dict["ResponseType"] = response_type
        if risk_id is not UNSET:
            field_dict["RiskId"] = risk_id
        if risk_name is not UNSET:
            field_dict["RiskName"] = risk_name
        if score is not UNSET:
            field_dict["Score"] = score
        if score_color is not UNSET:
            field_dict["ScoreColor"] = score_color
        if score_text is not UNSET:
            field_dict["ScoreText"] = score_text
        if start_date is not UNSET:
            field_dict["StartDate"] = start_date

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("Id")

        risk_object_id = d.pop("RiskObjectId")

        actual_cost = d.pop("ActualCost", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        _finish_date = d.pop("FinishDate", UNSET)
        finish_date: datetime.datetime | Unset
        if isinstance(_finish_date, Unset):
            finish_date = UNSET
        else:
            finish_date = isoparse(_finish_date)

        is_active = d.pop("IsActive", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        name = d.pop("Name", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        planned_cost = d.pop("PlannedCost", UNSET)

        _planned_finish_date = d.pop("PlannedFinishDate", UNSET)
        planned_finish_date: datetime.datetime | Unset
        if isinstance(_planned_finish_date, Unset):
            planned_finish_date = UNSET
        else:
            planned_finish_date = isoparse(_planned_finish_date)

        _planned_start_date = d.pop("PlannedStartDate", UNSET)
        planned_start_date: datetime.datetime | Unset
        if isinstance(_planned_start_date, Unset):
            planned_start_date = UNSET
        else:
            planned_start_date = isoparse(_planned_start_date)

        project_id = d.pop("ProjectId", UNSET)

        project_name = d.pop("ProjectName", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        remaining_cost = d.pop("RemainingCost", UNSET)

        response_type = d.pop("ResponseType", UNSET)

        risk_id = d.pop("RiskId", UNSET)

        risk_name = d.pop("RiskName", UNSET)

        score = d.pop("Score", UNSET)

        score_color = d.pop("ScoreColor", UNSET)

        score_text = d.pop("ScoreText", UNSET)

        _start_date = d.pop("StartDate", UNSET)
        start_date: datetime.datetime | Unset
        if isinstance(_start_date, Unset):
            start_date = UNSET
        else:
            start_date = isoparse(_start_date)

        risk_response_plan = cls(
            id=id,
            risk_object_id=risk_object_id,
            actual_cost=actual_cost,
            create_date=create_date,
            create_user=create_user,
            finish_date=finish_date,
            is_active=is_active,
            is_baseline=is_baseline,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            name=name,
            object_id=object_id,
            planned_cost=planned_cost,
            planned_finish_date=planned_finish_date,
            planned_start_date=planned_start_date,
            project_id=project_id,
            project_name=project_name,
            project_object_id=project_object_id,
            remaining_cost=remaining_cost,
            response_type=response_type,
            risk_id=risk_id,
            risk_name=risk_name,
            score=score,
            score_color=score_color,
            score_text=score_text,
            start_date=start_date,
        )

        risk_response_plan.additional_properties = d
        return risk_response_plan

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
