from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="Risk")


@_attrs_define
class Risk:
    """Risk Entity

    Attributes:
        id (str): The ID of the Risk. Must be unique within a project.
        project_object_id (int): The unique ID of the associated project.
        cause (str | Unset): The description of the cause of the Risk.
        cost_threshold_id (int | Unset):
        create_date (datetime.datetime | Unset): The date this risk was created.
        create_user (str | Unset): The name of the user that created the risk.
        description (str | Unset): The description of the Risk.
        effect (str | Unset): The description of the risks effect on the project.
        exposure (float | Unset): The calculated exposure value for the risk.
        exposure_finish_date (datetime.datetime | Unset): The calculated date the exposure finishes for the risk.
        exposure_start_date (datetime.datetime | Unset): The calculated date the exposure starts for the risk.
        identified_by_resource_id (str | Unset): The short code of the resource that identified the risk.
        identified_by_resource_name (str | Unset): The name of the resource that identified the risk.
        identified_by_resource_object_id (int | Unset): The unique ID of the resource that identified the risk.
        identified_date (datetime.datetime | Unset): The date this risk was identified.
        impact_threshold_values (int | Unset):
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline.
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this risk was last updated.
        last_update_user (str | Unset): The name of the user that last updated the risk.
        name (str | Unset): The name of the Risk. Does not need to be unique.
        note (str | Unset): The comments associated with the Risk.
        object_id (int | Unset): The unique ID generated by the system.
        probability_threshold_id (int | Unset):
        project_id (str | Unset): The short name of the associated project.
        project_name (str | Unset): The name of the associated project.
        resource_id (str | Unset): The ID of the resource who owns the Risk. The owner of the Risk is responsible for
            resolving the Risk.
        resource_name (str | Unset): The name of the resource who owns the Risk. The owner of the Risk is responsible
            for resolving the Risk.
        resource_object_id (int | Unset): The unique ID of the associated resource.
        response_total_cost (float | Unset): The total estimated cost for the risk. If the risk has an associated
            response plan, the cost is calculated from the risk response actions for the response plan. Not available if
            user does not have View Project Costs-Financial privilege.
        risk_category_name (str | Unset): The name of the category to which the Risk is assigned. e.g. Weather, Health,
            Legal etc. A Risk can only be associated with a single category.
        risk_category_object_id (int | Unset): The unique ID of the category to which the Risk is assigned. e.g.
            Weather, Health, Legal etc. A Risk can only be associated with a single category.
        schedule_threshold_id (int | Unset):
        score (int | Unset): The calculated score value of the impact values assigned to the risk.
        score_color (str | Unset): The color of the tolerance threshold for the score value.
        score_text (str | Unset): The calculated score text value of the impact values assigned to the risk.
        status (str | Unset): The current status of the Risk. Valid values are 'Proposed', 'Open', 'Rejected',
            'Managed', and 'Impacted'.
        type_ (str | Unset): The type of the risk. Valid values are 'Threat' and 'Opportunity'.
    """

    id: str
    project_object_id: int
    cause: str | Unset = UNSET
    cost_threshold_id: int | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    description: str | Unset = UNSET
    effect: str | Unset = UNSET
    exposure: float | Unset = UNSET
    exposure_finish_date: datetime.datetime | Unset = UNSET
    exposure_start_date: datetime.datetime | Unset = UNSET
    identified_by_resource_id: str | Unset = UNSET
    identified_by_resource_name: str | Unset = UNSET
    identified_by_resource_object_id: int | Unset = UNSET
    identified_date: datetime.datetime | Unset = UNSET
    impact_threshold_values: int | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    name: str | Unset = UNSET
    note: str | Unset = UNSET
    object_id: int | Unset = UNSET
    probability_threshold_id: int | Unset = UNSET
    project_id: str | Unset = UNSET
    project_name: str | Unset = UNSET
    resource_id: str | Unset = UNSET
    resource_name: str | Unset = UNSET
    resource_object_id: int | Unset = UNSET
    response_total_cost: float | Unset = UNSET
    risk_category_name: str | Unset = UNSET
    risk_category_object_id: int | Unset = UNSET
    schedule_threshold_id: int | Unset = UNSET
    score: int | Unset = UNSET
    score_color: str | Unset = UNSET
    score_text: str | Unset = UNSET
    status: str | Unset = UNSET
    type_: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        project_object_id = self.project_object_id

        cause = self.cause

        cost_threshold_id = self.cost_threshold_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        description = self.description

        effect = self.effect

        exposure = self.exposure

        exposure_finish_date: str | Unset = UNSET
        if not isinstance(self.exposure_finish_date, Unset):
            exposure_finish_date = self.exposure_finish_date.isoformat()

        exposure_start_date: str | Unset = UNSET
        if not isinstance(self.exposure_start_date, Unset):
            exposure_start_date = self.exposure_start_date.isoformat()

        identified_by_resource_id = self.identified_by_resource_id

        identified_by_resource_name = self.identified_by_resource_name

        identified_by_resource_object_id = self.identified_by_resource_object_id

        identified_date: str | Unset = UNSET
        if not isinstance(self.identified_date, Unset):
            identified_date = self.identified_date.isoformat()

        impact_threshold_values = self.impact_threshold_values

        is_baseline = self.is_baseline

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        name = self.name

        note = self.note

        object_id = self.object_id

        probability_threshold_id = self.probability_threshold_id

        project_id = self.project_id

        project_name = self.project_name

        resource_id = self.resource_id

        resource_name = self.resource_name

        resource_object_id = self.resource_object_id

        response_total_cost = self.response_total_cost

        risk_category_name = self.risk_category_name

        risk_category_object_id = self.risk_category_object_id

        schedule_threshold_id = self.schedule_threshold_id

        score = self.score

        score_color = self.score_color

        score_text = self.score_text

        status = self.status

        type_ = self.type_

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Id": id,
                "ProjectObjectId": project_object_id,
            }
        )
        if cause is not UNSET:
            field_dict["Cause"] = cause
        if cost_threshold_id is not UNSET:
            field_dict["CostThresholdId"] = cost_threshold_id
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if description is not UNSET:
            field_dict["Description"] = description
        if effect is not UNSET:
            field_dict["Effect"] = effect
        if exposure is not UNSET:
            field_dict["Exposure"] = exposure
        if exposure_finish_date is not UNSET:
            field_dict["ExposureFinishDate"] = exposure_finish_date
        if exposure_start_date is not UNSET:
            field_dict["ExposureStartDate"] = exposure_start_date
        if identified_by_resource_id is not UNSET:
            field_dict["IdentifiedByResourceId"] = identified_by_resource_id
        if identified_by_resource_name is not UNSET:
            field_dict["IdentifiedByResourceName"] = identified_by_resource_name
        if identified_by_resource_object_id is not UNSET:
            field_dict["IdentifiedByResourceObjectId"] = identified_by_resource_object_id
        if identified_date is not UNSET:
            field_dict["IdentifiedDate"] = identified_date
        if impact_threshold_values is not UNSET:
            field_dict["ImpactThresholdValues"] = impact_threshold_values
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if name is not UNSET:
            field_dict["Name"] = name
        if note is not UNSET:
            field_dict["Note"] = note
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if probability_threshold_id is not UNSET:
            field_dict["ProbabilityThresholdId"] = probability_threshold_id
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if project_name is not UNSET:
            field_dict["ProjectName"] = project_name
        if resource_id is not UNSET:
            field_dict["ResourceId"] = resource_id
        if resource_name is not UNSET:
            field_dict["ResourceName"] = resource_name
        if resource_object_id is not UNSET:
            field_dict["ResourceObjectId"] = resource_object_id
        if response_total_cost is not UNSET:
            field_dict["ResponseTotalCost"] = response_total_cost
        if risk_category_name is not UNSET:
            field_dict["RiskCategoryName"] = risk_category_name
        if risk_category_object_id is not UNSET:
            field_dict["RiskCategoryObjectId"] = risk_category_object_id
        if schedule_threshold_id is not UNSET:
            field_dict["ScheduleThresholdId"] = schedule_threshold_id
        if score is not UNSET:
            field_dict["Score"] = score
        if score_color is not UNSET:
            field_dict["ScoreColor"] = score_color
        if score_text is not UNSET:
            field_dict["ScoreText"] = score_text
        if status is not UNSET:
            field_dict["Status"] = status
        if type_ is not UNSET:
            field_dict["Type"] = type_

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("Id")

        project_object_id = d.pop("ProjectObjectId")

        cause = d.pop("Cause", UNSET)

        cost_threshold_id = d.pop("CostThresholdId", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        description = d.pop("Description", UNSET)

        effect = d.pop("Effect", UNSET)

        exposure = d.pop("Exposure", UNSET)

        _exposure_finish_date = d.pop("ExposureFinishDate", UNSET)
        exposure_finish_date: datetime.datetime | Unset
        if isinstance(_exposure_finish_date, Unset):
            exposure_finish_date = UNSET
        else:
            exposure_finish_date = isoparse(_exposure_finish_date)

        _exposure_start_date = d.pop("ExposureStartDate", UNSET)
        exposure_start_date: datetime.datetime | Unset
        if isinstance(_exposure_start_date, Unset):
            exposure_start_date = UNSET
        else:
            exposure_start_date = isoparse(_exposure_start_date)

        identified_by_resource_id = d.pop("IdentifiedByResourceId", UNSET)

        identified_by_resource_name = d.pop("IdentifiedByResourceName", UNSET)

        identified_by_resource_object_id = d.pop("IdentifiedByResourceObjectId", UNSET)

        _identified_date = d.pop("IdentifiedDate", UNSET)
        identified_date: datetime.datetime | Unset
        if isinstance(_identified_date, Unset):
            identified_date = UNSET
        else:
            identified_date = isoparse(_identified_date)

        impact_threshold_values = d.pop("ImpactThresholdValues", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        name = d.pop("Name", UNSET)

        note = d.pop("Note", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        probability_threshold_id = d.pop("ProbabilityThresholdId", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        project_name = d.pop("ProjectName", UNSET)

        resource_id = d.pop("ResourceId", UNSET)

        resource_name = d.pop("ResourceName", UNSET)

        resource_object_id = d.pop("ResourceObjectId", UNSET)

        response_total_cost = d.pop("ResponseTotalCost", UNSET)

        risk_category_name = d.pop("RiskCategoryName", UNSET)

        risk_category_object_id = d.pop("RiskCategoryObjectId", UNSET)

        schedule_threshold_id = d.pop("ScheduleThresholdId", UNSET)

        score = d.pop("Score", UNSET)

        score_color = d.pop("ScoreColor", UNSET)

        score_text = d.pop("ScoreText", UNSET)

        status = d.pop("Status", UNSET)

        type_ = d.pop("Type", UNSET)

        risk = cls(
            id=id,
            project_object_id=project_object_id,
            cause=cause,
            cost_threshold_id=cost_threshold_id,
            create_date=create_date,
            create_user=create_user,
            description=description,
            effect=effect,
            exposure=exposure,
            exposure_finish_date=exposure_finish_date,
            exposure_start_date=exposure_start_date,
            identified_by_resource_id=identified_by_resource_id,
            identified_by_resource_name=identified_by_resource_name,
            identified_by_resource_object_id=identified_by_resource_object_id,
            identified_date=identified_date,
            impact_threshold_values=impact_threshold_values,
            is_baseline=is_baseline,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            name=name,
            note=note,
            object_id=object_id,
            probability_threshold_id=probability_threshold_id,
            project_id=project_id,
            project_name=project_name,
            resource_id=resource_id,
            resource_name=resource_name,
            resource_object_id=resource_object_id,
            response_total_cost=response_total_cost,
            risk_category_name=risk_category_name,
            risk_category_object_id=risk_category_object_id,
            schedule_threshold_id=schedule_threshold_id,
            score=score,
            score_color=score_color,
            score_text=score_text,
            status=status,
            type_=type_,
        )

        risk.additional_properties = d
        return risk

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
