from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="RiskThresholdLevel")


@_attrs_define
class RiskThresholdLevel:
    """RiskThresholdLevel Entity

    Attributes:
        code (str): The 10 character code for the threshold level. Must be unique.
        risk_threshold_object_id (int): The unique ID of the associated Risk Threshold.
        color (str | Unset): The Hex representation for the color e.g. 0xFFFFFF.
        cost_range (float | Unset): The cost range of the threshold level.
        create_date (datetime.datetime | Unset): The date this threshold level was created.
        create_user (str | Unset): The name of the user that created the threshold level.
        last_update_date (datetime.datetime | Unset): The date this threshold level was last updated.
        last_update_user (str | Unset): The name of the user that last updated the threshold level.
        level (int | Unset): The valid values are between 0 and 9. Defines a level for the Risk Threshold.
        name (str | Unset): The 40 character name for the threshold level. Does not need to be unique.
        object_id (int | Unset): The unique ID generated by the system.
        probability_range (float | Unset): The probability range of the threshold level.
        range_ (str | Unset): The user defined range.
        risk_threshold_name (str | Unset): The name of the associated risk score type.
        schedule_range (float | Unset): The schedule range of the threshold level.
        threshold_type (str | Unset): The type of Risk Threshold. Valid types are 'Probability', 'Tolerance',
            'Schedule', 'Cost', 'Relative Schedule', 'Relative Cost' and 'User Defined'.
        tolerance_range (int | Unset): The tolerance range of the threshold level.
    """

    code: str
    risk_threshold_object_id: int
    color: str | Unset = UNSET
    cost_range: float | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    level: int | Unset = UNSET
    name: str | Unset = UNSET
    object_id: int | Unset = UNSET
    probability_range: float | Unset = UNSET
    range_: str | Unset = UNSET
    risk_threshold_name: str | Unset = UNSET
    schedule_range: float | Unset = UNSET
    threshold_type: str | Unset = UNSET
    tolerance_range: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        code = self.code

        risk_threshold_object_id = self.risk_threshold_object_id

        color = self.color

        cost_range = self.cost_range

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        level = self.level

        name = self.name

        object_id = self.object_id

        probability_range = self.probability_range

        range_ = self.range_

        risk_threshold_name = self.risk_threshold_name

        schedule_range = self.schedule_range

        threshold_type = self.threshold_type

        tolerance_range = self.tolerance_range

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Code": code,
                "RiskThresholdObjectId": risk_threshold_object_id,
            }
        )
        if color is not UNSET:
            field_dict["Color"] = color
        if cost_range is not UNSET:
            field_dict["CostRange"] = cost_range
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if level is not UNSET:
            field_dict["Level"] = level
        if name is not UNSET:
            field_dict["Name"] = name
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if probability_range is not UNSET:
            field_dict["ProbabilityRange"] = probability_range
        if range_ is not UNSET:
            field_dict["Range"] = range_
        if risk_threshold_name is not UNSET:
            field_dict["RiskThresholdName"] = risk_threshold_name
        if schedule_range is not UNSET:
            field_dict["ScheduleRange"] = schedule_range
        if threshold_type is not UNSET:
            field_dict["ThresholdType"] = threshold_type
        if tolerance_range is not UNSET:
            field_dict["ToleranceRange"] = tolerance_range

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        code = d.pop("Code")

        risk_threshold_object_id = d.pop("RiskThresholdObjectId")

        color = d.pop("Color", UNSET)

        cost_range = d.pop("CostRange", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        level = d.pop("Level", UNSET)

        name = d.pop("Name", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        probability_range = d.pop("ProbabilityRange", UNSET)

        range_ = d.pop("Range", UNSET)

        risk_threshold_name = d.pop("RiskThresholdName", UNSET)

        schedule_range = d.pop("ScheduleRange", UNSET)

        threshold_type = d.pop("ThresholdType", UNSET)

        tolerance_range = d.pop("ToleranceRange", UNSET)

        risk_threshold_level = cls(
            code=code,
            risk_threshold_object_id=risk_threshold_object_id,
            color=color,
            cost_range=cost_range,
            create_date=create_date,
            create_user=create_user,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            level=level,
            name=name,
            object_id=object_id,
            probability_range=probability_range,
            range_=range_,
            risk_threshold_name=risk_threshold_name,
            schedule_range=schedule_range,
            threshold_type=threshold_type,
            tolerance_range=tolerance_range,
        )

        risk_threshold_level.additional_properties = d
        return risk_threshold_level

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
