from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="RoleCode")


@_attrs_define
class RoleCode:
    """RoleCode Entity

    Attributes:
        create_date (datetime.datetime | Unset): The date this resource code was created.
        create_user (str | Unset): The name of the user that created this resource code.
        code_type_name (float | Unset): The name of the parent code type for this code.
        code_type_object_id (int | Unset): The unique ID of the parent resource code type.
        last_update_date (datetime.datetime | Unset): The date this resource code was last updated.
        last_update_user (str | Unset): The name of the user that last updated this resource code.
        object_id (int | Unset): The unique ID generated by the system.
        code_value (str | Unset): The value of the resource code.
        description (str | Unset): The description of the resource code.
        parent_object_id (int | Unset): The unique ID of the parent resource code of this resource code in the
            hierarchy.
        sequence_number (int | Unset): The sequence number for sorting.
    """

    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    code_type_name: float | Unset = UNSET
    code_type_object_id: int | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    code_value: str | Unset = UNSET
    description: str | Unset = UNSET
    parent_object_id: int | Unset = UNSET
    sequence_number: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        code_type_name = self.code_type_name

        code_type_object_id = self.code_type_object_id

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        code_value = self.code_value

        description = self.description

        parent_object_id = self.parent_object_id

        sequence_number = self.sequence_number

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if code_type_name is not UNSET:
            field_dict["CodeTypeName"] = code_type_name
        if code_type_object_id is not UNSET:
            field_dict["CodeTypeObjectId"] = code_type_object_id
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if code_value is not UNSET:
            field_dict["CodeValue"] = code_value
        if description is not UNSET:
            field_dict["Description"] = description
        if parent_object_id is not UNSET:
            field_dict["ParentObjectId"] = parent_object_id
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        code_type_name = d.pop("CodeTypeName", UNSET)

        code_type_object_id = d.pop("CodeTypeObjectId", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        code_value = d.pop("CodeValue", UNSET)

        description = d.pop("Description", UNSET)

        parent_object_id = d.pop("ParentObjectId", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        role_code = cls(
            create_date=create_date,
            create_user=create_user,
            code_type_name=code_type_name,
            code_type_object_id=code_type_object_id,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            code_value=code_value,
            description=description,
            parent_object_id=parent_object_id,
            sequence_number=sequence_number,
        )

        role_code.additional_properties = d
        return role_code

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
