from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="TimesheetAudit")


@_attrs_define
class TimesheetAudit:
    """TimesheetAudit Entity

    Attributes:
        approver_user_name (str | Unset): The user name of the approver.
        approver_user_object_id (int | Unset): The unique user ID of the approver.
        audit_date (datetime.datetime | Unset): The date this timesheet audit was created.
        object_id (int | Unset): The unique ID generated by the system.
        overhead_hours (float | Unset): The total overhead hours for the timesheet.
        overhead_overtime_hours (float | Unset): The total overhead overtime hours for the timesheet.
        pending_overhead_hours (float | Unset): The total pending overhead hours for the timesheet.
        pending_overhead_overtime_hours (float | Unset): The total pending overhead overtime hours for the timesheet.
        pending_project_hours (float | Unset): The total pending project hours for the timesheet.
        pending_project_overtime_hours (float | Unset): The total pending project overtime hours for the timesheet
        project_hours (float | Unset): The total project hours for the timesheet.
        project_id (str | Unset): The short code that uniquely identifies the project.
        project_object_id (int | Unset): The unique ID of the associated project.
        project_overtime_hours (float | Unset): The total project overtime hours for the timesheet.
        resource_id (str | Unset): The short code that uniquely identifies the resource.
        resource_name (str | Unset): The name of the resource.
        resource_object_id (int | Unset): The unique ID of the associated resource.
        timesheet_activity_status (str | Unset): The status of the timesheet activity, the value of which will depend on
            who approved or rejected it. Valid values are 'Submitted', 'Approved', 'Resource Manager Approved', 'Project
            Manager Approved', and 'Rejected'.
        timesheet_approving_as (str | Unset): The role of the timesheet approver. Valid values are 'Project Manager',
            'Resource Manager', 'Project Manager Delegate', and 'Resource Manager Delegate'.
        timesheet_period_end_date (datetime.datetime | Unset): The timesheet period end date.
        timesheet_period_object_id (int | Unset): The unique ID of the timesheet period.
        timesheet_period_start_date (datetime.datetime | Unset): The timesheet period start date.
        timesheet_status (str | Unset): The status of the timesheet. Valid values are 'Submitted', 'Approved', 'Resource
            Manager Approved', 'Project Manager Approved', and 'Rejected'.
    """

    approver_user_name: str | Unset = UNSET
    approver_user_object_id: int | Unset = UNSET
    audit_date: datetime.datetime | Unset = UNSET
    object_id: int | Unset = UNSET
    overhead_hours: float | Unset = UNSET
    overhead_overtime_hours: float | Unset = UNSET
    pending_overhead_hours: float | Unset = UNSET
    pending_overhead_overtime_hours: float | Unset = UNSET
    pending_project_hours: float | Unset = UNSET
    pending_project_overtime_hours: float | Unset = UNSET
    project_hours: float | Unset = UNSET
    project_id: str | Unset = UNSET
    project_object_id: int | Unset = UNSET
    project_overtime_hours: float | Unset = UNSET
    resource_id: str | Unset = UNSET
    resource_name: str | Unset = UNSET
    resource_object_id: int | Unset = UNSET
    timesheet_activity_status: str | Unset = UNSET
    timesheet_approving_as: str | Unset = UNSET
    timesheet_period_end_date: datetime.datetime | Unset = UNSET
    timesheet_period_object_id: int | Unset = UNSET
    timesheet_period_start_date: datetime.datetime | Unset = UNSET
    timesheet_status: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        approver_user_name = self.approver_user_name

        approver_user_object_id = self.approver_user_object_id

        audit_date: str | Unset = UNSET
        if not isinstance(self.audit_date, Unset):
            audit_date = self.audit_date.isoformat()

        object_id = self.object_id

        overhead_hours = self.overhead_hours

        overhead_overtime_hours = self.overhead_overtime_hours

        pending_overhead_hours = self.pending_overhead_hours

        pending_overhead_overtime_hours = self.pending_overhead_overtime_hours

        pending_project_hours = self.pending_project_hours

        pending_project_overtime_hours = self.pending_project_overtime_hours

        project_hours = self.project_hours

        project_id = self.project_id

        project_object_id = self.project_object_id

        project_overtime_hours = self.project_overtime_hours

        resource_id = self.resource_id

        resource_name = self.resource_name

        resource_object_id = self.resource_object_id

        timesheet_activity_status = self.timesheet_activity_status

        timesheet_approving_as = self.timesheet_approving_as

        timesheet_period_end_date: str | Unset = UNSET
        if not isinstance(self.timesheet_period_end_date, Unset):
            timesheet_period_end_date = self.timesheet_period_end_date.isoformat()

        timesheet_period_object_id = self.timesheet_period_object_id

        timesheet_period_start_date: str | Unset = UNSET
        if not isinstance(self.timesheet_period_start_date, Unset):
            timesheet_period_start_date = self.timesheet_period_start_date.isoformat()

        timesheet_status = self.timesheet_status

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if approver_user_name is not UNSET:
            field_dict["ApproverUserName"] = approver_user_name
        if approver_user_object_id is not UNSET:
            field_dict["ApproverUserObjectId"] = approver_user_object_id
        if audit_date is not UNSET:
            field_dict["AuditDate"] = audit_date
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if overhead_hours is not UNSET:
            field_dict["OverheadHours"] = overhead_hours
        if overhead_overtime_hours is not UNSET:
            field_dict["OverheadOvertimeHours"] = overhead_overtime_hours
        if pending_overhead_hours is not UNSET:
            field_dict["PendingOverheadHours"] = pending_overhead_hours
        if pending_overhead_overtime_hours is not UNSET:
            field_dict["PendingOverheadOvertimeHours"] = pending_overhead_overtime_hours
        if pending_project_hours is not UNSET:
            field_dict["PendingProjectHours"] = pending_project_hours
        if pending_project_overtime_hours is not UNSET:
            field_dict["PendingProjectOvertimeHours"] = pending_project_overtime_hours
        if project_hours is not UNSET:
            field_dict["ProjectHours"] = project_hours
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id
        if project_overtime_hours is not UNSET:
            field_dict["ProjectOvertimeHours"] = project_overtime_hours
        if resource_id is not UNSET:
            field_dict["ResourceId"] = resource_id
        if resource_name is not UNSET:
            field_dict["ResourceName"] = resource_name
        if resource_object_id is not UNSET:
            field_dict["ResourceObjectId"] = resource_object_id
        if timesheet_activity_status is not UNSET:
            field_dict["TimesheetActivityStatus"] = timesheet_activity_status
        if timesheet_approving_as is not UNSET:
            field_dict["TimesheetApprovingAs"] = timesheet_approving_as
        if timesheet_period_end_date is not UNSET:
            field_dict["TimesheetPeriodEndDate"] = timesheet_period_end_date
        if timesheet_period_object_id is not UNSET:
            field_dict["TimesheetPeriodObjectId"] = timesheet_period_object_id
        if timesheet_period_start_date is not UNSET:
            field_dict["TimesheetPeriodStartDate"] = timesheet_period_start_date
        if timesheet_status is not UNSET:
            field_dict["TimesheetStatus"] = timesheet_status

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        approver_user_name = d.pop("ApproverUserName", UNSET)

        approver_user_object_id = d.pop("ApproverUserObjectId", UNSET)

        _audit_date = d.pop("AuditDate", UNSET)
        audit_date: datetime.datetime | Unset
        if isinstance(_audit_date, Unset):
            audit_date = UNSET
        else:
            audit_date = isoparse(_audit_date)

        object_id = d.pop("ObjectId", UNSET)

        overhead_hours = d.pop("OverheadHours", UNSET)

        overhead_overtime_hours = d.pop("OverheadOvertimeHours", UNSET)

        pending_overhead_hours = d.pop("PendingOverheadHours", UNSET)

        pending_overhead_overtime_hours = d.pop("PendingOverheadOvertimeHours", UNSET)

        pending_project_hours = d.pop("PendingProjectHours", UNSET)

        pending_project_overtime_hours = d.pop("PendingProjectOvertimeHours", UNSET)

        project_hours = d.pop("ProjectHours", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        project_overtime_hours = d.pop("ProjectOvertimeHours", UNSET)

        resource_id = d.pop("ResourceId", UNSET)

        resource_name = d.pop("ResourceName", UNSET)

        resource_object_id = d.pop("ResourceObjectId", UNSET)

        timesheet_activity_status = d.pop("TimesheetActivityStatus", UNSET)

        timesheet_approving_as = d.pop("TimesheetApprovingAs", UNSET)

        _timesheet_period_end_date = d.pop("TimesheetPeriodEndDate", UNSET)
        timesheet_period_end_date: datetime.datetime | Unset
        if isinstance(_timesheet_period_end_date, Unset):
            timesheet_period_end_date = UNSET
        else:
            timesheet_period_end_date = isoparse(_timesheet_period_end_date)

        timesheet_period_object_id = d.pop("TimesheetPeriodObjectId", UNSET)

        _timesheet_period_start_date = d.pop("TimesheetPeriodStartDate", UNSET)
        timesheet_period_start_date: datetime.datetime | Unset
        if isinstance(_timesheet_period_start_date, Unset):
            timesheet_period_start_date = UNSET
        else:
            timesheet_period_start_date = isoparse(_timesheet_period_start_date)

        timesheet_status = d.pop("TimesheetStatus", UNSET)

        timesheet_audit = cls(
            approver_user_name=approver_user_name,
            approver_user_object_id=approver_user_object_id,
            audit_date=audit_date,
            object_id=object_id,
            overhead_hours=overhead_hours,
            overhead_overtime_hours=overhead_overtime_hours,
            pending_overhead_hours=pending_overhead_hours,
            pending_overhead_overtime_hours=pending_overhead_overtime_hours,
            pending_project_hours=pending_project_hours,
            pending_project_overtime_hours=pending_project_overtime_hours,
            project_hours=project_hours,
            project_id=project_id,
            project_object_id=project_object_id,
            project_overtime_hours=project_overtime_hours,
            resource_id=resource_id,
            resource_name=resource_name,
            resource_object_id=resource_object_id,
            timesheet_activity_status=timesheet_activity_status,
            timesheet_approving_as=timesheet_approving_as,
            timesheet_period_end_date=timesheet_period_end_date,
            timesheet_period_object_id=timesheet_period_object_id,
            timesheet_period_start_date=timesheet_period_start_date,
            timesheet_status=timesheet_status,
        )

        timesheet_audit.additional_properties = d
        return timesheet_audit

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
