from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="TimesheetDelegate")


@_attrs_define
class TimesheetDelegate:
    """TimesheetDelegate Entity

    Attributes:
        active_flag (bool | Unset): The flag indicating whether this delegate is active.
        approver_user_name (str | Unset): The approver user's login name.
        approver_user_object_id (int | Unset): The unique ID of the approver user.
        create_date (datetime.datetime | Unset): The date this timesheet delegate was created.
        create_user (str | Unset): The name of the user that created this timesheet delegate.
        delegate_user_email_address (str | Unset): The delegate user's email address.
        delegate_user_name (str | Unset): The delegate user's login name.
        delegate_user_object_id (int | Unset): The unique ID of the delegate user.
        last_update_date (datetime.datetime | Unset): The date this timesheet delegate was last updated.
        last_update_user (str | Unset): The name of the user that last updated this timesheet delegate.
        object_id (int | Unset): The unique ID generated by the system.
        project_object_id (int | Unset): The unique ID of the associated project.
    """

    active_flag: bool | Unset = UNSET
    approver_user_name: str | Unset = UNSET
    approver_user_object_id: int | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    delegate_user_email_address: str | Unset = UNSET
    delegate_user_name: str | Unset = UNSET
    delegate_user_object_id: int | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    project_object_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        active_flag = self.active_flag

        approver_user_name = self.approver_user_name

        approver_user_object_id = self.approver_user_object_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        delegate_user_email_address = self.delegate_user_email_address

        delegate_user_name = self.delegate_user_name

        delegate_user_object_id = self.delegate_user_object_id

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        project_object_id = self.project_object_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if active_flag is not UNSET:
            field_dict["ActiveFlag"] = active_flag
        if approver_user_name is not UNSET:
            field_dict["ApproverUserName"] = approver_user_name
        if approver_user_object_id is not UNSET:
            field_dict["ApproverUserObjectId"] = approver_user_object_id
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if delegate_user_email_address is not UNSET:
            field_dict["DelegateUserEmailAddress"] = delegate_user_email_address
        if delegate_user_name is not UNSET:
            field_dict["DelegateUserName"] = delegate_user_name
        if delegate_user_object_id is not UNSET:
            field_dict["DelegateUserObjectId"] = delegate_user_object_id
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if project_object_id is not UNSET:
            field_dict["ProjectObjectId"] = project_object_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        active_flag = d.pop("ActiveFlag", UNSET)

        approver_user_name = d.pop("ApproverUserName", UNSET)

        approver_user_object_id = d.pop("ApproverUserObjectId", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        delegate_user_email_address = d.pop("DelegateUserEmailAddress", UNSET)

        delegate_user_name = d.pop("DelegateUserName", UNSET)

        delegate_user_object_id = d.pop("DelegateUserObjectId", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        project_object_id = d.pop("ProjectObjectId", UNSET)

        timesheet_delegate = cls(
            active_flag=active_flag,
            approver_user_name=approver_user_name,
            approver_user_object_id=approver_user_object_id,
            create_date=create_date,
            create_user=create_user,
            delegate_user_email_address=delegate_user_email_address,
            delegate_user_name=delegate_user_name,
            delegate_user_object_id=delegate_user_object_id,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            project_object_id=project_object_id,
        )

        timesheet_delegate.additional_properties = d
        return timesheet_delegate

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
