from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="UDFType")


@_attrs_define
class UDFType:
    """UDFType Entity

    Attributes:
        create_date (datetime.datetime | Unset): The date this user-defined field was created.
        create_user (str | Unset): The name of the user that created this user-defined field.
        data_type (str | Unset): The data type of the user-defined field: "Text", "Start Date", "Finish Date", "Cost",
            "Double", "Integer", "Indicator", or "Code".
        display_indicator_flag (bool | Unset):
        formula (str | Unset):
        is_calculated (bool | Unset): The flag indicating whether this is a calculated user defined field type.
        is_conditional (bool | Unset): The flag indicating whether this is a indicator user defined field type.
        is_secure_code (bool | Unset): the flag indicating whether this is a secure code type
        last_update_date (datetime.datetime | Unset): The date this user-defined field was last updated.
        last_update_user (str | Unset): The name of the user that last updated this user-defined field.
        object_id (int | Unset): The unique ID generated by the system.
        subject_area (str | Unset): The subject area of the user-defined field: "Activity", "Activity Expense",
            "Activity Step", "Activity Step Template Item", "Project", "Project Issue", "Project Risk", "Resource",
            "Resource Assignment", "WBS", or "Work Products and Documents".
        summary_method (str | Unset):
        title (str | Unset): The name/title of the user-defined field.
    """

    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    data_type: str | Unset = UNSET
    display_indicator_flag: bool | Unset = UNSET
    formula: str | Unset = UNSET
    is_calculated: bool | Unset = UNSET
    is_conditional: bool | Unset = UNSET
    is_secure_code: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    subject_area: str | Unset = UNSET
    summary_method: str | Unset = UNSET
    title: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        data_type = self.data_type

        display_indicator_flag = self.display_indicator_flag

        formula = self.formula

        is_calculated = self.is_calculated

        is_conditional = self.is_conditional

        is_secure_code = self.is_secure_code

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        subject_area = self.subject_area

        summary_method = self.summary_method

        title = self.title

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if data_type is not UNSET:
            field_dict["DataType"] = data_type
        if display_indicator_flag is not UNSET:
            field_dict["DisplayIndicatorFlag"] = display_indicator_flag
        if formula is not UNSET:
            field_dict["Formula"] = formula
        if is_calculated is not UNSET:
            field_dict["IsCalculated"] = is_calculated
        if is_conditional is not UNSET:
            field_dict["IsConditional"] = is_conditional
        if is_secure_code is not UNSET:
            field_dict["IsSecureCode"] = is_secure_code
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if subject_area is not UNSET:
            field_dict["SubjectArea"] = subject_area
        if summary_method is not UNSET:
            field_dict["SummaryMethod"] = summary_method
        if title is not UNSET:
            field_dict["Title"] = title

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        data_type = d.pop("DataType", UNSET)

        display_indicator_flag = d.pop("DisplayIndicatorFlag", UNSET)

        formula = d.pop("Formula", UNSET)

        is_calculated = d.pop("IsCalculated", UNSET)

        is_conditional = d.pop("IsConditional", UNSET)

        is_secure_code = d.pop("IsSecureCode", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        subject_area = d.pop("SubjectArea", UNSET)

        summary_method = d.pop("SummaryMethod", UNSET)

        title = d.pop("Title", UNSET)

        udf_type = cls(
            create_date=create_date,
            create_user=create_user,
            data_type=data_type,
            display_indicator_flag=display_indicator_flag,
            formula=formula,
            is_calculated=is_calculated,
            is_conditional=is_conditional,
            is_secure_code=is_secure_code,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            subject_area=subject_area,
            summary_method=summary_method,
            title=title,
        )

        udf_type.additional_properties = d
        return udf_type

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
