from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.resource_requests import ResourceRequests


T = TypeVar("T", bound="User")


@_attrs_define
class User:
    """User Entity

    Attributes:
        all_resource_access_flag (bool | Unset): The flag that determines whether the user has all resource access
            (TRUE) or restricted resource access (FALSE). Admin Superusers always have all resource access.
        assignment_staffing_preference (str | Unset): The value that determines whether the current or the new
            resource's Units per Time and Overtime factor is used to calculate costs when assigning the resource to an
            existing activity assignment. If the AssignmentStaffingPreference is set to 'Ask Me', the default value is then
            current resource.
        create_date (datetime.datetime | Unset): The date this user was created.
        create_user (str | Unset): The name of the user that created this user.
        currency_id (str | Unset): The unique currency abbreviation for the currency associated with this user.
        currency_name (str | Unset): The name of the currency associated with this user.
        currency_object_id (int | Unset): The unique ID of the associated currency.
        currency_show_decimals (bool | Unset): The flag which when set to true will show decimal places for the
            currency, and when set to false will not Display decimal places. Possible values : 'True' or 'False'
        currency_show_symbol (bool | Unset): The flag which when set to true will show Currency Symbol for the currency,
            and when set to false will not Display Currency Symbol. Possible values : 'True' or 'False'
        date_format_type (str | Unset): The date format type for the user: 'Month, Day, Year' , 'Day, Month, Year' or
            'Year, Month, Day'.
        date_separator (str | Unset): The date Separator for the user: '/' , '-' or '.'
        date_show_four_digit_year (bool | Unset): The flag which when set to true will show four digit year for the Date
            format specified, and when set to false will not show four digit year. Possible values : 'True' or 'False'
        date_show_minutes (bool | Unset): The flag which when set to true will show minutes value for the Time format
            specified, and when set to false will not show minutes value. Possible values : 'True' or 'False'
        date_time_format_type (str | Unset): The date format type for the user: '12 hour (1:30 PM)' , '24 hour (13:30)'
            or 'Do not show time'.
        date_use_leading_zero (bool | Unset): The flag which when set to true will show leading zero for the Date format
            specified, and when set to false will not show leading zero. Possible values : 'True' or 'False'
        date_use_month_name (bool | Unset): The flag which when set to true will show month value for the Date format
            specified, and when set to false will not show month value. Possible values : 'True' or 'False'
        duration_decimal_count (str | Unset): The Duration Decimal count for the user is the number of decimal places to
            be displayed for the Duration. : '0','1' or '2'.
        duration_unit_type (str | Unset): The Duration Unit Type for the user is the Display Time units In:
            'Hour','Day','Week','Month' or 'Year'.
        duration_use_fraction (bool | Unset): The flag which when set to true will show units for the Duration, and when
            set to false will not show units. Possible values : 'True' or 'False'
        email_address (str | Unset): The current user's return email address. This will be used in the "FROM" line for
            any email sent by this user. Example: "yourname@yourdomain.com". For MAPI users, this may just be the MAPI
            profile name or mailbox name.
        email_protocol (str | Unset): The email type for the user: 'Internet Mail' or 'MAPI Mail'.
        enable_user_to_modify_view_settings_flag (bool | Unset): The flag that when set to true allows the user to
            change his or her personal view settings in P6. When a user changes the user interface view settings, the
            changes do not affect the settings of other users assigned to the same view.
        financial_period_end_object_id (int | Unset): The unique ID generated by the system of the last financial period
            viewable in columns in Project Management.
        financial_period_start_object_id (int | Unset): The unique ID generated by the system of the first financial
            period viewable in columns in Project Management.
        guid (str | Unset): The globally unique ID generated by the system.
        global_profile_object_id (int | Unset): The unique ID of the global security profile assigned to the user. See
            the GlobalProfile class for constants defining the fixed profiles of Admin Superuser and No Global Privileges.
        last_update_date (datetime.datetime | Unset): The date this user was last updated.
        last_update_user (str | Unset): The name of the user that last updated this user.
        mail_server_login_name (str | Unset): The mail login name (profile name) for the current user to send outgoing
            email. If the email protocol is MAPI, this field should contain the MAPI profile name
        name (str | Unset): The user's login name.
        new_project_duration_type (str | Unset): the default duration type assigned to new activities. Valid values are
            'Fixed Units/Time', 'Fixed Duration and Units/Time', 'Fixed Units', or 'Fixed Duration and Units'.
        object_id (int | Unset): The unique ID generated by the system.
        office_phone (str | Unset): The work phone number of the user.
        outgoing_mail_server (str | Unset): The outgoing mail server (SMTP) address used to send outgoing email for this
            user. The address may be a host name or an IP address. This field is used only with the Internet email protocol,
            and is not required for MAPI.
        personal_name (str | Unset): The user's personal or actual name.
        rate_source_preference (str | Unset): The value that determines which price/unit will be used by default to
            calculate costs for the assignment when both a resource and role are assigned.
        reporting_flag (bool | Unset): The flag that determines whether the user can access ODS database as a database
            user.
        resource_requests (ResourceRequests | Unset):
        respect_activity_duration_type (bool | Unset): the setting that indicates whether to recalculate the Duration,
            Units, or Units/Time for existing assignments based on the activity Duration Type (true) or to preserve the
            Duration, Units, or Units/Time for existing assignments (false) when adding or removing assignments on
            activities.
        role_limit_display_option (str | Unset): The option for how RoleLimit is displayed. Valid values are 'Custom',
            and 'PrimaryRole'.
        show_duration_time_unit (bool | Unset): The flag which when set to true will show units for the Duration, and
            when set to false will not show units. Possible values : 'True' or 'False'
        show_time_unit (bool | Unset): The flag which when set to true will show units for the Time, and when set to
            false will not show units. Possible values : 'True' or 'False'
        small_scale_decimal_count (str | Unset): The Small Scale Decimal count for the user is the number of decimal
            places to be displayed for the Time. : '0','1' or '2'.
        small_scale_unit_type (str | Unset): The Small Scale Unit Type for the user is the Display Time units In:
            'Hour','Day','Week','Month' or 'Year'.
        small_scale_use_fraction (bool | Unset): The flag which when set to true will show sub units for the Time units
            format specified, and when set to false will not show sub units. Possible values : 'True' or 'False'
        team_member_activity_filters (str | Unset): The Statuser activity filters for the Team Member application.
        team_member_activity_sort_field (str | Unset): Select whether column name entries are sorted in ascending or
            descending order.
        team_member_activity_sort_order (str | Unset): From the Sort Order list, you can select to list projects in the
            scorecard in either ascending
        team_member_application_theme (str | Unset): The user interface theme setting for P6 Team Member Web.
        team_member_date_format (str | Unset): The date format setting for the P6 Team Member Web.
        team_member_display_time_flag (bool | Unset): The display hours setting for P6 Team Member Web.
        team_member_display_time_format (str | Unset): The display hours format setting for P6 Team Member Web.
        team_member_locale (str | Unset): The user-specific locale set for P6 Team Member Web.
        team_member_project_filter (str | Unset): The project filter for P6 Team Member Web.
        team_member_resource_filter (str | Unset): The user-specific resource filter for P6 Team Member Web.
        team_member_display_qr_quick_access (str | Unset): The flag that is used to to determine if a user has seen the
            QR quick access link in P6 Team Member Web.
        team_member_task_status_filter (str | Unset): The task status filter for P6 Team Member Web.
        team_member_timeframe_filter (str | Unset):
        team_member_wbs_filter (str | Unset): The time frame filter for P6 Team Member Web.
        team_member_work_unit_type (str | Unset): The user-specific wbs filter for P6 Team Member Web.
        units_per_time_show_as_percentage (bool | Unset): The flag which when set to true will show Units/Time as
            Percentage, and when set to false will display as Units/Duration. Possible values : 'True' or 'False'
        user_interface_view_object_id (int | Unset): The unique ID of the associated user interface view.
    """

    all_resource_access_flag: bool | Unset = UNSET
    assignment_staffing_preference: str | Unset = UNSET
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    currency_id: str | Unset = UNSET
    currency_name: str | Unset = UNSET
    currency_object_id: int | Unset = UNSET
    currency_show_decimals: bool | Unset = UNSET
    currency_show_symbol: bool | Unset = UNSET
    date_format_type: str | Unset = UNSET
    date_separator: str | Unset = UNSET
    date_show_four_digit_year: bool | Unset = UNSET
    date_show_minutes: bool | Unset = UNSET
    date_time_format_type: str | Unset = UNSET
    date_use_leading_zero: bool | Unset = UNSET
    date_use_month_name: bool | Unset = UNSET
    duration_decimal_count: str | Unset = UNSET
    duration_unit_type: str | Unset = UNSET
    duration_use_fraction: bool | Unset = UNSET
    email_address: str | Unset = UNSET
    email_protocol: str | Unset = UNSET
    enable_user_to_modify_view_settings_flag: bool | Unset = UNSET
    financial_period_end_object_id: int | Unset = UNSET
    financial_period_start_object_id: int | Unset = UNSET
    guid: str | Unset = UNSET
    global_profile_object_id: int | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    mail_server_login_name: str | Unset = UNSET
    name: str | Unset = UNSET
    new_project_duration_type: str | Unset = UNSET
    object_id: int | Unset = UNSET
    office_phone: str | Unset = UNSET
    outgoing_mail_server: str | Unset = UNSET
    personal_name: str | Unset = UNSET
    rate_source_preference: str | Unset = UNSET
    reporting_flag: bool | Unset = UNSET
    resource_requests: ResourceRequests | Unset = UNSET
    respect_activity_duration_type: bool | Unset = UNSET
    role_limit_display_option: str | Unset = UNSET
    show_duration_time_unit: bool | Unset = UNSET
    show_time_unit: bool | Unset = UNSET
    small_scale_decimal_count: str | Unset = UNSET
    small_scale_unit_type: str | Unset = UNSET
    small_scale_use_fraction: bool | Unset = UNSET
    team_member_activity_filters: str | Unset = UNSET
    team_member_activity_sort_field: str | Unset = UNSET
    team_member_activity_sort_order: str | Unset = UNSET
    team_member_application_theme: str | Unset = UNSET
    team_member_date_format: str | Unset = UNSET
    team_member_display_time_flag: bool | Unset = UNSET
    team_member_display_time_format: str | Unset = UNSET
    team_member_locale: str | Unset = UNSET
    team_member_project_filter: str | Unset = UNSET
    team_member_resource_filter: str | Unset = UNSET
    team_member_display_qr_quick_access: str | Unset = UNSET
    team_member_task_status_filter: str | Unset = UNSET
    team_member_timeframe_filter: str | Unset = UNSET
    team_member_wbs_filter: str | Unset = UNSET
    team_member_work_unit_type: str | Unset = UNSET
    units_per_time_show_as_percentage: bool | Unset = UNSET
    user_interface_view_object_id: int | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        all_resource_access_flag = self.all_resource_access_flag

        assignment_staffing_preference = self.assignment_staffing_preference

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        currency_id = self.currency_id

        currency_name = self.currency_name

        currency_object_id = self.currency_object_id

        currency_show_decimals = self.currency_show_decimals

        currency_show_symbol = self.currency_show_symbol

        date_format_type = self.date_format_type

        date_separator = self.date_separator

        date_show_four_digit_year = self.date_show_four_digit_year

        date_show_minutes = self.date_show_minutes

        date_time_format_type = self.date_time_format_type

        date_use_leading_zero = self.date_use_leading_zero

        date_use_month_name = self.date_use_month_name

        duration_decimal_count = self.duration_decimal_count

        duration_unit_type = self.duration_unit_type

        duration_use_fraction = self.duration_use_fraction

        email_address = self.email_address

        email_protocol = self.email_protocol

        enable_user_to_modify_view_settings_flag = self.enable_user_to_modify_view_settings_flag

        financial_period_end_object_id = self.financial_period_end_object_id

        financial_period_start_object_id = self.financial_period_start_object_id

        guid = self.guid

        global_profile_object_id = self.global_profile_object_id

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        mail_server_login_name = self.mail_server_login_name

        name = self.name

        new_project_duration_type = self.new_project_duration_type

        object_id = self.object_id

        office_phone = self.office_phone

        outgoing_mail_server = self.outgoing_mail_server

        personal_name = self.personal_name

        rate_source_preference = self.rate_source_preference

        reporting_flag = self.reporting_flag

        resource_requests: dict[str, Any] | Unset = UNSET
        if not isinstance(self.resource_requests, Unset):
            resource_requests = self.resource_requests.to_dict()

        respect_activity_duration_type = self.respect_activity_duration_type

        role_limit_display_option = self.role_limit_display_option

        show_duration_time_unit = self.show_duration_time_unit

        show_time_unit = self.show_time_unit

        small_scale_decimal_count = self.small_scale_decimal_count

        small_scale_unit_type = self.small_scale_unit_type

        small_scale_use_fraction = self.small_scale_use_fraction

        team_member_activity_filters = self.team_member_activity_filters

        team_member_activity_sort_field = self.team_member_activity_sort_field

        team_member_activity_sort_order = self.team_member_activity_sort_order

        team_member_application_theme = self.team_member_application_theme

        team_member_date_format = self.team_member_date_format

        team_member_display_time_flag = self.team_member_display_time_flag

        team_member_display_time_format = self.team_member_display_time_format

        team_member_locale = self.team_member_locale

        team_member_project_filter = self.team_member_project_filter

        team_member_resource_filter = self.team_member_resource_filter

        team_member_display_qr_quick_access = self.team_member_display_qr_quick_access

        team_member_task_status_filter = self.team_member_task_status_filter

        team_member_timeframe_filter = self.team_member_timeframe_filter

        team_member_wbs_filter = self.team_member_wbs_filter

        team_member_work_unit_type = self.team_member_work_unit_type

        units_per_time_show_as_percentage = self.units_per_time_show_as_percentage

        user_interface_view_object_id = self.user_interface_view_object_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if all_resource_access_flag is not UNSET:
            field_dict["AllResourceAccessFlag"] = all_resource_access_flag
        if assignment_staffing_preference is not UNSET:
            field_dict["AssignmentStaffingPreference"] = assignment_staffing_preference
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if currency_id is not UNSET:
            field_dict["CurrencyId"] = currency_id
        if currency_name is not UNSET:
            field_dict["CurrencyName"] = currency_name
        if currency_object_id is not UNSET:
            field_dict["CurrencyObjectId"] = currency_object_id
        if currency_show_decimals is not UNSET:
            field_dict["CurrencyShowDecimals"] = currency_show_decimals
        if currency_show_symbol is not UNSET:
            field_dict["CurrencyShowSymbol"] = currency_show_symbol
        if date_format_type is not UNSET:
            field_dict["DateFormatType"] = date_format_type
        if date_separator is not UNSET:
            field_dict["DateSeparator"] = date_separator
        if date_show_four_digit_year is not UNSET:
            field_dict["DateShowFourDigitYear"] = date_show_four_digit_year
        if date_show_minutes is not UNSET:
            field_dict["DateShowMinutes"] = date_show_minutes
        if date_time_format_type is not UNSET:
            field_dict["DateTimeFormatType"] = date_time_format_type
        if date_use_leading_zero is not UNSET:
            field_dict["DateUseLeadingZero"] = date_use_leading_zero
        if date_use_month_name is not UNSET:
            field_dict["DateUseMonthName"] = date_use_month_name
        if duration_decimal_count is not UNSET:
            field_dict["DurationDecimalCount"] = duration_decimal_count
        if duration_unit_type is not UNSET:
            field_dict["DurationUnitType"] = duration_unit_type
        if duration_use_fraction is not UNSET:
            field_dict["DurationUseFraction"] = duration_use_fraction
        if email_address is not UNSET:
            field_dict["EmailAddress"] = email_address
        if email_protocol is not UNSET:
            field_dict["EmailProtocol"] = email_protocol
        if enable_user_to_modify_view_settings_flag is not UNSET:
            field_dict["EnableUserToModifyViewSettingsFlag"] = enable_user_to_modify_view_settings_flag
        if financial_period_end_object_id is not UNSET:
            field_dict["FinancialPeriodEndObjectId"] = financial_period_end_object_id
        if financial_period_start_object_id is not UNSET:
            field_dict["FinancialPeriodStartObjectId"] = financial_period_start_object_id
        if guid is not UNSET:
            field_dict["GUID"] = guid
        if global_profile_object_id is not UNSET:
            field_dict["GlobalProfileObjectId"] = global_profile_object_id
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if mail_server_login_name is not UNSET:
            field_dict["MailServerLoginName"] = mail_server_login_name
        if name is not UNSET:
            field_dict["Name"] = name
        if new_project_duration_type is not UNSET:
            field_dict["NewProjectDurationType"] = new_project_duration_type
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if office_phone is not UNSET:
            field_dict["OfficePhone"] = office_phone
        if outgoing_mail_server is not UNSET:
            field_dict["OutgoingMailServer"] = outgoing_mail_server
        if personal_name is not UNSET:
            field_dict["PersonalName"] = personal_name
        if rate_source_preference is not UNSET:
            field_dict["RateSourcePreference"] = rate_source_preference
        if reporting_flag is not UNSET:
            field_dict["ReportingFlag"] = reporting_flag
        if resource_requests is not UNSET:
            field_dict["ResourceRequests"] = resource_requests
        if respect_activity_duration_type is not UNSET:
            field_dict["RespectActivityDurationType"] = respect_activity_duration_type
        if role_limit_display_option is not UNSET:
            field_dict["RoleLimitDisplayOption"] = role_limit_display_option
        if show_duration_time_unit is not UNSET:
            field_dict["ShowDurationTimeUnit"] = show_duration_time_unit
        if show_time_unit is not UNSET:
            field_dict["ShowTimeUnit"] = show_time_unit
        if small_scale_decimal_count is not UNSET:
            field_dict["SmallScaleDecimalCount"] = small_scale_decimal_count
        if small_scale_unit_type is not UNSET:
            field_dict["SmallScaleUnitType"] = small_scale_unit_type
        if small_scale_use_fraction is not UNSET:
            field_dict["SmallScaleUseFraction"] = small_scale_use_fraction
        if team_member_activity_filters is not UNSET:
            field_dict["TeamMemberActivityFilters"] = team_member_activity_filters
        if team_member_activity_sort_field is not UNSET:
            field_dict["TeamMemberActivitySortField"] = team_member_activity_sort_field
        if team_member_activity_sort_order is not UNSET:
            field_dict["TeamMemberActivitySortOrder"] = team_member_activity_sort_order
        if team_member_application_theme is not UNSET:
            field_dict["TeamMemberApplicationTheme"] = team_member_application_theme
        if team_member_date_format is not UNSET:
            field_dict["TeamMemberDateFormat"] = team_member_date_format
        if team_member_display_time_flag is not UNSET:
            field_dict["TeamMemberDisplayTimeFlag"] = team_member_display_time_flag
        if team_member_display_time_format is not UNSET:
            field_dict["TeamMemberDisplayTimeFormat"] = team_member_display_time_format
        if team_member_locale is not UNSET:
            field_dict["TeamMemberLocale"] = team_member_locale
        if team_member_project_filter is not UNSET:
            field_dict["TeamMemberProjectFilter"] = team_member_project_filter
        if team_member_resource_filter is not UNSET:
            field_dict["TeamMemberResourceFilter"] = team_member_resource_filter
        if team_member_display_qr_quick_access is not UNSET:
            field_dict["TeamMemberDisplayQRQuickAccess"] = team_member_display_qr_quick_access
        if team_member_task_status_filter is not UNSET:
            field_dict["TeamMemberTaskStatusFilter"] = team_member_task_status_filter
        if team_member_timeframe_filter is not UNSET:
            field_dict["TeamMemberTimeframeFilter"] = team_member_timeframe_filter
        if team_member_wbs_filter is not UNSET:
            field_dict["TeamMemberWBSFilter"] = team_member_wbs_filter
        if team_member_work_unit_type is not UNSET:
            field_dict["TeamMemberWorkUnitType"] = team_member_work_unit_type
        if units_per_time_show_as_percentage is not UNSET:
            field_dict["UnitsPerTimeShowAsPercentage"] = units_per_time_show_as_percentage
        if user_interface_view_object_id is not UNSET:
            field_dict["UserInterfaceViewObjectId"] = user_interface_view_object_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.resource_requests import ResourceRequests

        d = dict(src_dict)
        all_resource_access_flag = d.pop("AllResourceAccessFlag", UNSET)

        assignment_staffing_preference = d.pop("AssignmentStaffingPreference", UNSET)

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        currency_id = d.pop("CurrencyId", UNSET)

        currency_name = d.pop("CurrencyName", UNSET)

        currency_object_id = d.pop("CurrencyObjectId", UNSET)

        currency_show_decimals = d.pop("CurrencyShowDecimals", UNSET)

        currency_show_symbol = d.pop("CurrencyShowSymbol", UNSET)

        date_format_type = d.pop("DateFormatType", UNSET)

        date_separator = d.pop("DateSeparator", UNSET)

        date_show_four_digit_year = d.pop("DateShowFourDigitYear", UNSET)

        date_show_minutes = d.pop("DateShowMinutes", UNSET)

        date_time_format_type = d.pop("DateTimeFormatType", UNSET)

        date_use_leading_zero = d.pop("DateUseLeadingZero", UNSET)

        date_use_month_name = d.pop("DateUseMonthName", UNSET)

        duration_decimal_count = d.pop("DurationDecimalCount", UNSET)

        duration_unit_type = d.pop("DurationUnitType", UNSET)

        duration_use_fraction = d.pop("DurationUseFraction", UNSET)

        email_address = d.pop("EmailAddress", UNSET)

        email_protocol = d.pop("EmailProtocol", UNSET)

        enable_user_to_modify_view_settings_flag = d.pop("EnableUserToModifyViewSettingsFlag", UNSET)

        financial_period_end_object_id = d.pop("FinancialPeriodEndObjectId", UNSET)

        financial_period_start_object_id = d.pop("FinancialPeriodStartObjectId", UNSET)

        guid = d.pop("GUID", UNSET)

        global_profile_object_id = d.pop("GlobalProfileObjectId", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        mail_server_login_name = d.pop("MailServerLoginName", UNSET)

        name = d.pop("Name", UNSET)

        new_project_duration_type = d.pop("NewProjectDurationType", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        office_phone = d.pop("OfficePhone", UNSET)

        outgoing_mail_server = d.pop("OutgoingMailServer", UNSET)

        personal_name = d.pop("PersonalName", UNSET)

        rate_source_preference = d.pop("RateSourcePreference", UNSET)

        reporting_flag = d.pop("ReportingFlag", UNSET)

        _resource_requests = d.pop("ResourceRequests", UNSET)
        resource_requests: ResourceRequests | Unset
        if isinstance(_resource_requests, Unset):
            resource_requests = UNSET
        else:
            resource_requests = ResourceRequests.from_dict(_resource_requests)

        respect_activity_duration_type = d.pop("RespectActivityDurationType", UNSET)

        role_limit_display_option = d.pop("RoleLimitDisplayOption", UNSET)

        show_duration_time_unit = d.pop("ShowDurationTimeUnit", UNSET)

        show_time_unit = d.pop("ShowTimeUnit", UNSET)

        small_scale_decimal_count = d.pop("SmallScaleDecimalCount", UNSET)

        small_scale_unit_type = d.pop("SmallScaleUnitType", UNSET)

        small_scale_use_fraction = d.pop("SmallScaleUseFraction", UNSET)

        team_member_activity_filters = d.pop("TeamMemberActivityFilters", UNSET)

        team_member_activity_sort_field = d.pop("TeamMemberActivitySortField", UNSET)

        team_member_activity_sort_order = d.pop("TeamMemberActivitySortOrder", UNSET)

        team_member_application_theme = d.pop("TeamMemberApplicationTheme", UNSET)

        team_member_date_format = d.pop("TeamMemberDateFormat", UNSET)

        team_member_display_time_flag = d.pop("TeamMemberDisplayTimeFlag", UNSET)

        team_member_display_time_format = d.pop("TeamMemberDisplayTimeFormat", UNSET)

        team_member_locale = d.pop("TeamMemberLocale", UNSET)

        team_member_project_filter = d.pop("TeamMemberProjectFilter", UNSET)

        team_member_resource_filter = d.pop("TeamMemberResourceFilter", UNSET)

        team_member_display_qr_quick_access = d.pop("TeamMemberDisplayQRQuickAccess", UNSET)

        team_member_task_status_filter = d.pop("TeamMemberTaskStatusFilter", UNSET)

        team_member_timeframe_filter = d.pop("TeamMemberTimeframeFilter", UNSET)

        team_member_wbs_filter = d.pop("TeamMemberWBSFilter", UNSET)

        team_member_work_unit_type = d.pop("TeamMemberWorkUnitType", UNSET)

        units_per_time_show_as_percentage = d.pop("UnitsPerTimeShowAsPercentage", UNSET)

        user_interface_view_object_id = d.pop("UserInterfaceViewObjectId", UNSET)

        user = cls(
            all_resource_access_flag=all_resource_access_flag,
            assignment_staffing_preference=assignment_staffing_preference,
            create_date=create_date,
            create_user=create_user,
            currency_id=currency_id,
            currency_name=currency_name,
            currency_object_id=currency_object_id,
            currency_show_decimals=currency_show_decimals,
            currency_show_symbol=currency_show_symbol,
            date_format_type=date_format_type,
            date_separator=date_separator,
            date_show_four_digit_year=date_show_four_digit_year,
            date_show_minutes=date_show_minutes,
            date_time_format_type=date_time_format_type,
            date_use_leading_zero=date_use_leading_zero,
            date_use_month_name=date_use_month_name,
            duration_decimal_count=duration_decimal_count,
            duration_unit_type=duration_unit_type,
            duration_use_fraction=duration_use_fraction,
            email_address=email_address,
            email_protocol=email_protocol,
            enable_user_to_modify_view_settings_flag=enable_user_to_modify_view_settings_flag,
            financial_period_end_object_id=financial_period_end_object_id,
            financial_period_start_object_id=financial_period_start_object_id,
            guid=guid,
            global_profile_object_id=global_profile_object_id,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            mail_server_login_name=mail_server_login_name,
            name=name,
            new_project_duration_type=new_project_duration_type,
            object_id=object_id,
            office_phone=office_phone,
            outgoing_mail_server=outgoing_mail_server,
            personal_name=personal_name,
            rate_source_preference=rate_source_preference,
            reporting_flag=reporting_flag,
            resource_requests=resource_requests,
            respect_activity_duration_type=respect_activity_duration_type,
            role_limit_display_option=role_limit_display_option,
            show_duration_time_unit=show_duration_time_unit,
            show_time_unit=show_time_unit,
            small_scale_decimal_count=small_scale_decimal_count,
            small_scale_unit_type=small_scale_unit_type,
            small_scale_use_fraction=small_scale_use_fraction,
            team_member_activity_filters=team_member_activity_filters,
            team_member_activity_sort_field=team_member_activity_sort_field,
            team_member_activity_sort_order=team_member_activity_sort_order,
            team_member_application_theme=team_member_application_theme,
            team_member_date_format=team_member_date_format,
            team_member_display_time_flag=team_member_display_time_flag,
            team_member_display_time_format=team_member_display_time_format,
            team_member_locale=team_member_locale,
            team_member_project_filter=team_member_project_filter,
            team_member_resource_filter=team_member_resource_filter,
            team_member_display_qr_quick_access=team_member_display_qr_quick_access,
            team_member_task_status_filter=team_member_task_status_filter,
            team_member_timeframe_filter=team_member_timeframe_filter,
            team_member_wbs_filter=team_member_wbs_filter,
            team_member_work_unit_type=team_member_work_unit_type,
            units_per_time_show_as_percentage=units_per_time_show_as_percentage,
            user_interface_view_object_id=user_interface_view_object_id,
        )

        user.additional_properties = d
        return user

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
