from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="UserFieldTitle")


@_attrs_define
class UserFieldTitle:
    """UserFieldTitle Entity

    Attributes:
        create_date (datetime.datetime | Unset): The date this user field title was created.
        create_user (str | Unset): The name of the user that created this user field title.
        default_title (str | Unset): The default title of the column name.
        last_update_date (datetime.datetime | Unset): The date this user field title was last updated.
        last_update_user (str | Unset): The name of the user that last updated this user field title.
        object_id (int | Unset): The unique ID generated by the system.
        object_name (str | Unset): The name of the business object to which this user defined column belongs.
        user_defined_title (str | Unset): The user defined column name.
        user_table_name (str | Unset): The table name of the user defined column.
    """

    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    default_title: str | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    object_id: int | Unset = UNSET
    object_name: str | Unset = UNSET
    user_defined_title: str | Unset = UNSET
    user_table_name: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        default_title = self.default_title

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        object_id = self.object_id

        object_name = self.object_name

        user_defined_title = self.user_defined_title

        user_table_name = self.user_table_name

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if default_title is not UNSET:
            field_dict["DefaultTitle"] = default_title
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if object_name is not UNSET:
            field_dict["ObjectName"] = object_name
        if user_defined_title is not UNSET:
            field_dict["UserDefinedTitle"] = user_defined_title
        if user_table_name is not UNSET:
            field_dict["UserTableName"] = user_table_name

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        default_title = d.pop("DefaultTitle", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        object_name = d.pop("ObjectName", UNSET)

        user_defined_title = d.pop("UserDefinedTitle", UNSET)

        user_table_name = d.pop("UserTableName", UNSET)

        user_field_title = cls(
            create_date=create_date,
            create_user=create_user,
            default_title=default_title,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            object_id=object_id,
            object_name=object_name,
            user_defined_title=user_defined_title,
            user_table_name=user_table_name,
        )

        user_field_title.additional_properties = d
        return user_field_title

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
