from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field
from dateutil.parser import isoparse

from ..types import UNSET, Unset

T = TypeVar("T", bound="WBSMilestone")


@_attrs_define
class WBSMilestone:
    """WBSMilestone Entity

    Attributes:
        name (str): The name of the WBS milestone.
        project_object_id (int): The unique ID of the associated project.
        wbs_object_id (int): The unique ID of the WBS where the WBS milestone is assigned.
        create_date (datetime.datetime | Unset): The date this WBS milestone was created.
        create_user (str | Unset): The name of the user that created this WBS milestone.
        is_baseline (bool | Unset): The boolean value indicating if this business object is related to a Project or
            Baseline
        is_completed (bool | Unset): The flag that indicates whether the step has been completed.
        is_template (bool | Unset): The boolean value indicating if this business object is related to a template
            Project.
        last_update_date (datetime.datetime | Unset): The date this WBS milestone was last updated.
        last_update_user (str | Unset): The name of the user that last updated this WBS milestone.
        project_id (str | Unset): The short code that uniquely identifies the project.
        object_id (int | Unset): The unique ID generated by the system.
        sequence_number (int | Unset): The sequence number for sorting.
        wbs_code (str | Unset): The short code assigned to each WBS element for identification. Each WBS element is
            uniquely identified by concatenating its own code together with its parents' codes.
        wbs_name (str | Unset): The name of the WBS element.
        weight (float | Unset): The weight that is assigned to the milestone.
    """

    name: str
    project_object_id: int
    wbs_object_id: int
    create_date: datetime.datetime | Unset = UNSET
    create_user: str | Unset = UNSET
    is_baseline: bool | Unset = UNSET
    is_completed: bool | Unset = UNSET
    is_template: bool | Unset = UNSET
    last_update_date: datetime.datetime | Unset = UNSET
    last_update_user: str | Unset = UNSET
    project_id: str | Unset = UNSET
    object_id: int | Unset = UNSET
    sequence_number: int | Unset = UNSET
    wbs_code: str | Unset = UNSET
    wbs_name: str | Unset = UNSET
    weight: float | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        project_object_id = self.project_object_id

        wbs_object_id = self.wbs_object_id

        create_date: str | Unset = UNSET
        if not isinstance(self.create_date, Unset):
            create_date = self.create_date.isoformat()

        create_user = self.create_user

        is_baseline = self.is_baseline

        is_completed = self.is_completed

        is_template = self.is_template

        last_update_date: str | Unset = UNSET
        if not isinstance(self.last_update_date, Unset):
            last_update_date = self.last_update_date.isoformat()

        last_update_user = self.last_update_user

        project_id = self.project_id

        object_id = self.object_id

        sequence_number = self.sequence_number

        wbs_code = self.wbs_code

        wbs_name = self.wbs_name

        weight = self.weight

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "Name": name,
                "ProjectObjectId": project_object_id,
                "WBSObjectId": wbs_object_id,
            }
        )
        if create_date is not UNSET:
            field_dict["CreateDate"] = create_date
        if create_user is not UNSET:
            field_dict["CreateUser"] = create_user
        if is_baseline is not UNSET:
            field_dict["IsBaseline"] = is_baseline
        if is_completed is not UNSET:
            field_dict["IsCompleted"] = is_completed
        if is_template is not UNSET:
            field_dict["IsTemplate"] = is_template
        if last_update_date is not UNSET:
            field_dict["LastUpdateDate"] = last_update_date
        if last_update_user is not UNSET:
            field_dict["LastUpdateUser"] = last_update_user
        if project_id is not UNSET:
            field_dict["ProjectId"] = project_id
        if object_id is not UNSET:
            field_dict["ObjectId"] = object_id
        if sequence_number is not UNSET:
            field_dict["SequenceNumber"] = sequence_number
        if wbs_code is not UNSET:
            field_dict["WBSCode"] = wbs_code
        if wbs_name is not UNSET:
            field_dict["WBSName"] = wbs_name
        if weight is not UNSET:
            field_dict["Weight"] = weight

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("Name")

        project_object_id = d.pop("ProjectObjectId")

        wbs_object_id = d.pop("WBSObjectId")

        _create_date = d.pop("CreateDate", UNSET)
        create_date: datetime.datetime | Unset
        if isinstance(_create_date, Unset):
            create_date = UNSET
        else:
            create_date = isoparse(_create_date)

        create_user = d.pop("CreateUser", UNSET)

        is_baseline = d.pop("IsBaseline", UNSET)

        is_completed = d.pop("IsCompleted", UNSET)

        is_template = d.pop("IsTemplate", UNSET)

        _last_update_date = d.pop("LastUpdateDate", UNSET)
        last_update_date: datetime.datetime | Unset
        if isinstance(_last_update_date, Unset):
            last_update_date = UNSET
        else:
            last_update_date = isoparse(_last_update_date)

        last_update_user = d.pop("LastUpdateUser", UNSET)

        project_id = d.pop("ProjectId", UNSET)

        object_id = d.pop("ObjectId", UNSET)

        sequence_number = d.pop("SequenceNumber", UNSET)

        wbs_code = d.pop("WBSCode", UNSET)

        wbs_name = d.pop("WBSName", UNSET)

        weight = d.pop("Weight", UNSET)

        wbs_milestone = cls(
            name=name,
            project_object_id=project_object_id,
            wbs_object_id=wbs_object_id,
            create_date=create_date,
            create_user=create_user,
            is_baseline=is_baseline,
            is_completed=is_completed,
            is_template=is_template,
            last_update_date=last_update_date,
            last_update_user=last_update_user,
            project_id=project_id,
            object_id=object_id,
            sequence_number=sequence_number,
            wbs_code=wbs_code,
            wbs_name=wbs_name,
            weight=weight,
        )

        wbs_milestone.additional_properties = d
        return wbs_milestone

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
